// 2025 MLB Players Database - Organized by Position
// Based on Baseball Reference JAWS Rankings

const players2025 = {
    "1B": {
        "legendary": [
            { "name": "Lou Gehrig", "rating": 99, "team": "Yankees", "rarity": "legendary" },
            { "name": "Jimmie Foxx", "rating": 98, "team": "Athletics", "rarity": "legendary" },
            { "name": "Albert Pujols", "rating": 97, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Mark McGwire", "rating": 97, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Hank Greenberg", "rating": 95, "team": "Tigers", "rarity": "legendary" },
            { "name": "Miguel Cabrera", "rating": 94, "team": "Tigers", "rarity": "legendary" },
            { "name": "Eddie Murray", "rating": 94, "team": "Orioles", "rarity": "legendary" },
            { "name": "Todd Helton", "rating": 93, "team": "Rockies", "rarity": "legendary" },
            { "name": "Jim Thome", "rating": 93, "team": "Indians", "rarity": "legendary" },
            { "name": "Jeff Bagwell", "rating": 92, "team": "Astros", "rarity": "legendary" },
            { "name": "Freddie Freeman", "rating": 92, "team": "Dodgers", "rarity": "legendary" },
            { "name": "Harmon Killebrew", "rating": 92, "team": "Twins", "rarity": "legendary" },
            { "name": "Frank Thomas", "rating": 90, "team": "White Sox", "rarity": "legendary" },
            { "name": "Joey Votto", "rating": 89, "team": "Reds", "rarity": "legendary" },
            { "name": "Paul Goldschmidt", "rating": 87, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Carlos Delgado", "rating": 85, "team": "Blue Jays", "rarity": "legendary" },
            { "name": "Vladimir Guerrero", "rating": 85, "team": "Expos", "rarity": "legendary" },
            { "name": "Willie McCovey", "rating": 84, "team": "Giants", "rarity": "legendary" },
            { "name": "Keith Hernandez", "rating": 83, "team": "Mets", "rarity": "legendary" },
            { "name": "Don Mattingly", "rating": 82, "team": "Yankees", "rarity": "legendary" },
            { "name": "Will Clark", "rating": 81, "team": "Giants", "rarity": "legendary" },
            { "name": "John Olerud", "rating": 79, "team": "Blue Jays", "rarity": "legendary" },
            { "name": "Mo Vaughn", "rating": 76, "team": "Red Sox", "rarity": "legendary" },
            {"name": "Jason Giambi","rating": 75,"team": "Athletics","rarity": "legendary"}
        ],
        "common": [
            { "name": "Anthony Rizzo", "rating": 74, "team": "Yankees", "rarity": "common" },
            { "name": "Pete Alonso", "rating": 73, "team": "Mets", "rarity": "common" },
            { "name": "Matt Olson", "rating": 72, "team": "Braves", "rarity": "common" },
            { "name": "Rhys Hoskins", "rating": 71, "team": "Phillies", "rarity": "common" },
            { "name": "Josh Bell", "rating": 70, "team": "Marlins", "rarity": "common" },
            { "name": "Ty France", "rating": 69, "team": "Mariners", "rarity": "common" },
            { "name": "Nathaniel Lowe", "rating": 68, "team": "Rangers", "rarity": "common" },
            { "name": "Christian Walker", "rating": 67, "team": "Diamondbacks", "rarity": "common" },
            { "name": "Vladimir Guerrero Jr.", "rating": 66, "team": "Blue Jays", "rarity": "common" },
            { "name": "Jose Abreu", "rating": 65, "team": "Astros", "rarity": "common" },
            { "name": "C.J. Cron", "rating": 64, "team": "Rockies", "rarity": "common" },
            { "name": "Rowdy Tellez", "rating": 63, "team": "Brewers", "rarity": "common" },
            { "name": "Jesus Aguilar", "rating": 62, "team": "Marlins", "rarity": "common" },
            { "name": "Brandon Belt", "rating": 61, "team": "Giants", "rarity": "common" },
            { "name": "Paul Konerko", "rating": 60, "team": "White Sox", "rarity": "common" },
            { "name": "Eric Hosmer", "rating": 59, "team": "Royals", "rarity": "common" },
            { "name": "Justin Smoak", "rating": 58, "team": "Blue Jays", "rarity": "common" },
            { "name": "Yuli Gurriel", "rating": 57, "team": "Astros", "rarity": "common" },
            { "name": "Ji-Man Choi", "rating": 56, "team": "Rays", "rarity": "common" },
            { "name": "Bobby Abreu", "rating": 55, "team": "Phillies", "rarity": "common" },
            { "name": "Luke Voit", "rating": 54, "team": "Padres", "rarity": "common" },
            { "name": "Garrett Cooper", "rating": 53, "team": "Marlins", "rarity": "common" },
            { "name": "Josh Naylor", "rating": 52, "team": "Guardians", "rarity": "common" },
            { "name": "Spencer Torkelson", "rating": 51, "team": "Tigers", "rarity": "common" },
            { "name": "Triston Casas", "rating": 50, "team": "Red Sox", "rarity": "common" }

        ]
    },
    "2B": {
        "legendary": [
            { "name": "Rogers Hornsby", "rating": 99, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Joe Morgan", "rating": 98, "team": "Reds", "rarity": "legendary" },
            { "name": "Eddie Collins", "rating": 97, "team": "Athletics", "rarity": "legendary" },
            { "name": "Charlie Gehringer", "rating": 96, "team": "Tigers", "rarity": "legendary" },
            { "name": "Rod Carew", "rating": 96, "team": "Twins", "rarity": "legendary" },
            { "name": "Jackie Robinson", "rating": 95, "team": "Dodgers", "rarity": "legendary" },
            { "name": "Roberto Alomar", "rating": 94, "team": "Blue Jays", "rarity": "legendary" },
            { "name": "Ryne Sandberg", "rating": 93, "team": "Cubs", "rarity": "legendary" },
            { "name": "Craig Biggio", "rating": 92, "team": "Astros", "rarity": "legendary" },
            { "name": "Robinson Cano", "rating": 91, "team": "Yankees", "rarity": "legendary" },
            { "name": "Nap Lajoie", "rating": 90, "team": "Indians", "rarity": "legendary" },
            { "name": "Jose Altuve", "rating": 89, "team": "Astros", "rarity": "legendary" },
            { "name": "Chase Utley", "rating": 88, "team": "Phillies", "rarity": "legendary" },
            { "name": "Alfonso Soriano", "rating": 88, "team": "Yankees", "rarity": "legendary" },
            { "name": "Jeff Kent", "rating": 87, "team": "Giants", "rarity": "legendary" },
            { "name": "Ian Kinsler", "rating": 87, "team": "Rangers", "rarity": "legendary" },
            { "name": "Lou Whitaker", "rating": 86, "team": "Tigers", "rarity": "legendary" },
            { "name": "Bobby Doerr", "rating": 85, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Marcus Semien", "rating": 85, "team": "Rangers", "rarity": "legendary" },
            { "name": "Dustin Pedroia", "rating": 83, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Brian Dozier", "rating": 83, "team": "Twins", "rarity": "legendary" },
            { "name": "Ben Zobrist", "rating": 80, "team": "Rays", "rarity": "legendary" },
            { "name": "Brandon Phillips", "rating": 78, "team": "Reds", "rarity": "legendary" },
            { "name": "Dan Uggla", "rating": 76, "team": "Marlins", "rarity": "legendary" },
            {"name": "Jose Vidro","rating": 75,"team": "Expos","rarity": "legendary"}
        ],
        "common": [
            { "name": "Ozzie Albies", "rating": 74, "team": "Braves", "rarity": "common" },
            { "name": "Jazz Chisholm Jr.", "rating": 74, "team": "Marlins", "rarity": "common" },
            { "name": "Gleyber Torres", "rating": 73, "team": "Yankees", "rarity": "common" },
            { "name": "Andrés Giménez", "rating": 71, "team": "Guardians", "rarity": "common" },
            { "name": "Nico Hoerner", "rating": 70, "team": "Cubs", "rarity": "common" },
            { "name": "Jorge Polanco", "rating": 69, "team": "Twins", "rarity": "common" },
            { "name": "Jonathan India", "rating": 68, "team": "Reds", "rarity": "common" },
            { "name": "Adam Frazier", "rating": 67, "team": "Orioles", "rarity": "common" },
            { "name": "Whit Merrifield", "rating": 66, "team": "Blue Jays", "rarity": "common" },
            { "name": "Josh Harrison", "rating": 65, "team": "Phillies", "rarity": "common" },
            { "name": "Luis Arraez", "rating": 64, "team": "Marlins", "rarity": "common" },
            { "name": "Kolten Wong", "rating": 63, "team": "Mariners", "rarity": "common" },
            { "name": "Jean Segura", "rating": 62, "team": "Marlins", "rarity": "common" },
            { "name": "Luis Urias", "rating": 61, "team": "Red Sox", "rarity": "common" },
            { "name": "Nick Madrigal", "rating": 60, "team": "Cubs", "rarity": "common" },
            { "name": "Ketel Marte", "rating": 59, "team": "Diamondbacks", "rarity": "common" },
            { "name": "Tommy Edman", "rating": 58, "team": "Cardinals", "rarity": "common" },
            { "name": "Jake Cronenworth", "rating": 57, "team": "Padres", "rarity": "common" },
            { "name": "Ryan McMahon", "rating": 56, "team": "Rockies", "rarity": "common" },
            { "name": "Nicky Lopez", "rating": 55, "team": "Braves", "rarity": "common" },
            { "name": "Cesar Hernandez", "rating": 54, "team": "Nationals", "rarity": "common" },
            { "name": "Brendan Rodgers", "rating": 52, "team": "Rockies", "rarity": "common" },
            { "name": "Michael Chavis", "rating": 51, "team": "Pirates", "rarity": "common" },
            { "name": "Kike Hernandez", "rating": 50, "team": "Dodgers", "rarity": "common" }
              
        ]
    },
    "3B": {
        "legendary": [
            { "name": "Mike Schmidt", "rating": 99, "team": "Phillies", "rarity": "legendary" },
            { "name": "Wade Boggs", "rating": 98, "team": "Red Sox", "rarity": "legendary" },
            { "name": "George Brett", "rating": 97, "team": "Royals", "rarity": "legendary" },
            { "name": "Eddie Mathews", "rating": 96, "team": "Braves", "rarity": "legendary" },
            { "name": "Chipper Jones", "rating": 95, "team": "Braves", "rarity": "legendary" },
            { "name": "Adrian Beltre", "rating": 94, "team": "Rangers", "rarity": "legendary" },
            { "name": "Jose Ramirez", "rating": 94, "team": "Guardians", "rarity": "legendary" },
            { "name": "Brooks Robinson", "rating": 93, "team": "Orioles", "rarity": "legendary" },
            { "name": "Ron Santo", "rating": 91, "team": "Cubs", "rarity": "legendary" },
            { "name": "Manny Machado", "rating": 90, "team": "Padres", "rarity": "legendary" },
            { "name": "Scott Rolen", "rating": 88, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Evan Longoria", "rating": 88, "team": "Rays", "rarity": "legendary" },
            { "name": "Rafael Devers", "rating": 87, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Matt Williams", "rating": 86, "team": "Giants", "rarity": "legendary" },
            { "name": "Eric Chavez", "rating": 85, "team": "Athletics", "rarity": "legendary" },
            { "name": "Aramis Ramirez", "rating": 84, "team": "Cubs", "rarity": "legendary" },
            { "name": "Troy Glaus", "rating": 84, "team": "Angels", "rarity": "legendary" },
            { "name": "Matt Chapman", "rating": 82, "team": "Blue Jays", "rarity": "legendary" },
            { "name": "Nolan Arenado", "rating": 82, "team": "Cardinals", "rarity": "legendary" },
            { "name": "David Wright", "rating": 81, "team": "Mets", "rarity": "legendary" },
            { "name": "Vinny Castilla", "rating": 80, "team": "Rockies", "rarity": "legendary" },
            { "name": "Graig Nettles", "rating": 79, "team": "Yankees", "rarity": "legendary" },
            { "name": "Ken Boyer", "rating": 78, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Buddy Bell", "rating": 77, "team": "Rangers", "rarity": "legendary" },
            { "name": "Travis Fryman", "rating": 76, "team": "Tigers", "rarity": "legendary" },
            { "name": "Doug DeCinces", "rating": 76, "team": "Orioles", "rarity": "legendary" }
              
        ],
        "common": [
            { "name": "Alex Bregman", "rating": 75, "team": "Astros", "rarity": "common" },
            { "name": "Austin Riley", "rating": 73, "team": "Braves", "rarity": "common" },
            { "name": "Matt Carpenter", "rating": 72, "team": "Cardinals", "rarity": "common" },
            { "name": "Anthony Rendon", "rating": 71, "team": "Angels", "rarity": "common" },
            { "name": "Ke'Bryan Hayes", "rating": 70, "team": "Pirates", "rarity": "common" },
            { "name": "Eugenio Suarez", "rating": 68, "team": "Mariners", "rarity": "common" },
            { "name": "Josh Donaldson", "rating": 67, "team": "Yankees", "rarity": "common" },
            { "name": "Yoan Moncada", "rating": 66, "team": "White Sox", "rarity": "common" },
            { "name": "Jeimer Candelario", "rating": 65, "team": "Nationals", "rarity": "common" },
            { "name": "Maikel Franco", "rating": 64, "team": "Nationals", "rarity": "common" },
            { "name": "Miguel Sano", "rating": 63, "team": "Twins", "rarity": "common" },
            { "name": "Kyle Seager", "rating": 62, "team": "Mariners", "rarity": "common" },
            { "name": "Patrick Wisdom", "rating": 61, "team": "Cubs", "rarity": "common" },
            { "name": "J.D. Davis", "rating": 60, "team": "Giants", "rarity": "common" },
            { "name": "Bobby Witt Jr.", "rating": 59, "team": "Royals", "rarity": "common" },
            { "name": "Giovanny Urshela", "rating": 58, "team": "Angels", "rarity": "common" },
            { "name": "Jonathan Villar", "rating": 57, "team": "Cubs", "rarity": "common" },
            { "name": "Luis Urias", "rating": 56, "team": "Red Sox", "rarity": "common" },
            { "name": "Josh Rojas", "rating": 55, "team": "Mariners", "rarity": "common" },
            { "name": "Joey Wendle", "rating": 54, "team": "Marlins", "rarity": "common" },
            { "name": "Eduardo Escobar", "rating": 53, "team": "Mets", "rarity": "common" },
            { "name": "Yandy Diaz", "rating": 52, "team": "Rays", "rarity": "common" },
            { "name": "Gio Urshela", "rating": 51, "team": "Angels", "rarity": "common" },
            { "name": "Matt Duffy", "rating": 50, "team": "Cubs", "rarity": "common" }
               
        ]
    },
    "SS": {
        "legendary": [
            { "name": "Honus Wagner", "rating": 99, "team": "Pirates", "rarity": "legendary" },
            { "name": "Cal Ripken Jr.", "rating": 98, "team": "Orioles", "rarity": "legendary" },
            { "name": "Derek Jeter", "rating": 98, "team": "Yankees", "rarity": "legendary" },
            { "name": "Alex Rodriguez", "rating": 97, "team": "Mariners", "rarity": "legendary" },
            { "name": "Arky Vaughan", "rating": 96, "team": "Pirates", "rarity": "legendary" },
            { "name": "Robin Yount", "rating": 95, "team": "Brewers", "rarity": "legendary" },
            { "name": "Ozzie Smith", "rating": 94, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Ernie Banks", "rating": 92, "team": "Cubs", "rarity": "legendary" },
            { "name": "Barry Larkin", "rating": 91, "team": "Reds", "rarity": "legendary" },
            { "name": "Alan Trammell", "rating": 90, "team": "Tigers", "rarity": "legendary" },
            { "name": "Francisco Lindor", "rating": 89, "team": "Mets", "rarity": "legendary" },
            { "name": "Trea Turner", "rating": 88, "team": "Phillies", "rarity": "legendary" },
            { "name": "Corey Seager", "rating": 87, "team": "Rangers", "rarity": "legendary" },
            { "name": "Xander Bogaerts", "rating": 86, "team": "Padres", "rarity": "legendary" },
            { "name": "Jimmy Rollins", "rating": 85, "team": "Phillies", "rarity": "legendary" },
            { "name": "Troy Tulowitzki", "rating": 84, "team": "Rockies", "rarity": "legendary" },
            { "name": "Omar Vizquel", "rating": 83, "team": "Indians", "rarity": "legendary" },
            { "name": "Jose Reyes", "rating": 82, "team": "Mets", "rarity": "legendary" },
            { "name": "Miguel Tejada", "rating": 81, "team": "Athletics", "rarity": "legendary" },
            { "name": "Luke Appling", "rating": 80, "team": "White Sox", "rarity": "legendary" },
            { "name": "Joe Cronin", "rating": 79, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Pee Wee Reese", "rating": 78, "team": "Dodgers", "rarity": "legendary" },
            { "name": "Bobby Wallace", "rating": 77, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Dave Concepcion", "rating": 76, "team": "Reds", "rarity": "legendary" },
            { "name": "Travis Jackson", "rating": 75, "team": "Giants","rarity": "legendary" }
        ],
        "common": [
            { "name": "Bo Bichette", "rating": 74, "team": "Blue Jays", "rarity": "common" },
            { "name": "Dansby Swanson", "rating": 73, "team": "Cubs", "rarity": "common" },
            { "name": "Carlos Correa", "rating": 72, "team": "Twins", "rarity": "common" },
            { "name": "Tim Anderson", "rating": 71, "team": "White Sox", "rarity": "common" },
            { "name": "Willy Adames", "rating": 70, "team": "Brewers", "rarity": "common" },
            { "name": "Javier Baez", "rating": 69, "team": "Tigers", "rarity": "common" },
            { "name": "Marcus Semien", "rating": 68, "team": "Rangers", "rarity": "common" },
            { "name": "JP Crawford", "rating": 67, "team": "Mariners", "rarity": "common" },
            { "name": "Amed Rosario", "rating": 66, "team": "Guardians", "rarity": "common" },
            { "name": "Ha-Seong Kim", "rating": 65, "team": "Padres", "rarity": "common" },
            { "name": "Jeremy Pena", "rating": 64, "team": "Astros", "rarity": "common" },
            { "name": "Didi Gregorius", "rating": 63, "team": "Phillies", "rarity": "common" },
            { "name": "Brandon Crawford", "rating": 62, "team": "Giants", "rarity": "common" },
            { "name": "Andrelton Simmons", "rating": 61, "team": "Cubs", "rarity": "common" },
            { "name": "Paul DeJong", "rating": 60, "team": "Cardinals", "rarity": "common" },
            { "name": "Adalberto Mondesi", "rating": 59, "team": "Royals", "rarity": "common" },
            { "name": "Elvis Andrus", "rating": 58, "team": "White Sox", "rarity": "common" },
            { "name": "Nico Hoerner", "rating": 57, "team": "Cubs", "rarity": "common" },
            { "name": "Jorge Mateo", "rating": 56, "team": "Orioles", "rarity": "common" },
            { "name": "Oneil Cruz", "rating": 55, "team": "Pirates", "rarity": "common" },
            { "name": "Nick Ahmed", "rating": 54, "team": "Diamondbacks", "rarity": "common" },
            { "name": "Alcides Escobar", "rating": 53, "team": "Nationals", "rarity": "common" },
            { "name": "Jose Iglesias", "rating": 52, "team": "Red Sox", "rarity": "common" },
            { "name": "Kevin Newman", "rating": 51, "team": "Pirates", "rarity": "common" },
            { "name": "Freddy Galvis", "rating": 50, "team": "Phillies", "rarity": "common" }
        ]
    },
    "C": {
        "legendary": [
            { "name": "Johnny Bench", "rating": 99, "team": "Reds", "rarity": "legendary" },
            { "name": "Yogi Berra", "rating": 98, "team": "Yankees", "rarity": "legendary" },
            { "name": "Mike Piazza", "rating": 97, "team": "Dodgers", "rarity": "legendary" },
            { "name": "Ivan Rodriguez", "rating": 96, "team": "Rangers", "rarity": "legendary" },
            { "name": "Roy Campanella", "rating": 95, "team": "Dodgers", "rarity": "legendary" },
            { "name": "Gary Carter", "rating": 94, "team": "Expos", "rarity": "legendary" },
            { "name": "Carlton Fisk", "rating": 93, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Yadier Molina", "rating": 92, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Joe Mauer", "rating": 91, "team": "Twins", "rarity": "legendary" },
            { "name": "Buster Posey", "rating": 90, "team": "Giants", "rarity": "legendary" },
            { "name": "Jorge Posada", "rating": 89, "team": "Yankees", "rarity": "legendary" },
            { "name": "Ted Simmons", "rating": 88, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Bill Dickey", "rating": 87, "team": "Yankees", "rarity": "legendary" },
            { "name": "Mickey Cochrane", "rating": 86, "team": "Athletics", "rarity": "legendary" },
            { "name": "Thurman Munson", "rating": 85, "team": "Yankees", "rarity": "legendary" },
            { "name": "Gabby Hartnett", "rating": 84, "team": "Cubs", "rarity": "legendary" },
            { "name": "J.T. Realmuto", "rating": 83, "team": "Phillies", "rarity": "legendary" },
            { "name": "Salvador Perez", "rating": 82, "team": "Royals", "rarity": "legendary" },
            { "name": "Brian McCann", "rating": 81, "team": "Braves", "rarity": "legendary" },
            { "name": "Russell Martin", "rating": 80, "team": "Dodgers", "rarity": "legendary" },
            { "name": "Benito Santiago", "rating": 79, "team": "Padres", "rarity": "legendary" },
            { "name": "Lance Parrish", "rating": 78, "team": "Tigers", "rarity": "legendary" },
            { "name": "Gene Tenace", "rating": 77, "team": "Athletics", "rarity": "legendary" },
            { "name": "Bob Boone", "rating": 76, "team": "Phillies", "rarity": "legendary" },
            { "name": "Darren Daulton", "rating": 75, "team": "Phillies", "rarity": "legendary" }
        ],
        "common": [
            { "name": "Will Smith", "rating": 74, "team": "Dodgers", "rarity": "common" },
            { "name": "Adley Rutschman", "rating": 73, "team": "Orioles", "rarity": "common" },
            { "name": "Sean Murphy", "rating": 72, "team": "Braves", "rarity": "common" },
            { "name": "Alejandro Kirk", "rating": 71, "team": "Blue Jays", "rarity": "common" },
            { "name": "Willson Contreras", "rating": 70, "team": "Cardinals", "rarity": "common" },
            { "name": "Cal Raleigh", "rating": 69, "team": "Mariners", "rarity": "common" },
            { "name": "Tyler Stephenson", "rating": 68, "team": "Reds", "rarity": "common" },
            { "name": "MJ Melendez", "rating": 67, "team": "Royals", "rarity": "common" },
            { "name": "Jonah Heim", "rating": 66, "team": "Rangers", "rarity": "common" },
            { "name": "Christian Vazquez", "rating": 65, "team": "Twins", "rarity": "common" },
            { "name": "Yasmani Grandal", "rating": 64, "team": "White Sox", "rarity": "common" },
            { "name": "Wilson Ramos", "rating": 63, "team": "Tigers", "rarity": "common" },
            { "name": "Travis d'Arnaud", "rating": 62, "team": "Braves", "rarity": "common" },
            { "name": "Omar Narvaez", "rating": 61, "team": "Mets", "rarity": "common" },
            { "name": "James McCann", "rating": 60, "team": "Orioles", "rarity": "common" },
            { "name": "Danny Jansen", "rating": 59, "team": "Blue Jays", "rarity": "common" },
            { "name": "Jacob Stallings", "rating": 58, "team": "Marlins", "rarity": "common" },
            { "name": "Elias Diaz", "rating": 57, "team": "Rockies", "rarity": "common" },
            { "name": "Connor Wong", "rating": 56, "team": "Red Sox", "rarity": "common" },
            { "name": "Austin Nola", "rating": 55, "team": "Padres", "rarity": "common" },
            { "name": "Yan Gomes", "rating": 54, "team": "Cubs", "rarity": "common" },
            { "name": "Kurt Suzuki", "rating": 53, "team": "Angels", "rarity": "common" },
            { "name": "Tucker Barnhart", "rating": 52, "team": "Tigers", "rarity": "common" },
            { "name": "Robinson Chirinos", "rating": 51, "team": "Orioles", "rarity": "common" },
            { "name": "Mitch Garver", "rating": 50, "team": "Rangers", "rarity": "common" }
        ]
    },
    "LF": {
        "legendary": [
            { "name": "Ted Williams", "rating": 99, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Barry Bonds", "rating": 98, "team": "Giants", "rarity": "legendary" },
            { "name": "Rickey Henderson", "rating": 97, "team": "Athletics", "rarity": "legendary" },
            { "name": "Stan Musial", "rating": 96, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Carl Yastrzemski", "rating": 95, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Manny Ramirez", "rating": 94, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Tim Raines", "rating": 93, "team": "Expos", "rarity": "legendary" },
            { "name": "Jim Rice", "rating": 92, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Ralph Kiner", "rating": 91, "team": "Pirates", "rarity": "legendary" },
            { "name": "Juan Soto", "rating": 90, "team": "Padres", "rarity": "legendary" },
            { "name": "Christian Yelich", "rating": 89, "team": "Brewers", "rarity": "legendary" },
            { "name": "Lou Brock", "rating": 88, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Goose Goslin", "rating": 87, "team": "Senators", "rarity": "legendary" },
            { "name": "Joe Medwick", "rating": 86, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Billy Williams", "rating": 85, "team": "Cubs", "rarity": "legendary" },
            { "name": "Zack Wheat", "rating": 84, "team": "Dodgers", "rarity": "legendary" },
            { "name": "Ed Delahanty", "rating": 83, "team": "Phillies", "rarity": "legendary" },
            { "name": "Ryan Braun", "rating": 82, "team": "Brewers", "rarity": "legendary" },
            { "name": "Matt Holliday", "rating": 81, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Carlos Lee", "rating": 80, "team": "Astros", "rarity": "legendary" },
            { "name": "Jesse Burkett", "rating": 79, "team": "Indians", "rarity": "legendary" },
            { "name": "Fred Clarke", "rating": 78, "team": "Pirates", "rarity": "legendary" },
            { "name": "Sherry Magee", "rating": 77, "team": "Phillies", "rarity": "legendary" },
            { "name": "Bob Johnson", "rating": 76, "team": "Athletics", "rarity": "legendary" },
            { "name": "Heinie Manush", "rating": 75, "team": "Senators", "rarity": "legendary" }
        ],
        "common": [
            { "name": "Randy Arozarena", "rating": 74, "team": "Rays", "rarity": "common" },
            { "name": "Kyle Schwarber", "rating": 73, "team": "Phillies", "rarity": "common" },
            { "name": "Ian Happ", "rating": 72, "team": "Cubs", "rarity": "common" },
            { "name": "Lourdes Gurriel Jr.", "rating": 71, "team": "Blue Jays", "rarity": "common" },
            { "name": "AJ Pollock", "rating": 70, "team": "White Sox", "rarity": "common" },
            { "name": "Corey Dickerson", "rating": 69, "team": "Cardinals", "rarity": "common" },
            { "name": "Eddie Rosario", "rating": 68, "team": "Braves", "rarity": "common" },
            { "name": "Alex Verdugo", "rating": 67, "team": "Red Sox", "rarity": "common" },
            { "name": "Andrew Benintendi", "rating": 66, "team": "White Sox", "rarity": "common" },
            { "name": "David Peralta", "rating": 65, "team": "Dodgers", "rarity": "common" },
            { "name": "Joc Pederson", "rating": 64, "team": "Giants", "rarity": "common" },
            { "name": "Jesse Winker", "rating": 63, "team": "Brewers", "rarity": "common" },
            { "name": "Tommy Pham", "rating": 62, "team": "Mets", "rarity": "common" },
            { "name": "Marcell Ozuna", "rating": 61, "team": "Braves", "rarity": "common" },
            { "name": "Austin Hays", "rating": 60, "team": "Orioles", "rarity": "common" },
            { "name": "Mark Canha", "rating": 59, "team": "Mets", "rarity": "common" },
            { "name": "Nomar Mazara", "rating": 58, "team": "Padres", "rarity": "common" },
            { "name": "Adam Duvall", "rating": 57, "team": "Red Sox", "rarity": "common" },
            { "name": "Michael Taylor", "rating": 56, "team": "Royals", "rarity": "common" },
            { "name": "Clint Frazier", "rating": 55, "team": "Cubs", "rarity": "common" },
            { "name": "Willie Calhoun", "rating": 54, "team": "Giants", "rarity": "common" },
            { "name": "Trent Grisham", "rating": 53, "team": "Padres", "rarity": "common" },
            { "name": "Daulton Varsho", "rating": 52, "team": "Blue Jays", "rarity": "common" },
            { "name": "Steven Kwan", "rating": 51, "team": "Guardians", "rarity": "common" },
            { "name": "Lars Nootbaar", "rating": 50, "team": "Cardinals", "rarity": "common" }
        ]
    },
    "CF": {
        "legendary": [
            { "name": "Willie Mays", "rating": 99, "team": "Giants", "rarity": "legendary" },
            { "name": "Ty Cobb", "rating": 98, "team": "Tigers", "rarity": "legendary" },
            { "name": "Tris Speaker", "rating": 97, "team": "Indians", "rarity": "legendary" },
            { "name": "Mickey Mantle", "rating": 96, "team": "Yankees", "rarity": "legendary" },
            { "name": "Ken Griffey Jr.", "rating": 95, "team": "Mariners", "rarity": "legendary" },
            { "name": "Mike Trout", "rating": 94, "team": "Angels", "rarity": "legendary" },
            { "name": "Duke Snider", "rating": 93, "team": "Dodgers", "rarity": "legendary" },
            { "name": "Joe DiMaggio", "rating": 92, "team": "Yankees", "rarity": "legendary" },
            { "name": "Oscar Charleston", "rating": 91, "team": "Negro Leagues", "rarity": "legendary" },
            { "name": "Andruw Jones", "rating": 90, "team": "Braves", "rarity": "legendary" },
            { "name": "Larry Doby", "rating": 89, "team": "Indians", "rarity": "legendary" },
            { "name": "Carlos Beltran", "rating": 88, "team": "Mets", "rarity": "legendary" },
            { "name": "Bernie Williams", "rating": 87, "team": "Yankees", "rarity": "legendary" },
            { "name": "Jim Edmonds", "rating": 86, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Torii Hunter", "rating": 85, "team": "Twins", "rarity": "legendary" },
            { "name": "Byron Buxton", "rating": 84, "team": "Twins", "rarity": "legendary" },
            { "name": "George Springer", "rating": 83, "team": "Astros", "rarity": "legendary" },
            { "name": "Andrew McCutchen", "rating": 82, "team": "Pirates", "rarity": "legendary" },
            { "name": "Cody Bellinger", "rating": 81, "team": "Cubs", "rarity": "legendary" },
            { "name": "Curtis Granderson", "rating": 80, "team": "Tigers", "rarity": "legendary" },
            { "name": "Dale Murphy", "rating": 79, "team": "Braves", "rarity": "legendary" },
            { "name": "Brett Butler", "rating": 78, "team": "Giants", "rarity": "legendary" },
            { "name": "Fred Lynn", "rating": 77, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Kirby Puckett", "rating": 76, "team": "Twins", "rarity": "legendary" },
            { "name": "Jim Wynn", "rating": 75, "team": "Astros", "rarity": "legendary" }
        ],
        "common": [
            { "name": "Luis Robert Jr.", "rating": 74, "team": "White Sox", "rarity": "common" },
            { "name": "Julio Rodriguez", "rating": 73, "team": "Mariners", "rarity": "common" },
            { "name": "Cedric Mullins", "rating": 72, "team": "Orioles", "rarity": "common" },
            { "name": "Brandon Nimmo", "rating": 71, "team": "Mets", "rarity": "common" },
            { "name": "Harrison Bader", "rating": 70, "team": "Yankees", "rarity": "common" },
            { "name": "Michael A. Taylor", "rating": 69, "team": "Royals", "rarity": "common" },
            { "name": "Kevin Kiermaier", "rating": 68, "team": "Blue Jays", "rarity": "common" },
            { "name": "Alek Thomas", "rating": 67, "team": "Diamondbacks", "rarity": "common" },
            { "name": "TJ Friedl", "rating": 66, "team": "Reds", "rarity": "common" },
            { "name": "Jake Meyers", "rating": 65, "team": "Astros", "rarity": "common" },
            { "name": "Esteury Ruiz", "rating": 64, "team": "Athletics", "rarity": "common" },
            { "name": "Dylan Carlson", "rating": 63, "team": "Cardinals", "rarity": "common" },
            { "name": "Victor Robles", "rating": 62, "team": "Nationals", "rarity": "common" },
            { "name": "Magneuris Sierra", "rating": 61, "team": "Marlins", "rarity": "common" },
            { "name": "Roman Quinn", "rating": 60, "team": "Phillies", "rarity": "common" },
            { "name": "Jackie Bradley Jr.", "rating": 59, "team": "Blue Jays", "rarity": "common" },
            { "name": "Lorenzo Cain", "rating": 58, "team": "Brewers", "rarity": "common" },
            { "name": "Billy Hamilton", "rating": 57, "team": "Reds", "rarity": "common" },
            { "name": "Adam Engel", "rating": 56, "team": "White Sox", "rarity": "common" },
            { "name": "Jon Berti", "rating": 55, "team": "Marlins", "rarity": "common" },
            { "name": "Odubel Herrera", "rating": 54, "team": "Phillies", "rarity": "common" },
            { "name": "Ramon Laureano", "rating": 53, "team": "Athletics", "rarity": "common" },
            { "name": "Jose Siri", "rating": 52, "team": "Rays", "rarity": "common" },
            { "name": "Jake Marisnick", "rating": 51, "team": "Cubs", "rarity": "common" },
            { "name": "Derek Hill", "rating": 50, "team": "Nationals", "rarity": "common" }
        ]
    },
    "RF": {
        "legendary": [
            { "name": "Babe Ruth", "rating": 99, "team": "Yankees", "rarity": "legendary" },
            { "name": "Hank Aaron", "rating": 98, "team": "Braves", "rarity": "legendary" },
            { "name": "Frank Robinson", "rating": 97, "team": "Reds", "rarity": "legendary" },
            { "name": "Roberto Clemente", "rating": 96, "team": "Pirates", "rarity": "legendary" },
            { "name": "Reggie Jackson", "rating": 95, "team": "Athletics", "rarity": "legendary" },
            { "name": "Al Kaline", "rating": 94, "team": "Tigers", "rarity": "legendary" },
            { "name": "Tony Gwynn", "rating": 93, "team": "Padres", "rarity": "legendary" },
            { "name": "Mookie Betts", "rating": 92, "team": "Dodgers", "rarity": "legendary" },
            { "name": "Vladimir Guerrero", "rating": 91, "team": "Expos", "rarity": "legendary" },
            { "name": "Aaron Judge", "rating": 90, "team": "Yankees", "rarity": "legendary" },
            { "name": "Ichiro Suzuki", "rating": 89, "team": "Mariners", "rarity": "legendary" },
            { "name": "Dave Winfield", "rating": 88, "team": "Padres", "rarity": "legendary" },
            { "name": "Larry Walker", "rating": 87, "team": "Rockies", "rarity": "legendary" },
            { "name": "Dwight Evans", "rating": 86, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Paul Waner", "rating": 85, "team": "Pirates", "rarity": "legendary" },
            { "name": "Giancarlo Stanton", "rating": 84, "team": "Marlins", "rarity": "legendary" },
            { "name": "Jason Heyward", "rating": 83, "team": "Cubs", "rarity": "legendary" },
            { "name": "J.D. Martinez", "rating": 82, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Bryce Harper", "rating": 81, "team": "Phillies", "rarity": "legendary" },
            { "name": "Jayson Werth", "rating": 80, "team": "Nationals", "rarity": "legendary" },
            { "name": "Bobby Abreu", "rating": 79, "team": "Phillies", "rarity": "legendary" },
            { "name": "Harry Heilmann", "rating": 78, "team": "Tigers", "rarity": "legendary" },
            { "name": "Sam Crawford", "rating": 77, "team": "Tigers", "rarity": "legendary" },
            { "name": "Elmer Flick", "rating": 76, "team": "Indians", "rarity": "legendary" },
            {"name": "Kiki Cuyler", "rating": 75, "team": "Cubs", "rarity": "legendary" }
        ],
        "common": [
            { "name": "Kyle Tucker", "rating": 74, "team": "Astros", "rarity": "common" },
            { "name": "Ronald Acuna Jr.", "rating": 73, "team": "Braves", "rarity": "common" },
            { "name": "Fernando Tatis Jr.", "rating": 72, "team": "Padres", "rarity": "common" },
            { "name": "Seiya Suzuki", "rating": 71, "team": "Cubs", "rarity": "common" },
            { "name": "Adolis Garcia", "rating": 70, "team": "Rangers", "rarity": "common" },
            { "name": "Hunter Renfroe", "rating": 69, "team": "Angels", "rarity": "common" },
            { "name": "Teoscar Hernandez", "rating": 68, "team": "Blue Jays", "rarity": "common" },
            { "name": "Max Kepler", "rating": 67, "team": "Twins", "rarity": "common" },
            { "name": "Nick Castellanos", "rating": 66, "team": "Phillies", "rarity": "common" },
            { "name": "Mitch Haniger", "rating": 65, "team": "Giants", "rarity": "common" },
            { "name": "Jorge Soler", "rating": 64, "team": "Marlins", "rarity": "common" },
            { "name": "Randal Grichuk", "rating": 63, "team": "Rockies", "rarity": "common" },
            { "name": "Adam Frazier", "rating": 62, "team": "Orioles", "rarity": "common" },
            { "name": "Kole Calhoun", "rating": 61, "team": "Rangers", "rarity": "common" },
            { "name": "Gregory Polanco", "rating": 60, "team": "Pirates", "rarity": "common" },
            { "name": "Jason Heyward", "rating": 59, "team": "Dodgers", "rarity": "common" },
            { "name": "Charlie Blackmon", "rating": 58, "team": "Rockies", "rarity": "common" },
            { "name": "Stephen Piscotty", "rating": 57, "team": "Athletics", "rarity": "common" },
            { "name": "Hunter Dozier", "rating": 56, "team": "Royals", "rarity": "common" },
            { "name": "Brett Phillips", "rating": 55, "team": "Rays", "rarity": "common" },
            { "name": "Cody Bellinger", "rating": 54, "team": "Cubs", "rarity": "common" },
            { "name": "Clint Frazier", "rating": 53, "team": "Cubs", "rarity": "common" },
            { "name": "Jay Bruce", "rating": 51, "team": "Mets", "rarity": "common" },
        ]
    },
    "DH": {
        "legendary": [
            { "name": "David Ortiz", "rating": 99, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Edgar Martinez", "rating": 98, "team": "Mariners", "rarity": "legendary" },
            { "name": "Frank Thomas", "rating": 97, "team": "White Sox", "rarity": "legendary" },
            { "name": "Shohei Ohtani", "rating": 96, "team": "Dodgers", "rarity": "legendary" },
            { "name": "Jim Rice", "rating": 95, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Harold Baines", "rating": 94, "team": "White Sox", "rarity": "legendary" },
            { "name": "Paul Molitor", "rating": 93, "team": "Brewers", "rarity": "legendary" },
            { "name": "Don Baylor", "rating": 92, "team": "Angels", "rarity": "legendary" },
            { "name": "Nelson Cruz", "rating": 91, "team": "Mariners", "rarity": "legendary" },
            { "name": "Yordan Alvarez", "rating": 90, "team": "Astros", "rarity": "legendary" },
            { "name": "J.D. Martinez", "rating": 89, "team": "Red Sox", "rarity": "legendary" },
            { "name": "Hideki Matsui", "rating": 88, "team": "Yankees", "rarity": "legendary" },
            { "name": "Travis Hafner", "rating": 87, "team": "Indians", "rarity": "legendary" },
            { "name": "Chili Davis", "rating": 86, "team": "Twins", "rarity": "legendary" },
            { "name": "Hal McRae", "rating": 85, "team": "Royals", "rarity": "legendary" },
            { "name": "Cliff Johnson", "rating": 84, "team": "Yankees", "rarity": "legendary" },
            { "name": "Ken Phelps", "rating": 83, "team": "Mariners", "rarity": "legendary" },
            { "name": "Rico Brogna", "rating": 82, "team": "Phillies", "rarity": "legendary" },
            { "name": "Jack Clark", "rating": 81, "team": "Cardinals", "rarity": "legendary" },
            { "name": "Tommy Davis", "rating": 80, "team": "Dodgers", "rarity": "legendary" },
            { "name": "Willie Horton", "rating": 79, "team": "Tigers", "rarity": "legendary" },
            { "name": "Roy White", "rating": 78, "team": "Yankees", "rarity": "legendary" },
            { "name": "Rusty Staub", "rating": 77, "team": "Expos", "rarity": "legendary" },
            { "name": "Greg Luzinski", "rating": 76, "team": "Phillies", "rarity": "legendary" },
            { "name": "Dave Kingman", "rating": 75, "team": "Mets", "rarity": "legendary" }
        ],
        "common": [
            { "name": "Kyle Schwarber", "rating": 73, "team": "Phillies", "rarity": "common" },
            { "name": "Marcell Ozuna", "rating": 72, "team": "Braves", "rarity": "common" },
            { "name": "Justin Turner", "rating": 71, "team": "Red Sox", "rarity": "common" },
            { "name": "Andrew McCutchen", "rating": 70, "team": "Pirates", "rarity": "common" },
            { "name": "Mitch Garver", "rating": 69, "team": "Rangers", "rarity": "common" },
            { "name": "Franmil Reyes", "rating": 68, "team": "Cubs", "rarity": "common" },
            { "name": "Jose Abreu", "rating": 67, "team": "Astros", "rarity": "common" },
            { "name": "Brandon Belt", "rating": 66, "team": "Blue Jays", "rarity": "common" },
            { "name": "Khris Davis", "rating": 65, "team": "Athletics", "rarity": "common" },
            { "name": "Daniel Vogelbach", "rating": 64, "team": "Mets", "rarity": "common" },
            { "name": "Rowdy Tellez", "rating": 63, "team": "Brewers", "rarity": "common" },
            { "name": "Hunter Dozier", "rating": 62, "team": "Royals", "rarity": "common" },
            { "name": "Evan Longoria", "rating": 61, "team": "Giants", "rarity": "common" },
            { "name": "Ryan Zimmerman", "rating": 60, "team": "Nationals", "rarity": "common" },
            { "name": "Corey Dickerson", "rating": 59, "team": "Cardinals", "rarity": "common" },
            { "name": "Albert Pujols", "rating": 58, "team": "Angels", "rarity": "common" },
            { "name": "Miguel Sano", "rating": 57, "team": "Twins", "rarity": "common" },
            { "name": "Joc Pederson", "rating": 56, "team": "Giants", "rarity": "common" },
            { "name": "Adam Duvall", "rating": 55, "team": "Red Sox", "rarity": "common" },
            { "name": "Ryon Healy", "rating": 54, "team": "Mariners", "rarity": "common" },
            { "name": "Kendrys Morales", "rating": 53, "team": "Blue Jays", "rarity": "common" },
            { "name": "Edwin Encarnacion", "rating": 52, "team": "Blue Jays", "rarity": "common" },
            { "name": "C.J. Cron", "rating": 51, "team": "Rockies", "rarity": "common" },
            { "name": "Mark Trumbo", "rating": 50, "team": "Orioles", "rarity": "common" }
        ]
    }
};

