// Team Logos Database
// Contains logo URLs for MLB teams

const teamLogos = {
    "Angels": "https://www.mlbstatic.com/team-logos/108.svg",
    "Athletics": "https://www.mlbstatic.com/team-logos/133.svg",
    "Astros": "https://www.mlbstatic.com/team-logos/117.svg",
    "Blue Jays": "https://www.mlbstatic.com/team-logos/141.svg",
    "Braves": "https://www.mlbstatic.com/team-logos/144.svg",
    "Brewers": "https://www.mlbstatic.com/team-logos/158.svg",
    "Cardinals": "https://www.mlbstatic.com/team-logos/138.svg",
    "Cubs": "https://www.mlbstatic.com/team-logos/112.svg",
    "Diamondbacks": "https://www.mlbstatic.com/team-logos/109.svg",
    "Dodgers": "https://www.mlbstatic.com/team-logos/119.svg",
    "Expos": "https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Montreal_Expos_Logo.svg/200px-Montreal_Expos_Logo.svg.png",
    "Giants": "https://www.mlbstatic.com/team-logos/137.svg",
    "Guardians": "https://www.mlbstatic.com/team-logos/114.svg",
    "Indians": "https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/Chief_Wahoo_%28mascot_character%29.svg/960px-Chief_Wahoo_%28mascot_character%29.svg.png",
    "Mariners": "https://www.mlbstatic.com/team-logos/136.svg",
    "Marlins": "https://www.mlbstatic.com/team-logos/146.svg",
    "Mets": "https://www.mlbstatic.com/team-logos/121.svg",
    "Nationals": "https://www.mlbstatic.com/team-logos/120.svg",
    "Negro Leagues": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e6/Negro_Leagues_Baseball_Museum_logo.svg/1280px-Negro_Leagues_Baseball_Museum_logo.svg.png",
    "Orioles": "https://www.mlbstatic.com/team-logos/110.svg",
    "Padres": "https://www.mlbstatic.com/team-logos/135.svg",
    "Phillies": "https://www.mlbstatic.com/team-logos/143.svg",
    "Pirates": "https://www.mlbstatic.com/team-logos/134.svg",
    "Rangers": "https://www.mlbstatic.com/team-logos/140.svg",
    "Rays": "https://www.mlbstatic.com/team-logos/139.svg",
    "Red Sox": "https://www.mlbstatic.com/team-logos/111.svg",
    "Reds": "https://www.mlbstatic.com/team-logos/113.svg",
    "Rockies": "https://www.mlbstatic.com/team-logos/115.svg",
    "Royals": "https://www.mlbstatic.com/team-logos/118.svg",
    "Senators": "https://upload.wikimedia.org/wikipedia/en/5/5a/Washington_Senators_%281961%E2%80%931971%29_Team_Logo.png",
    "Spiders": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Cleveland_Spiders_1889_logo.svg/200px-Cleveland_Spiders_1889_logo.svg.png",
    "Tigers": "https://www.mlbstatic.com/team-logos/116.svg",
    "Twins": "https://www.mlbstatic.com/team-logos/142.svg",
    "White Sox": "https://www.mlbstatic.com/team-logos/145.svg",
    "Yankees": "https://www.mlbstatic.com/team-logos/147.svg"
};