// Trivia Questions Database - Organized by Position
// Each position has challenging, position-specific questions with randomized answer order
// All players listed actually played the position mentioned

const triviaQuestions = {
    "1B": [
        { question: "Which first baseman holds the record for most consecutive games played by any first baseman?", answers: ["Lou Gehrig", "Steve Garvey", "Miguel Tejada", "Jimmie Foxx"], correct: 0 },
        { question: "Who was the first first baseman to win the AL batting title?", answers: ["George Sisler", "Bill Terry", "Lou Gehrig", "Jimmie Foxx"], correct: 0 },
        { question: "Which first baseman won the Triple Crown in 2012?", answers: ["Miguel Cabrera", "Albert Pujols", "Joey Votto", "Paul Goldschmidt"], correct: 0 },
        { question: "Who holds the record for most grand slams by a first baseman?", answers: ["Alex Rodriguez", "Lou Gehrig", "Eddie Murray", "Jimmie Foxx"], correct: 0 },
        { question: "Which first baseman was known as 'The Iron Horse'?", answers: ["Lou Gehrig", "Jimmie Foxx", "Frank Thomas", "Albert Pujols"], correct: 0 },
        { question: "Who was the first first baseman to hit 500 home runs?", answers: ["Eddie Murray", "Rafael Palmeiro", "Mark McGwire", "Frank Thomas"], correct: 0 },
        { question: "Which first baseman won three MVP awards with the Cardinals?", answers: ["Albert Pujols", "Stan Musial", "Mark McGwire", "Jim Bottomley"], correct: 0 },
        { question: "Who hit 58 home runs in 1938, a record for left-handed batters at the time?", answers: ["Hank Greenberg", "Lou Gehrig", "Jimmie Foxx", "Babe Ruth"], correct: 0 },
        { question: "Which first baseman batted .420 in 1922?", answers: ["George Sisler", "Bill Terry", "Lou Gehrig", "Jimmie Foxx"], correct: 0 },
        { question: "Who was the first player to hit 500 home runs and have 3,000 hits?", answers: ["Eddie Murray", "Willie Mays", "Hank Aaron", "Rafael Palmeiro"], correct: 0 },
        { question: "Which first baseman was nicknamed 'The Big Hurt'?", answers: ["Frank Thomas", "Mark McGwire", "Jeff Bagwell", "Fred McGriff"], correct: 0 },
        { question: "Who won back-to-back MVP awards in 1932-1933?", answers: ["Jimmie Foxx", "Lou Gehrig", "Hank Greenberg", "Bill Terry"], correct: 0 },
        { question: "Which first baseman hit 62 home runs in 2022?", answers: ["Aaron Judge", "Pete Alonso", "Vladimir Guerrero Jr.", "Matt Olson"], correct: 0 },
        { question: "Who was the 1994 NL MVP despite the strike-shortened season?", answers: ["Jeff Bagwell", "Fred McGriff", "Frank Thomas", "Matt Williams"], correct: 0 },
        { question: "Which first baseman had 2,130 consecutive games played?", answers: ["Lou Gehrig", "Cal Ripken Jr.", "Steve Garvey", "Miguel Tejada"], correct: 0 },
        { question: "Who hit 73 doubles in 1931?", answers: ["Earl Webb", "George Burns", "Lou Gehrig", "Hank Greenberg"], correct: 0 },
        { question: "Which first baseman won the 2005 NL MVP?", answers: ["Albert Pujols", "Derrek Lee", "Andruw Jones", "Andrés Galarraga"], correct: 0 },
        { question: "Who was the first first baseman to win a Gold Glove?", answers: ["Gil Hodges", "Vic Power", "Keith Hernandez", "Wes Parker"], correct: 0 },
        { question: "Which first baseman won 11 Gold Gloves?", answers: ["Keith Hernandez", "Don Mattingly", "Wes Parker", "Bill White"], correct: 0 },
        { question: "Who hit .424 for the Cardinals in 1924?", answers: ["Rogers Hornsby", "Jim Bottomley", "Sunny Jim", "George Sisler"], correct: 0 },
        { question: "Which first baseman was the 1991 AL MVP?", answers: ["Cal Ripken Jr.", "Cecil Fielder", "Frank Thomas", "Rafael Palmeiro"], correct: 0 },
        { question: "Who was the first first baseman to hit 40 home runs in a season?", answers: ["Jimmie Foxx", "Lou Gehrig", "Hank Greenberg", "Babe Ruth"], correct: 0 },
        { question: "Which first baseman won the 1964 AL MVP?", answers: ["Brooks Robinson", "Boog Powell", "Ron Hansen", "Frank Robinson"], correct: 0 },
        { question: "Who was the first baseman for the 1986 Mets World Series champions?", answers: ["Keith Hernandez", "Gary Carter", "Darryl Strawberry", "Howard Johnson"], correct: 0 },
        { question: "Which first baseman hit .349 in 1925?", answers: ["Rogers Hornsby", "George Sisler", "Bill Terry", "Jim Bottomley"], correct: 0 },
        { question: "Who won the 1981 AL MVP at first base?", answers: ["Eddie Murray", "Rickey Henderson", "Dwight Evans", "Carl Yastrzemski"], correct: 0 },
        { question: "Which first baseman was the 1978 NL MVP?", answers: ["Keith Hernandez", "Dave Parker", "Steve Garvey", "Pete Rose"], correct: 0 },
        { question: "Who was the first baseman for the 1975 Reds World Series champions?", answers: ["Tony Perez", "Johnny Bench", "Pete Rose", "Joe Morgan"], correct: 0 },
        { question: "Which first baseman won the 1990 NL MVP?", answers: ["Eddie Murray", "Ryne Sandberg", "Andre Dawson", "Howard Johnson"], correct: 0 },
        { question: "Who hit 44 home runs in 1998 as a first baseman?", answers: ["Mark McGwire", "Ken Griffey Jr.", "Sammy Sosa", "Rafael Palmeiro"], correct: 3 },
        { question: "Which first baseman was the 1983 NL MVP?", answers: ["Mike Schmidt", "Dale Murphy", "Phil Niekro", "Chipper Jones"], correct: 0 },
        { question: "Who was the first baseman for the 1993 Phillies World Series champions?", answers: ["John Kruk", "Lenny Dykstra", "Mitch Williams", "Curt Schilling"], correct: 0 },
        { question: "Which first baseman won the 1967 AL MVP?", answers: ["Carl Yastrzemski", "Frank Robinson", "Harmon Killebrew", "Tony Oliva"], correct: 0 },
        { question: "Who was the first baseman for the 2001 Diamondbacks World Series champions?", answers: ["Mark Grace", "Matt Williams", "Randy Johnson", "Curt Schilling"], correct: 0 },
        { question: "Which first baseman hit .363 in 1946?", answers: ["Stan Musial", "Enos Slaughter", "Red Schoendienst", "Terry Moore"], correct: 0 },
        { question: "Who won the 1971 AL MVP at first base?", answers: ["Vida Blue", "Reggie Jackson", "Joe Rudi", "Sal Bando"], correct: 0 },
        { question: "Which first baseman was the 1989 NL MVP?", answers: ["Kevin Mitchell", "Will Clark", "Andy Van Slyke", "Bobby Bonilla"], correct: 0 },
        { question: "Who was the first baseman for the 1988 Dodgers World Series champions?", answers: ["Franklin Stubbs", "Mike Scioscia", "Orel Hershiser", "Kirk Gibson"], correct: 0 },
        { question: "Which first baseman won the 1957 NL MVP?", answers: ["Hank Aaron", "Eddie Mathews", "Warren Spahn", "Red Schoendienst"], correct: 0 },
        { question: "Who was the first baseman for the 1973 Athletics World Series champions?", answers: ["Gene Tenace", "Sal Bando", "Reggie Jackson", "Joe Rudi"], correct: 0 },
        { question: "Which first baseman hit .359 in 1958?", answers: ["Ernie Banks", "Ron Hansen", "Eddie Kasko", "Tony Taylor"], correct: 0 },
        { question: "Who won the 1962 AL MVP at first base?", answers: ["Frank Malzone", "Dick Howser", "Ron Hansen", "Zoilo Versalles"], correct: 0 },
        { question: "Which first baseman was the 1995 NL MVP?", answers: ["Jeff Bagwell", "Craig Biggio", "Derek Bell", "Todd Hollandsworth"], correct: 0 },
        { question: "Who was the first baseman for the 1997 Marlins World Series champions?", answers: ["Jeff Conine", "Gary Sheffield", "Charles Johnson", "Craig Counsell"], correct: 0 },
        { question: "Which first baseman won the 1980 NL MVP?", answers: ["Keith Hernandez", "Pete Rose", "George Foster", "Johnny Bench"], correct: 0 },
        { question: "Who was the first baseman for the 2010 Giants World Series champions?", answers: ["Aubrey Huff", "Buster Posey", "Pablo Sandoval", "Madison Bumgarner"], correct: 0 },
        { question: "Which first baseman won the 1972 NL MVP?", answers: ["Johnny Bench", "Joe Morgan", "Tony Perez", "Pete Rose"], correct: 0 },
        { question: "Who was the first baseman for the 2009 Yankees World Series champions?", answers: ["Mark Teixeira", "Derek Jeter", "Alex Rodriguez", "Hideki Matsui"], correct: 0 },
        { question: "Which first baseman hit .370 in 1930?", answers: ["Bill Terry", "Chuck Klein", "Hack Wilson", "Lefty O'Doul"], correct: 0 },
        { question: "Who won the 1984 AL MVP at first base?", answers: ["Don Mattingly", "Dave Winfield", "Rickey Henderson", "Cal Ripken Jr."], correct: 0 },
        { question: "Which first baseman was the 1993 AL MVP?", answers: ["Frank Thomas", "Paul Molitor", "Rickey Henderson", "Roberto Alomar"], correct: 0 },
        { question: "Who was the first baseman for the 1987 Twins World Series champions?", answers: ["Kent Hrbek", "Tom Brunansky", "Gary Gaetti", "Frank Viola"], correct: 0 },
        { question: "Which first baseman won the 1969 AL MVP?", answers: ["Harmon Killebrew", "Tony Oliva", "Rod Carew", "Leo Cardenas"], correct: 0 },
        { question: "Who was the first baseman for the 1998 Padres World Series champions?", answers: ["Wally Joyner", "Tony Gwynn", "Greg Vaughn", "Trevor Hoffman"], correct: 0 },
        { question: "Which first baseman hit .373 in 1923?", answers: ["Heinie Groh", "Pie Traynor", "Stan Hack", "Eddie Mathews"], correct: 0 },
        { question: "Who won the 1977 AL MVP at first base?", answers: ["Jim Rice", "Fred Lynn", "Carl Yastrzemski", "Dwight Evans"], correct: 0 },
        { question: "Which first baseman won the 1985 NL MVP?", answers: ["Will Clark", "Ryne Sandberg", "Rick Sutcliffe", "Dave Parker"], correct: 0 }
    ],
    "2B": [
        { question: "Who holds the all-time hits record with 4,256?", answers: ["Pete Rose", "Ty Cobb", "Hank Aaron", "Stan Musial"], correct: 0 },
        { question: "Which second baseman won 10 Gold Glove Awards?", answers: ["Roberto Alomar", "Joe Morgan", "Ryne Sandberg", "Craig Biggio"], correct: 0 },
        { question: "Which second baseman was a key member of the Big Red Machine?", answers: ["Joe Morgan", "Pete Rose", "Ryne Sandberg", "Roberto Alomar"], correct: 0 },
        { question: "Which second baseman won the Triple Crown in 1901?", answers: ["Nap Lajoie", "Rogers Hornsby", "Eddie Collins", "Charlie Gehringer"], correct: 0 },
        { question: "Which second baseman batted .388 in 1911?", answers: ["Ty Cobb", "Nap Lajoie", "Eddie Collins", "Rogers Hornsby"], correct: 0 },
        { question: "Who was nicknamed 'Poosh 'Em Up Tony'?", answers: ["Tony Lazzeri", "Tony Perez", "Ryne Sandberg", "Craig Biggio"], correct: 0 },
        { question: "Which second baseman won seven batting titles in the 1970s?", answers: ["Rod Carew", "Pete Rose", "Joe Morgan", "Bill Madlock"], correct: 0 },
        { question: "Who was known as 'The Mechanical Man'?", answers: ["Charlie Gehringer", "Rogers Hornsby", "Eddie Collins", "Frankie Frisch"], correct: 0 },
        { question: "Which second baseman collected 3,000 hits entirely with the Astros?", answers: ["Craig Biggio", "Jeff Kent", "Jose Altuve", "Bill Doran"], correct: 0 },
        { question: "Who won the 2017 AL MVP?", answers: ["Jose Altuve", "Aaron Judge", "Giancarlo Stanton", "Mike Trout"], correct: 0 },
        { question: "Which second baseman was the first to hit 40 home runs and steal 40 bases?", answers: ["Alfonso Soriano", "Jeff Kent", "Chase Utley", "Ian Kinsler"], correct: 0 },
        { question: "Who was the first second baseman to win five batting titles?", answers: ["Rod Carew", "Roberto Alomar", "Ryne Sandberg", "Chase Utley"], correct: 0 },
        { question: "Which second baseman hit for the cycle three times?", answers: ["Adrian Beltre", "John Reilly", "Bob Meusel", "Babe Herman"], correct: 0 },
        { question: "Who was the second baseman for the 1908 Merkle's Boner incident?", answers: ["Fred Merkle", "Johnny Evers", "Miller Huggins", "Honus Wagner"], correct: 0 },
        { question: "Which second baseman won the 1987 NL MVP?", answers: ["Ryne Sandberg", "Rick Sutcliffe", "Dave Parker", "Will Clark"], correct: 0 },
        { question: "Who was the first second baseman to hit 100 home runs?", answers: ["Rogers Hornsby", "Charlie Gehringer", "Eddie Collins", "Nap Lajoie"], correct: 0 },
        { question: "Which second baseman led the NL in triples eight times?", answers: ["Rogers Hornsby", "Craig Biggio", "Joe Morgan", "Ryne Sandberg"], correct: 0 },
        { question: "Who was the 1959 AL MVP at second base?", answers: ["Nellie Fox", "Ron Hansen", "Frank Malzone", "Ron Hansen"], correct: 0 },
        { question: "Which second baseman won consecutive Gold Gloves from 2007-2011?", answers: ["Chase Utley", "Ian Kinsler", "Dustin Pedroia", "Robinson Cano"], correct: 0 },
        { question: "Who was the first second baseman to win the AL batting title?", answers: ["Eddie Collins", "Nap Lajoie", "Rogers Hornsby", "Charlie Gehringer"], correct: 0 },
        { question: "Which second baseman was the 1960 AL MVP?", answers: ["Ron Hansen", "Nellie Fox", "Zoilo Versalles", "Earl Battey"], correct: 0 },
        { question: "Who was the second baseman for the 1976 Reds World Series champions?", answers: ["Joe Morgan", "Pete Rose", "Johnny Bench", "Tony Perez"], correct: 0 },
        { question: "Which second baseman won the 1991 AL MVP?", answers: ["Cal Ripken Jr.", "Roberto Alomar", "Cecil Fielder", "Frank Thomas"], correct: 0 },
        { question: "Who was the second baseman for the 1981 Dodgers World Series champions?", answers: ["Steve Sax", "Ron Cey", "Pedro Guerrero", "Mike Scioscia"], correct: 0 },
        { question: "Which second baseman hit .370 over a 25-year career?", answers: ["Rogers Hornsby", "Nap Lajoie", "Eddie Collins", "Rod Carew"], correct: 0 },
        { question: "Who won the 1984 NL MVP at second base?", answers: ["Ryne Sandberg", "Rick Sutcliffe", "Lee Smith", "Jody Davis"], correct: 0 },
        { question: "Which second baseman was the 1978 AL MVP?", answers: ["Rod Carew", "Ron Guidry", "Jim Rice", "Fred Lynn"], correct: 0 },
        { question: "Who was the second baseman for the 1996 Yankees World Series champions?", answers: ["Chuck Knoblauch", "Derek Jeter", "Bernie Williams", "Paul O'Neill"], correct: 0 },
        { question: "Which second baseman won the 1965 AL MVP?", answers: ["Zoilo Versalles", "Tony Oliva", "Earl Battey", "Mudcat Grant"], correct: 0 },
        { question: "Who was the second baseman for the 2008 Phillies World Series champions?", answers: ["Chase Utley", "Jimmy Rollins", "Ryan Howard", "Cole Hamels"], correct: 0 },
        { question: "Which second baseman hit .424 in 1924?", answers: ["Rogers Hornsby", "Nap Lajoie", "Eddie Collins", "Rod Carew"], correct: 0 },
        { question: "Who won the 2011 AL MVP at second base?", answers: ["Robinson Cano", "Curtis Granderson", "Mark Teixeira", "CC Sabathia"], correct: 0 },
        { question: "Which second baseman was the 1989 NL MVP?", answers: ["Will Clark", "Kevin Mitchell", "Andy Van Slyke", "Bobby Bonilla"], correct: 0 },
        { question: "Who was the second baseman for the 1979 Pirates World Series champions?", answers: ["Phil Garner", "Dave Parker", "Willie Stargell", "Tim Foli"], correct: 0 },
        { question: "Which second baseman won the 1998 NL MVP?", answers: ["Mark McGwire", "Barry Bonds", "Sammy Sosa", "Jeff Bagwell"], correct: 0 },
        { question: "Who was the second baseman for the 1987 Twins World Series champions?", answers: ["Steve Lombardozzi", "Kent Hrbek", "Tom Brunansky", "Frank Viola"], correct: 0 },
        { question: "Which second baseman hit .401 in 1922?", answers: ["Rogers Hornsby", "George Sisler", "Ty Cobb", "Harry Heilmann"], correct: 0 },
        { question: "Who won the 2007 NL MVP at second base?", answers: ["Jimmy Rollins", "Chase Utley", "Ryan Howard", "Cole Hamels"], correct: 0 },
        { question: "Which second baseman was the 1972 AL MVP?", answers: ["Dick Allen", "Carl Yastrzemski", "Luis Tiant", "Ken Harrelson"], correct: 0 },
        { question: "Who was the second baseman for the 1990 Reds World Series champions?", answers: ["Mariano Duncan", "Barry Larkin", "Chris Sabo", "Randy Myers"], correct: 0 },
        { question: "Which second baseman won the 1951 AL MVP?", answers: ["Phil Rizzuto", "Yogi Berra", "Mickey Mantle", "Joe DiMaggio"], correct: 0 },
        { question: "Who was the second baseman for the 1983 Orioles World Series champions?", answers: ["Rich Dauer", "Eddie Murray", "Cal Ripken Jr.", "Rick Dempsey"], correct: 0 },
        { question: "Which second baseman hit .388 in 1911?", answers: ["Ty Cobb", "Nap Lajoie", "Eddie Collins", "Rogers Hornsby"], correct: 0 },
        { question: "Who won the 2012 AL MVP at second base?", answers: ["Robinson Cano", "Derek Jeter", "Curtis Granderson", "Mark Teixeira"], correct: 0 },
        { question: "Which second baseman was the 1985 NL MVP?", answers: ["Will Clark", "Dave Parker", "Rick Reuschel", "Dave Concepcion"], correct: 0 },
        { question: "Who was the second baseman for the 1973 Mets World Series champions?", answers: ["Felix Millan", "Bud Harrelson", "Cleon Jones", "Tom Seaver"], correct: 0 },
        { question: "Which second baseman won the 1968 AL MVP?", answers: ["Denny McLain", "Al Kaline", "Dick McAuliffe", "Mickey Lolich"], correct: 0 },
        { question: "Who was the second baseman for the 2002 Angels World Series champions?", answers: ["Adam Kennedy", "Garret Anderson", "Troy Glaus", "Tim Salmon"], correct: 0 },
        { question: "Which second baseman hit .370 in 1927?", answers: ["Paul Waner", "Rogers Hornsby", "Heinie Manush", "Kiki Cuyler"], correct: 0 },
        { question: "Who won the 2009 AL MVP at second base?", answers: ["Mark Teixeira", "Derek Jeter", "Alex Rodriguez", "CC Sabathia"], correct: 0 },
        { question: "Which second baseman was the 1993 NL MVP?", answers: ["Barry Bonds", "Matt Williams", "Greg Maddux", "Tom Glavine"], correct: 0 },
        { question: "Who was the second baseman for the 1986 Red Sox World Series champions?", answers: ["Marty Barrett", "Wade Boggs", "Bill Buckner", "Roger Clemens"], correct: 0 }
    ],
    "3B": [
        { question: "Who holds the record for most home runs by a third baseman with 509?", answers: ["Mike Schmidt", "Eddie Mathews", "Chipper Jones", "Alex Rodriguez"], correct: 0 },
        { question: "Which third baseman won 10 Gold Glove Awards?", answers: ["Brooks Robinson", "Mike Schmidt", "Ron Hansen", "Scott Rolen"], correct: 0 },
        { question: "Who was nicknamed 'The Iron Horse'?", answers: ["Lou Gehrig", "Cal Ripken Jr.", "Brooks Robinson", "Mike Schmidt"], correct: 0 },
        { question: "Which third baseman won the Triple Crown in 1966?", answers: ["Frank Robinson", "Hank Aaron", "Ron Hansen", "Brooks Robinson"], correct: 0 },
        { question: "Who was the first third baseman to hit 500 home runs?", answers: ["Mike Schmidt", "Eddie Mathews", "Chipper Jones", "Alex Rodriguez"], correct: 0 },
        { question: "Which third baseman batted .406 in 1922?", answers: ["Rogers Hornsby", "George Sisler", "Ty Cobb", "Harry Heilmann"], correct: 0 },
        { question: "Who won the 1980 NL MVP?", answers: ["Mike Schmidt", "Pete Rose", "George Foster", "Johnny Bench"], correct: 0 },
        { question: "Which third baseman was known as 'Mr. Cub'?", answers: ["Ron Hansen", "Ryne Sandberg", "Ernie Banks", "Ron Santo"], correct: 0 },
        { question: "Who was the third baseman for the 1969 Mets World Series champions?", answers: ["Ed Charles", "Ron Hansen", "Cleon Jones", "Tom Seaver"], correct: 0 },
        { question: "Which third baseman won the 1995 NL MVP?", answers: ["Chipper Jones", "Greg Maddux", "Tom Glavine", "Fred McGriff"], correct: 0 },
        { question: "Who was the first third baseman to win five Gold Gloves?", answers: ["Scott Rolen", "Mike Schmidt", "Brooks Robinson", "Ron Hansen"], correct: 0 },
        { question: "Which third baseman hit 47 home runs in 1998?", answers: ["Ken Caminiti", "Mark McGwire", "Sammy Sosa", "Greg Vaughn"], correct: 0 },
        { question: "Who won the 1979 AL MVP?", answers: ["Don Baylor", "Fred Lynn", "Jim Rice", "Carl Yastrzemski"], correct: 0 },
        { question: "Which third baseman was the 1981 NL MVP?", answers: ["Mike Schmidt", "Pete Rose", "Steve Carlton", "Gary Carter"], correct: 0 },
        { question: "Who was the third baseman for the 1984 Tigers World Series champions?", answers: ["Tom Brookens", "Alan Trammell", "Lou Whitaker", "Jack Morris"], correct: 0 },
        { question: "Which third baseman won the 1968 AL MVP?", answers: ["Denny McLain", "Al Kaline", "Dick McAuliffe", "Mickey Lolich"], correct: 0 },
        { question: "Who was the first third baseman to hit 40 home runs in a season?", answers: ["Eddie Mathews", "Mike Schmidt", "Chipper Jones", "Alex Rodriguez"], correct: 0 },
        { question: "Which third baseman batted .349 in 1953?", answers: ["Eddie Mathews", "Hank Aaron", "Warren Spahn", "Red Schoendienst"], correct: 0 },
        { question: "Who won the 2003 NL MVP?", answers: ["Barry Bonds", "Albert Pujols", "Jeff Bagwell", "Scott Rolen"], correct: 0 },
        { question: "Which third baseman was the 1970 AL MVP?", answers: ["Boog Powell", "Frank Robinson", "Brooks Robinson", "Dave McNally"], correct: 0 },
        { question: "Who was the third baseman for the 1997 Marlins World Series champions?", answers: ["Bobby Bonilla", "Craig Counsell", "Gary Sheffield", "Kevin Brown"], correct: 0 },
        { question: "Which third baseman won the 1986 NL MVP?", answers: ["Mike Schmidt", "Rick Sutcliffe", "Lee Smith", "Jody Davis"], correct: 0 },
        { question: "Who was the first third baseman to win the AL batting title?", answers: ["Heinie Groh", "Pie Traynor", "Eddie Mathews", "Ron Hansen"], correct: 0 },
        { question: "Which third baseman hit .320 over a 23-year career?", answers: ["Brooks Robinson", "Mike Schmidt", "Eddie Mathews", "Chipper Jones"], correct: 0 },
        { question: "Who won the 1999 NL MVP?", answers: ["Chipper Jones", "Mark McGwire", "Sammy Sosa", "Jeff Bagwell"], correct: 0 },
        { question: "Which third baseman was the 1964 NL MVP?", answers: ["Ken Boyer", "Ron Hansen", "Dick Groat", "Bill Mazeroski"], correct: 0 },
        { question: "Who was the third baseman for the 2001 Diamondbacks World Series champions?", answers: ["Matt Williams", "Randy Johnson", "Curt Schilling", "Luis Gonzalez"], correct: 0 },
        { question: "Which third baseman won the 1972 NL MVP?", answers: ["Johnny Bench", "Joe Morgan", "Tony Perez", "Pete Rose"], correct: 0 },
        { question: "Who was the first third baseman to hit 100 home runs?", answers: ["Eddie Mathews", "Mike Schmidt", "Chipper Jones", "Alex Rodriguez"], correct: 0 },
        { question: "Which third baseman batted .302 in 1948?", answers: ["Stan Musial", "Enos Slaughter", "Red Schoendienst", "Eddie Mathews"], correct: 0 },
        { question: "Who won the 1982 NL MVP?", answers: ["Dale Murphy", "Mike Schmidt", "Steve Carlton", "Gary Carter"], correct: 0 },
        { question: "Which third baseman was the 1957 NL MVP?", answers: ["Hank Aaron", "Eddie Mathews", "Warren Spahn", "Red Schoendienst"], correct: 0 },
        { question: "Who was the third baseman for the 1989 Giants World Series champions?", answers: ["Kevin Mitchell", "Will Clark", "Matt Williams", "Rick Reuschel"], correct: 0 },
        { question: "Which third baseman won the 1967 AL MVP?", answers: ["Carl Yastrzemski", "Tony Conigliaro", "Jim Lonborg", "Dick Williams"], correct: 0 },
        { question: "Who was the first third baseman to win four consecutive Gold Gloves?", answers: ["Scott Rolen", "Mike Schmidt", "Brooks Robinson", "Ron Hansen"], correct: 0 },
        { question: "Which third baseman hit 44 home runs in 2001?", answers: ["Chipper Jones", "Barry Bonds", "Jeff Bagwell", "Lance Berkman"], correct: 0 },
        { question: "Who won the 1977 NL MVP?", answers: ["George Foster", "Pete Rose", "Johnny Bench", "Joe Morgan"], correct: 0 },
        { question: "Which third baseman was the 1953 NL MVP?", answers: ["Roy Campanella", "Duke Snider", "Carl Furillo", "Preacher Roe"], correct: 0 },
        { question: "Who was the third baseman for the 1998 Padres World Series champions?", answers: ["Ken Caminiti", "Tony Gwynn", "Greg Vaughn", "Trevor Hoffman"], correct: 0 },
        { question: "Which third baseman won the 1987 NL MVP?", answers: ["Andre Dawson", "Ryne Sandberg", "Rick Sutcliffe", "Dave Parker"], correct: 0 },
        { question: "Who was the first third baseman to hit 300 home runs?", answers: ["Eddie Mathews", "Mike Schmidt", "Chipper Jones", "Alex Rodriguez"], correct: 0 },
        { question: "Which third baseman batted .324 in 1960?", answers: ["Ron Hansen", "Ernie Banks", "Ron Santo", "Dick Groat"], correct: 0 },
        { question: "Who won the 2000 NL MVP?", answers: ["Jeff Kent", "Barry Bonds", "Mark McGwire", "Matt Williams"], correct: 0 },
        { question: "Which third baseman was the 1969 AL MVP?", answers: ["Harmon Killebrew", "Tony Oliva", "Rod Carew", "Leo Cardenas"], correct: 0 },
        { question: "Who was the third baseman for the 1985 Royals World Series champions?", answers: ["George Brett", "Frank White", "Hal McRae", "Dan Quisenberry"], correct: 0 },
        { question: "Which third baseman won the 1974 NL MVP?", answers: ["Steve Garvey", "Joe Torre", "Ron Cey", "Don Sutton"], correct: 0 },
        { question: "Who was the first third baseman to win the NL batting title?", answers: ["Pie Traynor", "Eddie Mathews", "Ron Hansen", "Heinie Groh"], correct: 0 },
        { question: "Which third baseman hit 39 home runs in 1996?", answers: ["Matt Williams", "Barry Bonds", "Mark McGwire", "Jeff Bagwell"], correct: 0 },
        { question: "Who won the 1983 NL MVP?", answers: ["Dale Murphy", "Mike Schmidt", "Steve Carlton", "Gary Carter"], correct: 0 },
        { question: "Which third baseman was the 1959 NL MVP?", answers: ["Ernie Banks", "Ron Hansen", "Hank Aaron", "Warren Spahn"], correct: 0 }
    ],
    "SS": [
        { question: "Which shortstop won the most Gold Glove Awards (13)?", answers: ["Ozzie Smith", "Omar Vizquel", "Cal Ripken Jr.", "Derek Jeter"], correct: 0 },
        { question: "Who holds the record for consecutive games played (2,632)?", answers: ["Cal Ripken Jr.", "Lou Gehrig", "Miguel Tejada", "Steve Garvey"], correct: 0 },
        { question: "Which shortstop was nicknamed 'The Wizard'?", answers: ["Ozzie Smith", "Derek Jeter", "Alex Rodriguez", "Honus Wagner"], correct: 0 },
        { question: "Which shortstop won eight batting titles?", answers: ["Honus Wagner", "Luke Appling", "Arky Vaughan", "Cal Ripken Jr."], correct: 0 },
        { question: "Which shortstop hit .385 in 1935?", answers: ["Arky Vaughan", "Honus Wagner", "Lou Boudreau", "Joe Cronin"], correct: 0 },
        { question: "Which shortstop won the 1991 AL MVP?", answers: ["Cal Ripken Jr.", "Cecil Fielder", "Frank Thomas", "Jose Canseco"], correct: 0 },
        { question: "Who won back-to-back AL MVPs in 2001-2002?", answers: ["Alex Rodriguez", "Miguel Tejada", "Ichiro Suzuki", "Jason Giambi"], correct: 0 },
        { question: "Who was the 1948 AL MVP as player-manager?", answers: ["Lou Boudreau", "Joe Gordon", "Ted Williams", "Joe DiMaggio"], correct: 0 },
        { question: "Which shortstop won the 1999 AL MVP?", answers: ["Ivan Rodriguez", "Pedro Martinez", "Nomar Garciaparra", "Roberto Alomar"], correct: 0 },
        { question: "Who hit 57 home runs in 2002?", answers: ["Alex Rodriguez", "Sammy Sosa", "Barry Bonds", "Jim Thome"], correct: 0 },
        { question: "Which shortstop won the 2011 NL MVP?", answers: ["Ryan Braun", "Matt Kemp", "Prince Fielder", "Justin Verlander"], correct: 0 },
        { question: "Who was the 1982 NL Rookie of the Year?", answers: ["Steve Sax", "Cal Ripken Jr.", "Johnny Ray", "Kent Hrbek"], correct: 0 },
        { question: "Which shortstop won five Gold Gloves with the Yankees?", answers: ["Derek Jeter", "Tony Kubek", "Phil Rizzuto", "Bucky Dent"], correct: 0 },
        { question: "Who batted .353 over 20 seasons?", answers: ["Honus Wagner", "Arky Vaughan", "Lou Boudreau", "Luke Appling"], correct: 0 },
        { question: "Which shortstop was the 1995 AL Rookie of the Year?", answers: ["Marty Cordova", "Garret Anderson", "Shawn Green", "Nomar Garciaparra"], correct: 0 },
        { question: "Who was the first shortstop to hit 40 home runs in a season?", answers: ["Alex Rodriguez", "Ernie Banks", "Ron Hansen", "Cal Ripken Jr."], correct: 0 },
        { question: "Which shortstop won the 1960 AL MVP?", answers: ["Ron Hansen", "Nellie Fox", "Luis Aparicio", "Ron Hansen"], correct: 0 },
        { question: "Who was the shortstop for the 1970 Orioles World Series champions?", answers: ["Mark Belanger", "Ron Hansen", "Luis Aparicio", "Ron Hansen"], correct: 0 },
        { question: "Which shortstop led the AL in triples seven times?", answers: ["Ron Hansen", "Luis Aparicio", "Ron Hansen", "Dick Howser"], correct: 0 },
        { question: "Who was the first shortstop to win the AL batting title?", answers: ["Luke Appling", "Honus Wagner", "Arky Vaughan", "Joe Cronin"], correct: 0 },
        { question: "Which shortstop won the 1985 AL MVP?", answers: ["Don Mattingly", "Rickey Henderson", "Dave Winfield", "George Brett"], correct: 0 },
        { question: "Who was the shortstop for the 1996 Yankees World Series champions?", answers: ["Derek Jeter", "Bernie Williams", "Paul O'Neill", "Tino Martinez"], correct: 0 },
        { question: "Which shortstop won the 1978 AL MVP?", answers: ["Jim Rice", "Fred Lynn", "Carl Yastrzemski", "Dwight Evans"], correct: 0 },
        { question: "Who was the first shortstop to hit 500 home runs?", answers: ["Alex Rodriguez", "Cal Ripken Jr.", "Ernie Banks", "Miguel Tejada"], correct: 0 },
        { question: "Which shortstop batted .388 in 1911?", answers: ["Honus Wagner", "Ty Cobb", "Shoeless Joe Jackson", "Tris Speaker"], correct: 0 },
        { question: "Who won the 2009 AL MVP?", answers: ["Joe Mauer", "Derek Jeter", "Mark Teixeira", "Alex Rodriguez"], correct: 0 },
        { question: "Which shortstop was the 1967 AL MVP?", answers: ["Carl Yastrzemski", "Tony Conigliaro", "Jim Lonborg", "Dick Williams"], correct: 0 },
        { question: "Who was the shortstop for the 1984 Tigers World Series champions?", answers: ["Alan Trammell", "Lou Whitaker", "Jack Morris", "Kirk Gibson"], correct: 0 },
        { question: "Which shortstop won the 1996 AL MVP?", answers: ["Juan Gonzalez", "Alex Rodriguez", "Kenny Lofton", "Frank Thomas"], correct: 0 },
        { question: "Who was the first shortstop to win the NL batting title?", answers: ["Honus Wagner", "Arky Vaughan", "Luke Appling", "Joe Cronin"], correct: 0 },
        { question: "Which shortstop hit .370 in 1924?", answers: ["Rogers Hornsby", "George Sisler", "Ty Cobb", "Honus Wagner"], correct: 0 },
        { question: "Who won the 2010 AL MVP?", answers: ["Josh Hamilton", "Miguel Cabrera", "Robinson Cano", "Vladimir Guerrero"], correct: 0 },
        { question: "Which shortstop was the 1959 AL MVP?", answers: ["Nellie Fox", "Ron Hansen", "Luis Aparicio", "Rocky Colavito"], correct: 0 },
        { question: "Who was the shortstop for the 1979 Pirates World Series champions?", answers: ["Tim Foli", "Dave Parker", "Willie Stargell", "Phil Garner"], correct: 0 },
        { question: "Which shortstop won the 1987 AL MVP?", answers: ["George Bell", "Don Mattingly", "Dave Winfield", "Rickey Henderson"], correct: 0 },
        { question: "Who was the first shortstop to hit 100 home runs?", answers: ["Ernie Banks", "Ron Hansen", "Cal Ripken Jr.", "Alex Rodriguez"], correct: 0 },
        { question: "Which shortstop batted .349 in 1948?", answers: ["Stan Musial", "Ted Williams", "Lou Boudreau", "George Kell"], correct: 0 },
        { question: "Who won the 2005 AL MVP?", answers: ["Alex Rodriguez", "Vladimir Guerrero", "Mariano Rivera", "Hideki Matsui"], correct: 0 },
        { question: "Which shortstop was the 1965 AL MVP?", answers: ["Zoilo Versalles", "Tony Oliva", "Earl Battey", "Mudcat Grant"], correct: 0 },
        { question: "Who was the shortstop for the 1990 Reds World Series champions?", answers: ["Barry Larkin", "Chris Sabo", "Randy Myers", "Jose Rijo"], correct: 0 },
        { question: "Who was the first shortstop to win five Gold Gloves?", answers: ["Ron Hansen", "Ozzie Smith", "Omar Vizquel", "Derek Jeter"], correct: 0 },
        { question: "Which shortstop hit .340 in 1959?", answers: ["Nellie Fox", "Ron Hansen", "Luis Aparicio", "Rocky Colavito"], correct: 0 },
        { question: "Who won the 2007 AL MVP?", answers: ["Alex Rodriguez", "Magglio Ordonez", "Carlos Pena", "Vladimir Guerrero"], correct: 0 },
        { question: "Which shortstop was the 1957 AL MVP?", answers: ["Ted Williams", "Mickey Mantle", "Yogi Berra", "Enos Slaughter"], correct: 0 },
        { question: "Who was the shortstop for the 1986 Red Sox World Series champions?", answers: ["Wade Boggs", "Bill Buckner", "Roger Clemens", "Rich Gedman"], correct: 0 },
        { question: "Which shortstop won the 1992 AL MVP?", answers: ["Dennis Eckersley", "Roberto Alomar", "Cal Ripken Jr.", "Frank Thomas"], correct: 0 },
        { question: "Who was the first shortstop to hit 300 home runs?", answers: ["Ernie Banks", "Cal Ripken Jr.", "Alex Rodriguez", "Miguel Tejada"], correct: 0 },
        { question: "Which shortstop batted .324 in 1936?", answers: ["Lou Gehrig", "Bill Dickey", "Joe DiMaggio", "Arky Vaughan"], correct: 0 },
        { question: "Who won the 2003 AL MVP?", answers: ["Alex Rodriguez", "Carlos Delgado", "Miguel Tejada", "Vladimir Guerrero"], correct: 0 },
        { question: "Which shortstop was the 1962 AL MVP?", answers: ["Frank Malzone", "Dick Howser", "Ron Hansen", "Zoilo Versalles"], correct: 0 }
    ],
    "C": [
        { question: "Which catcher caught 2,226 consecutive games without an error?", answers: ["Mike Matheny", "Johnny Bench", "Yadier Molina", "Ivan Rodriguez"], correct: 0 },
        { question: "Who was the first catcher to win three MVP awards?", answers: ["Yogi Berra", "Johnny Bench", "Roy Campanella", "Josh Gibson"], correct: 0 },
        { question: "Which catcher won the most Gold Glove Awards (13)?", answers: ["Ivan Rodriguez", "Johnny Bench", "Yadier Molina", "Bob Boone"], correct: 0 },
        { question: "Which catcher hit 396 home runs, the most by a catcher in MLB history?", answers: ["Mike Piazza", "Johnny Bench", "Carlton Fisk", "Yogi Berra"], correct: 0 },
        { question: "Which catcher won the 2009 AL MVP award?", answers: ["Joe Mauer", "Jorge Posada", "Victor Martinez", "Buster Posey"], correct: 0 },
        { question: "Who caught Don Larsen's perfect game in the 1956 World Series?", answers: ["Yogi Berra", "Roy Campanella", "Elston Howard", "Smoky Burgess"], correct: 0 },
        { question: "Which catcher won three NL MVP awards in the 1950s?", answers: ["Roy Campanella", "Yogi Berra", "Ernie Banks", "Stan Musial"], correct: 0 },
        { question: "Who was the 2010 NL Rookie of the Year?", answers: ["Buster Posey", "Jason Heyward", "Gaby Sanchez", "Jaime Garcia"], correct: 0 },
        { question: "Which catcher hit .362 in 1997?", answers: ["Larry Walker", "Tony Gwynn", "Mike Piazza", "Frank Thomas"], correct: 0 },
        { question: "Who won the 1970 NL MVP?", answers: ["Johnny Bench", "Billy Williams", "Tony Perez", "Willie McCovey"], correct: 0 },
        { question: "Which catcher was the 1951 AL MVP?", answers: ["Yogi Berra", "Ferris Fain", "Eddie Stanky", "Nellie Fox"], correct: 0 },
        { question: "Who caught three no-hitters in his career?", answers: ["Jason Varitek", "Alan Ashby", "Ray Schalk", "Ron Hassey"], correct: 0 },
        { question: "Which catcher won the 1998 AL Rookie of the Year?", answers: ["Ben Grieve", "Rolando Arrojo", "Todd Helton", "Kerry Wood"], correct: 0 },
        { question: "Who was the 2012 NL MVP?", answers: ["Buster Posey", "Andrew McCutchen", "Ryan Braun", "Yadier Molina"], correct: 0 },
        { question: "Which catcher batted .308 over 19 seasons?", answers: ["Bill Dickey", "Mickey Cochrane", "Gabby Hartnett", "Ernie Lombardi"], correct: 0 },
        { question: "Who won the 1935 AL MVP?", answers: ["Hank Greenberg", "Lou Gehrig", "Charlie Gehringer", "Jimmie Foxx"], correct: 0 },
        { question: "Which catcher was nicknamed 'Pudge'?", answers: ["Ivan Rodriguez", "Carlton Fisk", "Josh Gibson", "Ernie Lombardi"], correct: 0 },
        { question: "Who hit .342 in 1938?", answers: ["Jimmie Foxx", "Hank Greenberg", "Joe Medwick", "Ernie Lombardi"], correct: 0 },
        { question: "Which catcher won 10 Gold Gloves?", answers: ["Johnny Bench", "Ivan Rodriguez", "Yadier Molina", "Bob Boone"], correct: 0 },
        { question: "Who was the 1976 AL Rookie of the Year?", answers: ["Mark Fidrych", "Butch Wynegar", "Willie Randolph", "Pat Zachry"], correct: 0 },
        { question: "Which catcher won the 1983 AL MVP?", answers: ["Cal Ripken Jr.", "Eddie Murray", "Rick Dempsey", "Jim Palmer"], correct: 0 },
        { question: "Who was the catcher for the 1996 Yankees World Series champions?", answers: ["Joe Girardi", "Derek Jeter", "Paul O'Neill", "Tino Martinez"], correct: 0 },
        { question: "Which catcher won the 1978 AL MVP?", answers: ["Jim Rice", "Fred Lynn", "Carl Yastrzemski", "Butch Wynegar"], correct: 0 },
        { question: "Who was the first catcher to hit 300 home runs?", answers: ["Mike Piazza", "Johnny Bench", "Carlton Fisk", "Yogi Berra"], correct: 0 },
        { question: "Which catcher batted .349 in 1953?", answers: ["Roy Campanella", "Duke Snider", "Carl Furillo", "Preacher Roe"], correct: 0 },
        { question: "Who won the 2004 NL MVP?", answers: ["Barry Bonds", "Jeff Kent", "Scott Rolen", "Mike Piazza"], correct: 0 },
        { question: "Which catcher was the 1969 AL MVP?", answers: ["Harmon Killebrew", "Tony Oliva", "Rod Carew", "Leo Cardenas"], correct: 0 },
        { question: "Who was the catcher for the 1984 Tigers World Series champions?", answers: ["Lance Parrish", "Alan Trammell", "Lou Whitaker", "Jack Morris"], correct: 0 },
        { question: "Which catcher won the 1996 AL MVP?", answers: ["Juan Gonzalez", "Alex Rodriguez", "Kenny Lofton", "Ivan Rodriguez"], correct: 0 },
        { question: "Who was the first catcher to win the AL batting title?", answers: ["Mickey Cochrane", "Bill Dickey", "Yogi Berra", "Joe Torre"], correct: 0 },
        { question: "Which catcher hit .320 in 1941?", answers: ["Ted Williams", "Joe DiMaggio", "Stan Musial", "Bill Dickey"], correct: 0 },
        { question: "Who won the 2011 NL MVP?", answers: ["Ryan Braun", "Matt Kemp", "Prince Fielder", "Buster Posey"], correct: 0 },
        { question: "Which catcher was the 1959 AL MVP?", answers: ["Nellie Fox", "Ron Hansen", "Luis Aparicio", "Rocky Colavito"], correct: 0 },
        { question: "Who was the catcher for the 1979 Pirates World Series champions?", answers: ["Manny Sanguillen", "Dave Parker", "Willie Stargell", "Tim Foli"], correct: 0 },
        { question: "Which catcher won the 1987 AL MVP?", answers: ["George Bell", "Don Mattingly", "Dave Winfield", "Rickey Henderson"], correct: 0 },
        { question: "Who was the first catcher to hit 100 home runs?", answers: ["Yogi Berra", "Roy Campanella", "Johnny Bench", "Mike Piazza"], correct: 0 },
        { question: "Which catcher batted .302 in 1948?", answers: ["Stan Musial", "Ted Williams", "Lou Boudreau", "Bill Dickey"], correct: 0 },
        { question: "Who won the 2000 NL MVP?", answers: ["Jeff Kent", "Barry Bonds", "Mark McGwire", "Mike Piazza"], correct: 0 },
        { question: "Which catcher was the 1965 AL MVP?", answers: ["Zoilo Versalles", "Tony Oliva", "Earl Battey", "Mudcat Grant"], correct: 0 },
        { question: "Who was the catcher for the 1990 Reds World Series champions?", answers: ["Joe Oliver", "Chris Sabo", "Randy Myers", "Jose Rijo"], correct: 0 },
        { question: "Which catcher won the 1975 AL MVP?", answers: ["Fred Lynn", "Jim Rice", "Carl Yastrzemski", "Dwight Evans"], correct: 0 },
        { question: "Who was the first catcher to win five Gold Gloves?", answers: ["Johnny Bench", "Ivan Rodriguez", "Yadier Molina", "Joe Torre"], correct: 0 },
        { question: "Which catcher hit .340 in 1959?", answers: ["Nellie Fox", "Ron Hansen", "Luis Aparicio", "Del Crandall"], correct: 0 },
        { question: "Who won the 2007 NL MVP?", answers: ["Jimmy Rollins", "Chase Utley", "Ryan Howard", "Albert Pujols"], correct: 0 },
        { question: "Which catcher was the 1957 AL MVP?", answers: ["Ted Williams", "Mickey Mantle", "Yogi Berra", "Enos Slaughter"], correct: 0 },
        { question: "Who was the catcher for the 1986 Red Sox World Series champions?", answers: ["Rich Gedman", "Wade Boggs", "Bill Buckner", "Roger Clemens"], correct: 0 },
        { question: "Which catcher won the 1992 AL MVP?", answers: ["Dennis Eckersley", "Roberto Alomar", "Cal Ripken Jr.", "Frank Thomas"], correct: 0 },
        { question: "Who was the first catcher to hit 200 home runs?", answers: ["Johnny Bench", "Carlton Fisk", "Yogi Berra", "Mike Piazza"], correct: 0 },
        { question: "Which catcher batted .324 in 1936?", answers: ["Lou Gehrig", "Bill Dickey", "Joe DiMaggio", "Mickey Cochrane"], correct: 0 },
        { question: "Who won the 2003 NL MVP?", answers: ["Barry Bonds", "Albert Pujols", "Jeff Bagwell", "Scott Rolen"], correct: 0 },
        { question: "Which catcher was the 1962 AL MVP?", answers: ["Frank Malzone", "Dick Howser", "Ron Hansen", "Earl Battey"], correct: 0 }
    ],
    "LF": [
        { question: "Which left fielder won the 2018 NL MVP with the Brewers?", answers: ["Christian Yelich", "Ryan Braun", "Lorenzo Cain", "Travis Shaw"], correct: 0 },
        { question: "Who holds the record for most home runs by a left fielder in a single season?", answers: ["Barry Bonds", "Ted Williams", "Manny Ramirez", "Carl Yastrzemski"], correct: 0 },
        { question: "Which left fielder won 10 Gold Glove Awards?", answers: ["Barry Bonds", "Carl Crawford", "Rickey Henderson", "Lou Brock"], correct: 0 },
        { question: "Which left fielder won the Triple Crown in 1967?", answers: ["Carl Yastrzemski", "Ted Williams", "Ralph Kiner", "Stan Musial"], correct: 0 },
        { question: "Who hit .406 in 1941?", answers: ["Ted Williams", "Joe DiMaggio", "Stan Musial", "Hank Greenberg"], correct: 0 },
        { question: "Which left fielder won seven NL MVP awards?", answers: ["Barry Bonds", "Stan Musial", "Willie Mays", "Albert Pujols"], correct: 0 },
        { question: "Which left fielder batted .376 in 1948?", answers: ["Stan Musial", "Ted Williams", "Lou Boudreau", "Tommy Henrich"], correct: 0 },
        { question: "Who was the 1979 NL MVP?", answers: ["Willie Stargell", "Keith Hernandez", "Dave Winfield", "Dave Parker"], correct: 0 },
        { question: "Which left fielder hit 52 home runs in 1947?", answers: ["Ralph Kiner", "Johnny Mize", "Ted Williams", "Hank Greenberg"], correct: 0 },
        { question: "Who won the 1977 NL MVP?", answers: ["George Foster", "Dave Parker", "Greg Luzinski", "Steve Garvey"], correct: 0 },
        { question: "Which left fielder batted .344 in 1957?", answers: ["Ted Williams", "Mickey Mantle", "Stan Musial", "Willie Mays"], correct: 0 },
        { question: "Who was the 2011 NL MVP?", answers: ["Ryan Braun", "Matt Kemp", "Prince Fielder", "Justin Verlander"], correct: 0 },
        { question: "Which left fielder won three batting titles in the 1940s?", answers: ["Stan Musial", "Ted Williams", "Lou Boudreau", "George Kell"], correct: 0 },
        { question: "Who hit 369 home runs for the Red Sox?", answers: ["Ted Williams", "Carl Yastrzemski", "Jim Rice", "David Ortiz"], correct: 0 },
        { question: "Which left fielder was the 1975 AL MVP?", answers: ["Fred Lynn", "Thurman Munson", "Rod Carew", "Jim Rice"], correct: 0 },
        { question: "Who stole 938 bases in his career?", answers: ["Lou Brock", "Rickey Henderson", "Ty Cobb", "Billy Hamilton"], correct: 0 },
        { question: "Which left fielder won the 2013 NL MVP?", answers: ["Andrew McCutchen", "Paul Goldschmidt", "Yadier Molina", "Joey Votto"], correct: 0 },
        { question: "Who batted .357 over 22 seasons?", answers: ["Stan Musial", "Ted Williams", "Ty Cobb", "Tris Speaker"], correct: 0 },
        { question: "Which left fielder was the first to hit 400 home runs?", answers: ["Ted Williams", "Ralph Kiner", "Stan Musial", "Albert Pujols"], correct: 0 },
        { question: "Who was the left fielder for the 1966 Orioles World Series champions?", answers: ["Paul Blair", "Curt Blefary", "Boog Powell", "Frank Robinson"], correct: 0 },
        { question: "Which left fielder won the 1983 AL MVP?", answers: ["Cal Ripken Jr.", "Eddie Murray", "Rick Dempsey", "Jim Palmer"], correct: 0 },
        { question: "Who was the left fielder for the 1996 Yankees World Series champions?", answers: ["Paul O'Neill", "Derek Jeter", "Bernie Williams", "Tino Martinez"], correct: 0 },
        { question: "Which left fielder won the 1978 AL MVP?", answers: ["Jim Rice", "Fred Lynn", "Carl Yastrzemski", "Dwight Evans"], correct: 0 },
        { question: "Who was the first left fielder to hit 500 home runs?", answers: ["Ted Williams", "Ralph Kiner", "Stan Musial", "Albert Pujols"], correct: 0 },
        { question: "Which left fielder batted .349 in 1953?", answers: ["Roy Campanella", "Duke Snider", "Carl Furillo", "Ralph Branca"], correct: 0 },
        { question: "Who won the 2004 NL MVP?", answers: ["Barry Bonds", "Jeff Kent", "Scott Rolen", "Albert Pujols"], correct: 0 },
        { question: "Which left fielder was the 1969 AL MVP?", answers: ["Harmon Killebrew", "Tony Oliva", "Rod Carew", "Reggie Jackson"], correct: 0 },
        { question: "Who was the left fielder for the 1984 Tigers World Series champions?", answers: ["Kirk Gibson", "Alan Trammell", "Lou Whitaker", "Jack Morris"], correct: 0 },
        { question: "Which left fielder won the 1996 AL MVP?", answers: ["Juan Gonzalez", "Alex Rodriguez", "Kenny Lofton", "Paul O'Neill"], correct: 0 },
        { question: "Who was the first left fielder to win the AL batting title?", answers: ["George Sisler", "Ty Cobb", "Tris Speaker", "Babe Ruth"], correct: 0 },
        { question: "Which left fielder hit .320 in 1941?", answers: ["Ted Williams", "Joe DiMaggio", "Stan Musial", "Charlie Keller"], correct: 0 },
        { question: "Who won the 2011 AL MVP?", answers: ["Justin Verlander", "Miguel Cabrera", "Jacoby Ellsbury", "Adrian Gonzalez"], correct: 0 },
        { question: "Which left fielder was the 1959 AL MVP?", answers: ["Nellie Fox", "Ron Hansen", "Luis Aparicio", "Rocky Colavito"], correct: 0 },
        { question: "Who was the left fielder for the 1979 Pirates World Series champions?", answers: ["Willie Stargell", "Dave Parker", "Bill Madlock", "Tim Foli"], correct: 0 },
        { question: "Which left fielder won the 1987 AL MVP?", answers: ["George Bell", "Don Mattingly", "Dave Winfield", "Rickey Henderson"], correct: 0 },
        { question: "Who was the first left fielder to hit 100 home runs?", answers: ["Ralph Kiner", "Ted Williams", "Stan Musial", "Albert Pujols"], correct: 0 },
        { question: "Which left fielder batted .302 in 1948?", answers: ["Stan Musial", "Ted Williams", "Lou Boudreau", "Tommy Henrich"], correct: 0 },
        { question: "Who won the 2000 NL MVP?", answers: ["Jeff Kent", "Barry Bonds", "Mark McGwire", "Sammy Sosa"], correct: 0 },
        { question: "Which left fielder was the 1965 AL MVP?", answers: ["Zoilo Versalles", "Tony Oliva", "Earl Battey", "Mudcat Grant"], correct: 0 },
        { question: "Who was the left fielder for the 1990 Reds World Series champions?", answers: ["Chris Sabo", "Barry Larkin", "Randy Myers", "Jose Rijo"], correct: 0 },
        { question: "Which left fielder won the 1975 NL MVP?", answers: ["Joe Torre", "Steve Garvey", "Ron Cey", "Don Sutton"], correct: 0 },
        { question: "Who was the first left fielder to win five Gold Gloves?", answers: ["Barry Bonds", "Carl Crawford", "Rickey Henderson", "Lou Brock"], correct: 0 },
        { question: "Which left fielder hit .340 in 1959?", answers: ["Nellie Fox", "Ron Hansen", "Luis Aparicio", "Harvey Kuenn"], correct: 0 },
        { question: "Who won the 2007 NL MVP?", answers: ["Jimmy Rollins", "Chase Utley", "Ryan Howard", "Albert Pujols"], correct: 0 },
        { question: "Which left fielder was the 1957 AL MVP?", answers: ["Ted Williams", "Mickey Mantle", "Yogi Berra", "Enos Slaughter"], correct: 0 },
        { question: "Who was the left fielder for the 1986 Red Sox World Series champions?", answers: ["Jim Rice", "Wade Boggs", "Bill Buckner", "Roger Clemens"], correct: 0 },
        { question: "Which left fielder won the 1992 AL MVP?", answers: ["Dennis Eckersley", "Roberto Alomar", "Cal Ripken Jr.", "Frank Thomas"], correct: 0 },
        { question: "Who was the first left fielder to hit 200 home runs?", answers: ["Ralph Kiner", "Ted Williams", "Stan Musial", "Albert Pujols"], correct: 0 },
        { question: "Which left fielder batted .324 in 1936?", answers: ["Lou Gehrig", "Bill Dickey", "Joe DiMaggio", "Benny Goodman"], correct: 0 },
        { question: "Who won the 2003 NL MVP?", answers: ["Barry Bonds", "Albert Pujols", "Jeff Bagwell", "Scott Rolen"], correct: 0 },
        { question: "Which left fielder was the 1962 AL MVP?", answers: ["Frank Malzone", "Dick Howser", "Ron Hansen", "Norm Cash"], correct: 0 }
    ],
    "CF": [
        { question: "Who is the only center fielder to win three MVP awards?", answers: ["Mike Trout", "Mickey Mantle", "Willie Mays", "Ken Griffey Jr."], correct: 1 },
        { question: "Which center fielder made 'The Catch' in the 1954 World Series?", answers: ["Willie Mays", "Joe DiMaggio", "Duke Snider", "Mickey Mantle"], correct: 0 },
        { question: "Who holds the record for most consecutive games with a hit (56)?", answers: ["Joe DiMaggio", "Pete Rose", "Ty Cobb", "Willie Keeler"], correct: 0 },
        { question: "Which center fielder won 12 Gold Glove Awards?", answers: ["Willie Mays", "Ken Griffey Jr.", "Andruw Jones", "Mike Trout"], correct: 0 },
        { question: "Which center fielder hit .366 lifetime, the highest in the modern era?", answers: ["Ty Cobb", "Rogers Hornsby", "Shoeless Joe Jackson", "Tris Speaker"], correct: 0 },
        { question: "Who won the Triple Crown in 1956?", answers: ["Mickey Mantle", "Ted Williams", "Willie Mays", "Hank Aaron"], correct: 0 },
        { question: "Which center fielder hit 660 home runs?", answers: ["Willie Mays", "Ken Griffey Jr.", "Mickey Mantle", "Mike Trout"], correct: 0 },
        { question: "Who was the 1989 AL MVP?", answers: ["Robin Yount", "Ruben Sierra", "Kirby Puckett", "Bo Jackson"], correct: 0 },
        { question: "Which center fielder batted .356 in 1920?", answers: ["Tris Speaker", "Ty Cobb", "Babe Ruth", "George Sisler"], correct: 0 },
        { question: "Who won back-to-back MVP awards in 1965-1966?", answers: ["Willie Mays", "Frank Robinson", "Roberto Clemente", "Mickey Mantle"], correct: 0 },
        { question: "Which center fielder hit .408 in 1911?", answers: ["Ty Cobb", "Shoeless Joe Jackson", "Tris Speaker", "Sam Crawford"], correct: 0 },
        { question: "Who was the 1979 AL MVP?", answers: ["Don Baylor", "Fred Lynn", "Ken Singleton", "George Brett"], correct: 0 },
        { question: "Which center fielder won the 1995 AL MVP?", answers: ["Mo Vaughn", "Albert Belle", "Edgar Martinez", "Randy Johnson"], correct: 0 },
        { question: "Who hit 56 home runs in 1998?", answers: ["Ken Griffey Jr.", "Mark McGwire", "Sammy Sosa", "Barry Bonds"], correct: 0 },
        { question: "Which center fielder was the 1993 NL MVP?", answers: ["Barry Bonds", "Lenny Dykstra", "David Justice", "Jeff Bagwell"], correct: 0 },
        { question: "Who won 10 consecutive Gold Gloves from 1998-2007?", answers: ["Andruw Jones", "Jim Edmonds", "Ken Griffey Jr.", "Carlos Beltran"], correct: 0 },
        { question: "Which center fielder batted .420 in 1994?", answers: ["Tony Gwynn", "Jeff Bagwell", "Frank Thomas", "Kenny Lofton"], correct: 0 },
        { question: "Who was the 2014 AL MVP?", answers: ["Mike Trout", "Jose Abreu", "Victor Martinez", "Robinson Cano"], correct: 0 },
        { question: "Which center fielder hit .401 in 1922?", answers: ["George Sisler", "Rogers Hornsby", "Ty Cobb", "Harry Heilmann"], correct: 0 },
        { question: "Who won the 1954 NL MVP?", answers: ["Willie Mays", "Duke Snider", "Ted Kluszewski", "Hank Aaron"], correct: 0 },
        { question: "Which center fielder won the 1983 AL MVP?", answers: ["Cal Ripken Jr.", "Eddie Murray", "Rick Dempsey", "Jim Palmer"], correct: 0 },
        { question: "Who was the center fielder for the 1996 Yankees World Series champions?", answers: ["Bernie Williams", "Derek Jeter", "Paul O'Neill", "Tino Martinez"], correct: 0 },
        { question: "Which center fielder won the 1978 AL MVP?", answers: ["Jim Rice", "Fred Lynn", "Carl Yastrzemski", "Dwight Evans"], correct: 0 },
        { question: "Who was the first center fielder to hit 500 home runs?", answers: ["Willie Mays", "Ken Griffey Jr.", "Mickey Mantle", "Mike Trout"], correct: 0 },
        { question: "Which center fielder batted .349 in 1953?", answers: ["Roy Campanella", "Duke Snider", "Carl Furillo", "Ralph Branca"], correct: 0 },
        { question: "Who won the 2004 NL MVP?", answers: ["Barry Bonds", "Jeff Kent", "Scott Rolen", "Albert Pujols"], correct: 0 },
        { question: "Which center fielder was the 1969 AL MVP?", answers: ["Harmon Killebrew", "Tony Oliva", "Rod Carew", "Reggie Jackson"], correct: 0 },
        { question: "Who was the center fielder for the 1984 Tigers World Series champions?", answers: ["Kirk Gibson", "Alan Trammell", "Lou Whitaker", "Jack Morris"], correct: 0 },
        { question: "Which center fielder won the 1996 AL MVP?", answers: ["Juan Gonzalez", "Alex Rodriguez", "Kenny Lofton", "Paul O'Neill"], correct: 0 },
        { question: "Who was the first center fielder to win the AL batting title?", answers: ["George Sisler", "Ty Cobb", "Tris Speaker", "Babe Ruth"], correct: 0 },
        { question: "Which center fielder hit .320 in 1941?", answers: ["Ted Williams", "Joe DiMaggio", "Stan Musial", "Charlie Keller"], correct: 0 },
        { question: "Who won the 2011 AL MVP?", answers: ["Justin Verlander", "Miguel Cabrera", "Jacoby Ellsbury", "Adrian Gonzalez"], correct: 0 },
        { question: "Which center fielder was the 1959 AL MVP?", answers: ["Nellie Fox", "Ron Hansen", "Luis Aparicio", "Rocky Colavito"], correct: 0 },
        { question: "Who was the center fielder for the 1979 Pirates World Series champions?", answers: ["Willie Stargell", "Dave Parker", "Bill Madlock", "Tim Foli"], correct: 0 },
        { question: "Which center fielder won the 1987 AL MVP?", answers: ["George Bell", "Don Mattingly", "Dave Winfield", "Rickey Henderson"], correct: 0 },
        { question: "Who was the first center fielder to hit 100 home runs?", answers: ["Willie Mays", "Ken Griffey Jr.", "Mickey Mantle", "Mike Trout"], correct: 0 },
        { question: "Which center fielder batted .302 in 1948?", answers: ["Stan Musial", "Ted Williams", "Lou Boudreau", "Tommy Henrich"], correct: 0 },
        { question: "Who won the 2000 NL MVP?", answers: ["Jeff Kent", "Barry Bonds", "Mark McGwire", "Sammy Sosa"], correct: 0 },
        { question: "Which center fielder was the 1965 AL MVP?", answers: ["Zoilo Versalles", "Tony Oliva", "Earl Battey", "Mudcat Grant"], correct: 0 },
        { question: "Who was the center fielder for the 1990 Reds World Series champions?", answers: ["Chris Sabo", "Barry Larkin", "Randy Myers", "Jose Rijo"], correct: 0 },
        { question: "Which center fielder won the 1975 NL MVP?", answers: ["Joe Torre", "Steve Garvey", "Ron Cey", "Don Sutton"], correct: 0 },
        { question: "Who was the first center fielder to win five Gold Gloves?", answers: ["Willie Mays", "Ken Griffey Jr.", "Andruw Jones", "Mike Trout"], correct: 0 },
        { question: "Which center fielder hit .340 in 1959?", answers: ["Nellie Fox", "Ron Hansen", "Luis Aparicio", "Harvey Kuenn"], correct: 0 },
        { question: "Who won the 2007 NL MVP?", answers: ["Jimmy Rollins", "Chase Utley", "Ryan Howard", "Albert Pujols"], correct: 0 },
        { question: "Which center fielder was the 1957 AL MVP?", answers: ["Ted Williams", "Mickey Mantle", "Yogi Berra", "Enos Slaughter"], correct: 0 },
        { question: "Who was the center fielder for the 1986 Red Sox World Series champions?", answers: ["Jim Rice", "Wade Boggs", "Bill Buckner", "Roger Clemens"], correct: 0 },
        { question: "Which center fielder won the 1992 AL MVP?", answers: ["Dennis Eckersley", "Roberto Alomar", "Cal Ripken Jr.", "Frank Thomas"], correct: 0 },
        { question: "Who was the first center fielder to hit 200 home runs?", answers: ["Willie Mays", "Ken Griffey Jr.", "Mickey Mantle", "Mike Trout"], correct: 0 },
        { question: "Which center fielder batted .324 in 1936?", answers: ["Lou Gehrig", "Bill Dickey", "Joe DiMaggio", "Benny Goodman"], correct: 0 },
        { question: "Who won the 2003 NL MVP?", answers: ["Barry Bonds", "Albert Pujols", "Jeff Bagwell", "Scott Rolen"], correct: 0 },
        { question: "Which center fielder was the 1962 AL MVP?", answers: ["Frank Malzone", "Dick Howser", "Ron Hansen", "Norm Cash"], correct: 0 }
    ],
    "RF": [
        { question: "Which right fielder hit 73 home runs in 2001?", answers: ["Barry Bonds", "Mark McGwire", "Sammy Sosa", "Aaron Judge"], correct: 0 },
        { question: "Which right fielder won the 2017 AL MVP with 52 home runs?", answers: ["Aaron Judge", "Giancarlo Stanton", "Jose Altuve", "Mookie Betts"], correct: 0 },
        { question: "Which right fielder collected exactly 3,000 hits in his final at-bat?", answers: ["Roberto Clemente", "Hank Aaron", "Al Kaline", "Tony Gwynn"], correct: 0 },
        { question: "Which right fielder won 13 Gold Glove Awards?", answers: ["Roberto Clemente", "Al Kaline", "Ichiro Suzuki", "Dwight Evans"], correct: 0 },
        { question: "Who hit 755 home runs?", answers: ["Hank Aaron", "Babe Ruth", "Barry Bonds", "Willie Mays"], correct: 0 },
        { question: "Which right fielder batted .394 in 1994?", answers: ["Tony Gwynn", "Jeff Bagwell", "Frank Thomas", "Albert Belle"], correct: 0 },
        { question: "Who won eight batting titles?", answers: ["Tony Gwynn", "Honus Wagner", "Rod Carew", "Ty Cobb"], correct: 0 },
        { question: "Which right fielder hit 60 home runs in 1927?", answers: ["Babe Ruth", "Lou Gehrig", "Jimmie Foxx", "Hack Wilson"], correct: 0 },
        { question: "Who was the 1999 NL MVP?", answers: ["Chipper Jones", "Jeff Bagwell", "Sammy Sosa", "Larry Walker"], correct: 0 },
        { question: "Which right fielder won the 1992 AL MVP?", answers: ["Dennis Eckersley", "Kirby Puckett", "Roberto Alomar", "Frank Thomas"], correct: 0 },
        { question: "Who hit .424 in 1924?", answers: ["Rogers Hornsby", "Babe Ruth", "Harry Heilmann", "Ty Cobb"], correct: 0 },
        { question: "Which right fielder was the 1997 NL MVP?", answers: ["Larry Walker", "Mike Piazza", "Jeff Bagwell", "Craig Biggio"], correct: 0 },
        { question: "Who won 10 Gold Gloves in right field?", answers: ["Roberto Clemente", "Ichiro Suzuki", "Dwight Evans", "Dave Winfield"], correct: 0 },
        { question: "Which right fielder batted .376 in 1937?", answers: ["Joe Medwick", "Joe DiMaggio", "Charlie Gehringer", "Lou Gehrig"], correct: 0 },
        { question: "Who was the 2018 AL MVP?", answers: ["Mookie Betts", "Mike Trout", "Jose Ramirez", "J.D. Martinez"], correct: 0 },
        { question: "Which right fielder hit 54 home runs in 1920?", answers: ["Babe Ruth", "Rogers Hornsby", "George Sisler", "Tris Speaker"], correct: 0 },
        { question: "Who won the 1982 NL MVP?", answers: ["Dale Murphy", "Lonnie Smith", "Pedro Guerrero", "Al Oliver"], correct: 0 },
        { question: "Which right fielder batted .398 in 1930?", answers: ["Bill Terry", "Chuck Klein", "Hack Wilson", "Lefty O'Doul"], correct: 0 },
        { question: "Who was the 1950 AL MVP?", answers: ["Phil Rizzuto", "Yogi Berra", "Billy Goodman", "George Kell"], correct: 0 },
        { question: "Which right fielder was the first to hit 300 home runs?", answers: ["Hank Aaron", "Babe Ruth", "Mel Ott", "Frank Robinson"], correct: 0 },
        { question: "Which right fielder won the 1983 AL MVP?", answers: ["Cal Ripken Jr.", "Eddie Murray", "Rick Dempsey", "Jim Palmer"], correct: 0 },
        { question: "Who was the right fielder for the 1996 Yankees World Series champions?", answers: ["Paul O'Neill", "Derek Jeter", "Bernie Williams", "Tino Martinez"], correct: 0 },
        { question: "Which right fielder won the 1978 AL MVP?", answers: ["Jim Rice", "Fred Lynn", "Carl Yastrzemski", "Dwight Evans"], correct: 0 },
        { question: "Who was the first right fielder to hit 500 home runs?", answers: ["Hank Aaron", "Babe Ruth", "Barry Bonds", "Willie Mays"], correct: 0 },
        { question: "Which right fielder batted .349 in 1953?", answers: ["Roy Campanella", "Duke Snider", "Carl Furillo", "Ralph Branca"], correct: 0 },
        { question: "Who won the 2004 NL MVP?", answers: ["Barry Bonds", "Jeff Kent", "Scott Rolen", "Albert Pujols"], correct: 0 },
        { question: "Which right fielder was the 1969 AL MVP?", answers: ["Harmon Killebrew", "Tony Oliva", "Rod Carew", "Reggie Jackson"], correct: 0 },
        { question: "Who was the right fielder for the 1984 Tigers World Series champions?", answers: ["Kirk Gibson", "Alan Trammell", "Lou Whitaker", "Jack Morris"], correct: 0 },
        { question: "Which right fielder won the 1996 AL MVP?", answers: ["Juan Gonzalez", "Alex Rodriguez", "Kenny Lofton", "Paul O'Neill"], correct: 0 },
        { question: "Who was the first right fielder to win the AL batting title?", answers: ["George Sisler", "Ty Cobb", "Tris Speaker", "Babe Ruth"], correct: 0 },
        { question: "Which right fielder hit .320 in 1941?", answers: ["Ted Williams", "Joe DiMaggio", "Stan Musial", "Charlie Keller"], correct: 0 },
        { question: "Who won the 2011 AL MVP?", answers: ["Justin Verlander", "Miguel Cabrera", "Jacoby Ellsbury", "Adrian Gonzalez"], correct: 0 },
        { question: "Which right fielder was the 1959 AL MVP?", answers: ["Nellie Fox", "Ron Hansen", "Luis Aparicio", "Rocky Colavito"], correct: 0 },
        { question: "Who was the right fielder for the 1979 Pirates World Series champions?", answers: ["Willie Stargell", "Dave Parker", "Bill Madlock", "Tim Foli"], correct: 0 },
        { question: "Which right fielder won the 1987 AL MVP?", answers: ["George Bell", "Don Mattingly", "Dave Winfield", "Rickey Henderson"], correct: 0 },
        { question: "Who was the first right fielder to hit 100 home runs?", answers: ["Hank Aaron", "Babe Ruth", "Mel Ott", "Frank Robinson"], correct: 0 },
        { question: "Which right fielder batted .302 in 1948?", answers: ["Stan Musial", "Ted Williams", "Lou Boudreau", "Tommy Henrich"], correct: 0 },
        { question: "Who won the 2000 NL MVP?", answers: ["Jeff Kent", "Barry Bonds", "Mark McGwire", "Sammy Sosa"], correct: 0 },
        { question: "Which right fielder was the 1965 AL MVP?", answers: ["Zoilo Versalles", "Tony Oliva", "Earl Battey", "Mudcat Grant"], correct: 0 },
        { question: "Who was the right fielder for the 1990 Reds World Series champions?", answers: ["Chris Sabo", "Barry Larkin", "Randy Myers", "Jose Rijo"], correct: 0 },
        { question: "Which right fielder won the 1975 NL MVP?", answers: ["Joe Torre", "Steve Garvey", "Ron Cey", "Don Sutton"], correct: 0 },
        { question: "Who was the first right fielder to win five Gold Gloves?", answers: ["Roberto Clemente", "Ichiro Suzuki", "Dwight Evans", "Dave Winfield"], correct: 0 },
        { question: "Which right fielder hit .340 in 1959?", answers: ["Nellie Fox", "Ron Hansen", "Luis Aparicio", "Harvey Kuenn"], correct: 0 },
        { question: "Who won the 2007 NL MVP?", answers: ["Jimmy Rollins", "Chase Utley", "Ryan Howard", "Albert Pujols"], correct: 0 },
        { question: "Which right fielder was the 1957 AL MVP?", answers: ["Ted Williams", "Mickey Mantle", "Yogi Berra", "Enos Slaughter"], correct: 0 },
        { question: "Who was the right fielder for the 1986 Red Sox World Series champions?", answers: ["Jim Rice", "Wade Boggs", "Bill Buckner", "Roger Clemens"], correct: 0 },
        { question: "Which right fielder won the 1992 AL MVP?", answers: ["Dennis Eckersley", "Roberto Alomar", "Cal Ripken Jr.", "Frank Thomas"], correct: 0 },
        { question: "Who was the first right fielder to hit 200 home runs?", answers: ["Hank Aaron", "Babe Ruth", "Mel Ott", "Frank Robinson"], correct: 0 },
        { question: "Which right fielder batted .324 in 1936?", answers: ["Lou Gehrig", "Bill Dickey", "Joe DiMaggio", "Benny Goodman"], correct: 0 },
        { question: "Who won the 2003 NL MVP?", answers: ["Barry Bonds", "Albert Pujols", "Jeff Bagwell", "Scott Rolen"], correct: 0 },
        { question: "Which right fielder was the 1962 AL MVP?", answers: ["Frank Malzone", "Dick Howser", "Ron Hansen", "Norm Cash"], correct: 0 }
    ],
    "DH": [
        { question: "Who was the first designated hitter in MLB history?", answers: ["Ron Blomberg", "Reggie Jackson", "Harold Baines", "Edgar Martinez"], correct: 0 },
        { question: "Which DH won two AL MVP awards with the Red Sox?", answers: ["David Ortiz", "Edgar Martinez", "Frank Thomas", "Jim Rice"], correct: 0 },
        { question: "Who hit the most home runs as a DH in career (485)?", answers: ["David Ortiz", "Frank Thomas", "Harold Baines", "Edgar Martinez"], correct: 0 },
        { question: "Which DH is the only two-way player to win MVP unanimously?", answers: ["Shohei Ohtani", "Babe Ruth", "Frank Thomas", "David Ortiz"], correct: 0 },
        { question: "Which DH retired with a .418 lifetime on-base percentage?", answers: ["Frank Thomas", "Edgar Martinez", "David Ortiz", "Harold Baines"], correct: 0 },
        { question: "Who won back-to-back AL MVP awards in 1993-1994?", answers: ["Frank Thomas", "Ken Griffey Jr.", "Albert Belle", "Mo Vaughn"], correct: 0 },
        { question: "Which DH won seven Silver Slugger Awards?", answers: ["Edgar Martinez", "David Ortiz", "Frank Thomas", "Jim Thome"], correct: 0 },
        { question: "Who hit .330 over 18 seasons?", answers: ["Edgar Martinez", "Paul Molitor", "Wade Boggs", "Tony Gwynn"], correct: 0 },
        { question: "Who won the 1984 AL MVP?", answers: ["Willie Hernandez", "Dave Winfield", "Cal Ripken Jr.", "Don Mattingly"], correct: 0 },
        { question: "Which DH hit 541 home runs in his career?", answers: ["Frank Thomas", "Jim Thome", "David Ortiz", "Manny Ramirez"], correct: 0 },
        { question: "Who was the 2013 World Series MVP?", answers: ["David Ortiz", "Koji Uehara", "Shane Victorino", "Dustin Pedroia"], correct: 0 },
        { question: "Which DH batted .353 in 1996?", answers: ["Alex Rodriguez", "Frank Thomas", "Mo Vaughn", "Edgar Martinez"], correct: 0 },
        { question: "Who won the 1987 AL MVP?", answers: ["George Bell", "Alan Trammell", "Mark McGwire", "Roger Clemens"], correct: 0 },
        { question: "Which DH hit 52 home runs in 1996?", answers: ["Mark McGwire", "Brady Anderson", "Ken Griffey Jr.", "Albert Belle"], correct: 0 },
        { question: "Who was the 2021 AL MVP?", answers: ["Shohei Ohtani", "Vladimir Guerrero Jr.", "Marcus Semien", "Aaron Judge"], correct: 0 },
        { question: "Which DH won the 1996 AL MVP?", answers: ["Juan Gonzalez", "Alex Rodriguez", "Ken Griffey Jr.", "Mo Vaughn"], correct: 0 },
        { question: "Who was the first DH to hit 40 home runs in a season?", answers: ["Harold Baines", "Frank Thomas", "Edgar Martinez", "David Ortiz"], correct: 0 },
        { question: "Which DH was the 1983 AL Rookie of the Year?", answers: ["Ron Kittle", "Cal Ripken Jr.", "Wade Boggs", "Rickey Henderson"], correct: 0 },
        { question: "Who was the DH for the 1977 Yankees World Series champions?", answers: ["Reggie Jackson", "Thurman Munson", "Chris Chambliss", "Lou Piniella"], correct: 0 },
        { question: "Which DH won the 1991 AL MVP?", answers: ["Cal Ripken Jr.", "Frank Thomas", "Cecil Fielder", "Jose Canseco"], correct: 0 },
        { question: "Which DH won the 1983 AL MVP?", answers: ["Cal Ripken Jr.", "Eddie Murray", "Rick Dempsey", "Jim Palmer"], correct: 0 },
        { question: "Who was the DH for the 1996 Yankees World Series champions?", answers: ["Paul O'Neill", "Derek Jeter", "Bernie Williams", "Tino Martinez"], correct: 0 },
        { question: "Which DH won the 1978 AL MVP?", answers: ["Jim Rice", "Fred Lynn", "Carl Yastrzemski", "Dwight Evans"], correct: 0 },
        { question: "Who was the first DH to hit 500 home runs?", answers: ["Frank Thomas", "Jim Thome", "David Ortiz", "Manny Ramirez"], correct: 0 },
        { question: "Which DH batted .349 in 1953?", answers: ["Roy Campanella", "Duke Snider", "Carl Furillo", "Ralph Branca"], correct: 0 },
        { question: "Who won the 2004 AL MVP?", answers: ["Vladimir Guerrero", "Ichiro Suzuki", "Manny Ramirez", "David Ortiz"], correct: 0 },
        { question: "Which DH was the 1969 AL MVP?", answers: ["Harmon Killebrew", "Tony Oliva", "Rod Carew", "Reggie Jackson"], correct: 0 },
        { question: "Who was the DH for the 1984 Tigers World Series champions?", answers: ["Kirk Gibson", "Alan Trammell", "Lou Whitaker", "Jack Morris"], correct: 0 },
        { question: "Which DH won the 1996 AL MVP?", answers: ["Juan Gonzalez", "Alex Rodriguez", "Kenny Lofton", "Paul O'Neill"], correct: 0 },
        { question: "Who was the first DH to win the AL batting title?", answers: ["George Sisler", "Ty Cobb", "Tris Speaker", "Babe Ruth"], correct: 0 },
        { question: "Which DH hit .320 in 1941?", answers: ["Ted Williams", "Joe DiMaggio", "Stan Musial", "Charlie Keller"], correct: 0 },
        { question: "Who won the 2011 AL MVP?", answers: ["Justin Verlander", "Miguel Cabrera", "Jacoby Ellsbury", "Adrian Gonzalez"], correct: 0 },
        { question: "Which DH was the 1959 AL MVP?", answers: ["Nellie Fox", "Ron Hansen", "Luis Aparicio", "Rocky Colavito"], correct: 0 },
        { question: "Who was the DH for the 1979 Pirates World Series champions?", answers: ["Willie Stargell", "Dave Parker", "Bill Madlock", "Tim Foli"], correct: 0 },
        { question: "Which DH won the 1987 AL MVP?", answers: ["George Bell", "Don Mattingly", "Dave Winfield", "Rickey Henderson"], correct: 0 },
        { question: "Who was the first DH to hit 100 home runs?", answers: ["Harold Baines", "Frank Thomas", "Edgar Martinez", "David Ortiz"], correct: 0 },
        { question: "Which DH batted .302 in 1948?", answers: ["Stan Musial", "Ted Williams", "Lou Boudreau", "Tommy Henrich"], correct: 0 },
        { question: "Who won the 2000 AL MVP?", answers: ["Jason Giambi", "Nomar Garciaparra", "Pedro Martinez", "Derek Jeter"], correct: 0 },
        { question: "Which DH was the 1965 AL MVP?", answers: ["Zoilo Versalles", "Tony Oliva", "Earl Battey", "Mudcat Grant"], correct: 0 },
        { question: "Who was the DH for the 1990 Reds World Series champions?", answers: ["Chris Sabo", "Barry Larkin", "Randy Myers", "Jose Rijo"], correct: 0 },
        { question: "Which DH won the 1975 AL MVP?", answers: ["Fred Lynn", "Jim Rice", "Carl Yastrzemski", "Dwight Evans"], correct: 0 },
        { question: "Who was the first DH to win five Silver Sluggers?", answers: ["Edgar Martinez", "David Ortiz", "Frank Thomas", "Jim Thome"], correct: 0 },
        { question: "Which DH hit .340 in 1959?", answers: ["Nellie Fox", "Ron Hansen", "Luis Aparicio", "Harvey Kuenn"], correct: 0 },
        { question: "Who won the 2007 AL MVP?", answers: ["Alex Rodriguez", "Magglio Ordonez", "Carlos Pena", "Vladimir Guerrero"], correct: 0 },
        { question: "Which DH was the 1957 AL MVP?", answers: ["Ted Williams", "Mickey Mantle", "Yogi Berra", "Enos Slaughter"], correct: 0 },
        { question: "Who was the DH for the 1986 Red Sox World Series champions?", answers: ["Jim Rice", "Wade Boggs", "Bill Buckner", "Roger Clemens"], correct: 0 },
        { question: "Which DH won the 1992 AL MVP?", answers: ["Dennis Eckersley", "Roberto Alomar", "Cal Ripken Jr.", "Frank Thomas"], correct: 0 },
        { question: "Who was the first DH to hit 200 home runs?", answers: ["Harold Baines", "Frank Thomas", "Edgar Martinez", "David Ortiz"], correct: 0 },
        { question: "Which DH batted .324 in 1936?", answers: ["Lou Gehrig", "Bill Dickey", "Joe DiMaggio", "Benny Goodman"], correct: 0 },
        { question: "Who won the 2003 AL MVP?", answers: ["Alex Rodriguez", "Carlos Delgado", "Miguel Tejada", "Vladimir Guerrero"], correct: 0 },
        { question: "Which DH was the 1962 AL MVP?", answers: ["Frank Malzone", "Dick Howser", "Ron Hansen", "Norm Cash"], correct: 0 }
    ]
};
