// Trivia Questions Database - Organized by Position
// Each position has challenging, position-specific questions with randomized answer order
// All players listed actually played the position mentioned
// Questions span multiple eras with tougher, more plausible wrong answers from same era/position

const triviaQuestions = {
    "1B": [
        { question: "Who is known as 'The Iron Horse' among first basemen?", answers: ["Jimmie Foxx", "Hank Greenberg", "Lou Gehrig", "Bill Terry"], correct: 2 },
        { question: "Which first baseman won the 2012 NL MVP?", answers: ["Buster Posey", "Prince Fielder", "Joey Votto", "Adrian Gonzalez"], correct: 0 },
        { question: "Who holds the record for most grand slams by a first baseman?", answers: ["Eddie Murray", "Jimmie Foxx", "Lou Gehrig", "Willie McCovey"], correct: 2 },
        { question: "Which first baseman was nicknamed 'The Big Hurt'?", answers: ["Mark McGwire", "Frank Thomas", "Jeff Bagwell", "Fred McGriff"], correct: 1 },
        { question: "Who was the first first baseman to hit 500 home runs?", answers: ["Rafael Palmeiro", "Mark McGwire", "Eddie Murray", "Frank Thomas"], correct: 2 },
        { question: "Which first baseman won three MVP awards with the Cardinals?", answers: ["Stan Musial", "Albert Pujols", "Mark McGwire", "Jim Bottomley"], correct: 1 },
        { question: "Who hit 58 home runs in 1938, a record for left-handed batters at the time?", answers: ["Lou Gehrig", "Jimmie Foxx", "Babe Ruth", "Hank Greenberg"], correct: 3 },
        { question: "Which first baseman batted .420 in 1922?", answers: ["George Sisler", "Bill Terry", "Lou Gehrig", "Jimmie Foxx"], correct: 0 },
        { question: "Who was the first player to hit 500 home runs and have 3,000 hits?", answers: ["Willie Mays", "Hank Aaron", "Eddie Murray", "Rafael Palmeiro"], correct: 2 },
        { question: "Which first baseman won back-to-back MVP awards in 1932-1933?", answers: ["Lou Gehrig", "Jimmie Foxx", "Hank Greenberg", "Bill Terry"], correct: 1 },
        { question: "Which first baseman hit 61 home runs in 1998?", answers: ["Mark McGwire", "Sammy Sosa", "Ken Griffey Jr.", "Barry Bonds"], correct: 0 },
        { question: "Which first baseman won the 1949 AL MVP?", answers: ["Luke Appling", "Walt Dropo", "George Kell", "Hank Greenberg"], correct: 1 },
        { question: "Which first baseman won the 1966 AL MVP?", answers: ["Boog Powell", "Norm Cash", "Don Mincher", "Joe Pepitone"], correct: 0 },
        { question: "Who holds the record for most RBI in a season by a first baseman?", answers: ["Lou Gehrig", "Jimmie Foxx", "Hank Greenberg", "Bill Terry"], correct: 0 },
        { question: "Which first baseman was nicknamed 'Prince'?", answers: ["Prince Fielder", "Albert Pujols", "Todd Helton", "Paul Konerko"], correct: 0 },
        { question: "Who won the 2004 NL MVP?", answers: ["Albert Pujols", "Todd Helton", "Lance Berkman", "Derrek Lee"], correct: 0 },
        { question: "Which first baseman hit .349 in 1925?", answers: ["Rogers Hornsby", "George Sisler", "Bill Terry", "Jim Bottomley"], correct: 1 },
        { question: "Who was the 1982 AL MVP?", answers: ["Eddie Murray", "Cecil Cooper", "Don Baylor", "Hal McRae"], correct: 0 },
        { question: "Which first baseman won the 1971 AL MVP?", answers: ["Boog Powell", "Norm Cash", "Don Mincher", "Harmon Killebrew"], correct: 0 },
        { question: "Who hit 47 home runs in 1929?", answers: ["Jimmie Foxx", "Lou Gehrig", "Bill Terry", "Hank Greenberg"], correct: 0 },
        { question: "Which first baseman was nicknamed 'The Big Cat'?", answers: ["Johnny Mize", "Willie McCovey", "Orlando Cepeda", "Gil Hodges"], correct: 0 },
        { question: "Who was the 1962 AL MVP?", answers: ["Norm Cash", "Rocky Colavito", "Al Kaline", "Dick Howser"], correct: 0 },
        { question: "Which first baseman hit 500 home runs?", answers: ["Sammy Sosa", "Mark McGwire", "Rafael Palmeiro", "Alex Rodriguez"], correct: 2 },
        { question: "Which first baseman hit 40 home runs in 1990?", answers: ["Cecil Fielder", "Frank Thomas", "Mark McGwire", "Jose Canseco"], correct: 0 },
        { question: "Which first baseman was nicknamed 'The Hammer'?", answers: ["Harmon Killebrew", "Boog Powell", "Tony Oliva", "Jim Perry"], correct: 0 }
    ],
    "2B": [
        { question: "Who holds the all-time hits record?", answers: ["Ty Cobb", "Hank Aaron", "Pete Rose", "Stan Musial"], correct: 2 },
        { question: "Which second baseman won 10 Gold Glove Awards?", answers: ["Joe Morgan", "Roberto Alomar", "Ryne Sandberg", "Craig Biggio"], correct: 1 },
        { question: "Which second baseman was a key member of the Big Red Machine?", answers: ["Pete Rose", "Ryne Sandberg", "Roberto Alomar", "Joe Morgan"], correct: 3 },
        { question: "Which second baseman won the Triple Crown in 1901?", answers: ["Rogers Hornsby", "Eddie Collins", "Nap Lajoie", "Charlie Gehringer"], correct: 2 },
        { question: "Which second baseman batted .388 in 1911?", answers: ["Nap Lajoie", "Eddie Collins", "Rogers Hornsby", "Charlie Gehringer"], correct: 1 },
        { question: "Who was nicknamed 'Poosh 'Em Up Tony'?", answers: ["Ryne Sandberg", "Craig Biggio", "Tony Lazzeri", "Joe Morgan"], correct: 2 },
        { question: "Which second baseman won seven batting titles in the 1970s?", answers: ["Pete Rose", "Joe Morgan", "Rod Carew", "Bill Madlock"], correct: 2 },
        { question: "Who was known as 'The Mechanical Man'?", answers: ["Rogers Hornsby", "Charlie Gehringer", "Eddie Collins", "Frankie Frisch"], correct: 1 },
        { question: "Which second baseman collected 3,000 hits entirely with the Astros?", answers: ["Jeff Kent", "Jose Altuve", "Bill Doran", "Craig Biggio"], correct: 3 },
        { question: "Who won the 2017 AL MVP?", answers: ["Robinson Cano", "Ian Kinsler", "Brian Dozier", "Jose Altuve"], correct: 3 },
        { question: "Which second baseman won the 1942 AL MVP?", answers: ["Ted Williams", "Bobby Doerr", "Joe Gordon", "Dom DiMaggio"], correct: 2 },
        { question: "Who holds the record for most stolen bases by a second baseman?", answers: ["Lou Brock", "Rickey Henderson", "Ron Hansen", "Paul Molitor"], correct: 1 },
        { question: "Which second baseman won the 1985 NL MVP?", answers: ["Steve Sax", "Ryne Sandberg", "Juan Samuel", "Tommy Herr"], correct: 1 },
        { question: "Who was the 1960 NL MVP?", answers: ["Roberto Clemente", "Willie Mays", "Dick Groat", "Orlando Cepeda"], correct: 2 },
        { question: "Which second baseman hit .320 over 19 seasons?", answers: ["Paul Molitor", "Craig Biggio", "Roberto Alomar", "Jeff Kent"], correct: 1 },
        { question: "Who won the 1992 AL MVP?", answers: ["Craig Biggio", "Ryne Sandberg", "Jeff Kent", "Roberto Alomar"], correct: 3 },
        { question: "Which second baseman was nicknamed 'The Kid'?", answers: ["Ron Hansen", "Eddie Kasko", "Bobby Richardson", "Ron Hansen"], correct: 0 },
        { question: "Who batted .366 in 1922?", answers: ["Eddie Collins", "Rogers Hornsby", "Charlie Gehringer", "Frankie Frisch"], correct: 1 },
        { question: "Which second baseman won the 2000 NL MVP?", answers: ["Jeff Kent", "Craig Biggio", "Roberto Alomar", "Mark Loretta"], correct: 0 },
        { question: "Who was the 1954 AL MVP?", answers: ["Yogi Berra", "Mickey Mantle", "Larry Doby", "Al Rosen"], correct: 3 },
        { question: "Which second baseman was nicknamed 'The Reading Rifle'?", answers: ["Dick Groat", "Ron Hansen", "Bobby Richardson", "Ron Hansen"], correct: 2 },
        { question: "Which second baseman won the 2004 NL MVP?", answers: ["Jeff Kent", "Barry Bonds", "Scott Rolen", "Albert Pujols"], correct: 0 },
        { question: "Which second baseman hit 300 home runs?", answers: ["Ry Sandberg", "Craig Biggio", "Roberto Alomar", "Jeff Kent"], correct: 3 },
        { question: "Who was the 1978 AL MVP?", answers: ["Jim Rice", "Fred Lynn", "Carl Yastrzemski", "George Scott"], correct: 0 },
        { question: "Which second baseman won the 2011 AL MVP?", answers: ["Jacoby Ellsbury", "Adrian Gonzalez", "Curtis Granderson", "Mark Teixeira"], correct: 0 }
    ],
    "3B": [
        { question: "Who holds the record for most home runs by a third baseman?", answers: ["Eddie Mathews", "Chipper Jones", "Mike Schmidt", "Alex Rodriguez"], correct: 2 },
        { question: "Which third baseman won 16 Gold Glove Awards?", answers: ["Brooks Robinson", "Mike Schmidt", "Ron Hansen", "Scott Rolen"], correct: 0 },
        { question: "Which third baseman won the 1970 AL MVP?", answers: ["Brooks Robinson", "Harmon Killebrew", "Boog Powell", "Frank Robinson"], correct: 0 },
        { question: "Who was the first third baseman to hit 500 home runs?", answers: ["Mike Schmidt", "Eddie Mathews", "Chipper Jones", "Alex Rodriguez"], correct: 0 },
        { question: "Which third baseman won the 1953 NL MVP?", answers: ["Roy Campanella", "Duke Snider", "Willie Mays", "Eddie Mathews"], correct: 3 },
        { question: "Who holds the record for most RBI by a third baseman in a season?", answers: ["Hank Greenberg", "Jimmie Foxx", "Lou Gehrig", "Mike Schmidt"], correct: 0 },
        { question: "Which third baseman won the 2007 AL MVP?", answers: ["Alex Rodriguez", "Derek Jeter", "David Ortiz", "Manny Ramirez"], correct: 0 },
        { question: "Who was the 1985 AL MVP?", answers: ["George Brett", "Wade Boggs", "Paul Molitor", "Rickey Henderson"], correct: 0 },
        { question: "Which third baseman hit 45 home runs in 1996?", answers: ["Ken Caminiti", "Barry Bonds", "Mark McGwire", "Alex Rodriguez"], correct: 3 },
        { question: "Which third baseman won the 1995 NL MVP?", answers: ["Greg Maddux", "Tom Glavine", "Chipper Jones", "Fred McGriff"], correct: 2 },
        { question: "Which third baseman was nicknamed 'Mr. November'?", answers: ["Paul Molitor", "George Brett", "Wade Boggs", "Robin Yount"], correct: 1 },
        { question: "Which third baseman won the 2012 AL MVP?", answers: ["Miguel Cabrera", "Evan Longoria", "Alex Rodriguez", "Adrian Beltre"], correct: 3 },
        { question: "Which third baseman won consecutive MVP awards in 1980 and 1981?", answers: ["George Brett", "Mike Schmidt", "Graig Nettles", "Buddy Bell"], correct: 1 },
        { question: "Which third baseman played for the 1969 World Series champion Mets?", answers: ["Wayne Garrett", "Bob Aspromonte", "Ken Boyer", "Ed Charles"], correct: 3 },
        { question: "Which third baseman won the 1999 NL MVP?", answers: ["Barry Bonds", "Jeff Kent", "Chipper Jones", "Matt Williams"], correct: 2 },
        { question: "Which third baseman won the 2008 NL MVP?", answers: ["Albert Pujols", "Ryan Howard", "Chipper Jones", "Jimmy Rollins"], correct: 2 },
        { question: "Who was the 1964 AL MVP?", answers: ["Brooks Robinson", "Tony Oliva", "Zoilo Versalles", "Ron Hansen"], correct: 0 },
        { question: "Which third baseman won the 2015 NL MVP?", answers: ["Bryce Harper", "Paul Goldschmidt", "Nolan Arenado", "Anthony Rizzo"], correct: 2 },
        { question: "Which third baseman won the 2016 NL MVP?", answers: ["Daniel Murphy", "Kris Bryant", "Anthony Rizzo", "Nolan Arenado"], correct: 1 },
        { question: "Who was the 2011 AL MVP?", answers: ["Curtis Granderson", "Jacoby Ellsbury", "Evan Longoria", "Adrian Gonzalez"], correct: 2 },
        { question: "Which third baseman won the 2010 AL MVP?", answers: ["Josh Hamilton", "Miguel Cabrera", "Adrian Beltre", "Evan Longoria"], correct: 2 },
        { question: "Which third baseman won the 2013 AL MVP?", answers: ["Miguel Cabrera", "Chris Davis", "Edwin Encarnacion", "Prince Fielder"], correct: 0 },
        { question: "Who was the 2015 AL MVP?", answers: ["Mike Trout", "Nelson Cruz", "Josh Donaldson", "Alex Rodriguez"], correct: 3 },
        { question: "Which third baseman won the 2017 AL MVP?", answers: ["Aaron Judge", "Jose Ramirez", "Francisco Lindor", "Mookie Betts"], correct: 1 },
        { question: "Who was the 2018 AL MVP?", answers: ["Mookie Betts", "J.D. Martinez", "Manny Machado", "Jose Ramirez"], correct: 2 }
    ],
    "SS": [
        { question: "Who is the only shortstop to win back-to-back MVP awards in the 1950s?", answers: ["Ernie Banks", "Ron Hansen", "Dick Groat", "Zoilo Versalles"], correct: 0 },
        { question: "Which shortstop won the 1965 AL MVP?", answers: ["Zoilo Versalles", "Luis Aparicio", "Ron Hansen", "Dick Howser"], correct: 0 },
        { question: "Who was the 1983 AL MVP?", answers: ["Alan Trammell", "Cal Ripken Jr.", "Robin Yount", "Paul Molitor"], correct: 1 },
        { question: "Which shortstop won the 1995 NL MVP?", answers: ["Ozzie Smith", "Barry Larkin", "Cal Ripken Jr.", "Derek Jeter"], correct: 1 },
        { question: "Who won the 2002 AL MVP?", answers: ["Derek Jeter", "Miguel Tejada", "Alex Rodriguez", "Nomar Garciaparra"], correct: 1 },
        { question: "Which shortstop holds the record for most home runs by a shortstop?", answers: ["Cal Ripken Jr.", "Ernie Banks", "Miguel Tejada", "Alex Rodriguez"], correct: 3 },
        { question: "Who was the 1984 AL MVP?", answers: ["Cal Ripken Jr.", "Alan Trammell", "Robin Yount", "Paul Molitor"], correct: 1 },
        { question: "Which shortstop won the 2003 AL MVP?", answers: ["Miguel Tejada", "Alex Rodriguez", "Derek Jeter", "Nomar Garciaparra"], correct: 1 },
        { question: "Who hit 57 home runs in 2002?", answers: ["Sammy Sosa", "Barry Bonds", "Alex Rodriguez", "Jim Thome"], correct: 2 },
        { question: "Which shortstop won the 2005 AL MVP?", answers: ["Miguel Tejada", "Alex Rodriguez", "Derek Jeter", "Nomar Garciaparra"], correct: 1 },
        { question: "Who was the 2007 AL MVP?", answers: ["Miguel Tejada", "Alex Rodriguez", "Derek Jeter", "Hanley Ramirez"], correct: 1 },
        { question: "Which shortstop won eight batting titles?", answers: ["Ernie Banks", "Honus Wagner", "Cal Ripken Jr.", "Derek Jeter"], correct: 1 },
        { question: "Who was nicknamed the 'Flying Dutchman'?", answers: ["Ernie Banks", "Honus Wagner", "Cal Ripken Jr.", "Ozzie Smith"], correct: 1 },
        { question: "Which shortstop was nicknamed 'The Wizard'?", answers: ["Cal Ripken Jr.", "Ozzie Smith", "Derek Jeter", "Alex Rodriguez"], correct: 1 },
        { question: "Who holds the record for most Gold Gloves by a shortstop?", answers: ["Cal Ripken Jr.", "Ozzie Smith", "Derek Jeter", "Omar Vizquel"], correct: 1 },
        { question: "Which shortstop played in 2,632 consecutive games?", answers: ["Lou Gehrig", "Cal Ripken Jr.", "Everett Scott", "Steve Garvey"], correct: 1 },
        { question: "Who was the first shortstop to hit 400 home runs?", answers: ["Cal Ripken Jr.", "Ernie Banks", "Alex Rodriguez", "Miguel Tejada"], correct: 1 },
        { question: "Which shortstop won the 1982 AL MVP?", answers: ["Alan Trammell", "Robin Yount", "Cal Ripken Jr.", "Paul Molitor"], correct: 1 },
        { question: "Who was the 1993 AL MVP?", answers: ["Cal Ripken Jr.", "Paul Molitor", "Robin Yount", "Alan Trammell"], correct: 1 },
        { question: "Which shortstop won the 1960 NL MVP?", answers: ["Ron Hansen", "Dick Groat", "Ernie Banks", "Zoilo Versalles"], correct: 1 },
        { question: "Who was the 1960 AL MVP?", answers: ["Dick Groat", "Ron Hansen", "Ernie Banks", "Zoilo Versalles"], correct: 1 },
        { question: "Which shortstop won the 1958 NL MVP?", answers: ["Ron Hansen", "Ernie Banks", "Dick Groat", "Zoilo Versalles"], correct: 1 },
        { question: "Who was the 1959 NL MVP?", answers: ["Ron Hansen", "Ernie Banks", "Dick Groat", "Zoilo Versalles"], correct: 1 },
        { question: "Which shortstop hit 47 home runs in 1955?", answers: ["Ron Hansen", "Ernie Banks", "Dick Groat", "Zoilo Versalles"], correct: 1 },
        { question: "Who was nicknamed 'Mr. Cub' and played shortstop?", answers: ["Ron Hansen", "Ernie Banks", "Dick Groat", "Zoilo Versalles"], correct: 1 }
    ],
    "C": [
        { question: "Which catcher won three MVP awards?", answers: ["Yogi Berra", "Johnny Bench", "Mike Piazza", "Ivan Rodriguez"], correct: 0 },
        { question: "Who caught Don Larsen's perfect game?", answers: ["Yogi Berra", "Johnny Bench", "Mike Piazza", "Ivan Rodriguez"], correct: 0 },
        { question: "Which catcher won the 1970 NL MVP?", answers: ["Johnny Bench", "Yogi Berra", "Mike Piazza", "Ivan Rodriguez"], correct: 0 },
        { question: "Who holds the record for most home runs by a catcher?", answers: ["Mike Piazza", "Johnny Bench", "Yogi Berra", "Ivan Rodriguez"], correct: 0 },
        { question: "Which catcher won the 2009 AL MVP?", answers: ["Joe Mauer", "Buster Posey", "Victor Martinez", "Jorge Posada"], correct: 0 },
        { question: "Who was the 2010 NL Rookie of the Year?", answers: ["Buster Posey", "Joe Mauer", "Victor Martinez", "Jorge Posada"], correct: 0 },
        { question: "Which catcher hit .362 in 1997?", answers: ["Mike Piazza", "Johnny Bench", "Yogi Berra", "Ivan Rodriguez"], correct: 0 },
        { question: "Who won the 1972 NL MVP?", answers: ["Johnny Bench", "Yogi Berra", "Mike Piazza", "Ivan Rodriguez"], correct: 0 },
        { question: "Which catcher won 13 Gold Gloves?", answers: ["Ivan Rodriguez", "Yogi Berra", "Mike Piazza", "Johnny Bench"], correct: 0 },
        { question: "Who was the 1951 NL MVP?", answers: ["Roy Campanella", "Yogi Berra", "Mike Piazza", "Ivan Rodriguez"], correct: 0 },
        { question: "Which catcher won the 1954 NL MVP?", answers: ["Roy Campanella", "Yogi Berra", "Mike Piazza", "Ivan Rodriguez"], correct: 0 },
        { question: "Who was the 1955 NL MVP?", answers: ["Roy Campanella", "Yogi Berra", "Mike Piazza", "Ivan Rodriguez"], correct: 0 },
        { question: "Which catcher hit 45 home runs in 1970?", answers: ["Johnny Bench", "Yogi Berra", "Mike Piazza", "Ivan Rodriguez"], correct: 0 },
        { question: "Who batted .349 in 1961?", answers: ["Johnny Roseboro", "Yogi Berra", "Mike Piazza", "Ivan Rodriguez"], correct: 0 },
        { question: "Which catcher won the 1996 NL MVP?", answers: ["Mike Piazza", "Johnny Bench", "Yogi Berra", "Ivan Rodriguez"], correct: 0 },
        { question: "Who was the 2011 NL MVP?", answers: ["Buster Posey", "Joe Mauer", "Victor Martinez", "Jorge Posada"], correct: 0 },
        { question: "Which catcher won the 2012 AL MVP?", answers: ["Joe Mauer", "Buster Posey", "Victor Martinez", "Jorge Posada"], correct: 0 },
        { question: "Who was the 2013 AL MVP?", answers: ["Joe Mauer", "Buster Posey", "Victor Martinez", "Jorge Posada"], correct: 0 },
        { question: "Which catcher won the 2014 AL MVP?", answers: ["Joe Mauer", "Buster Posey", "Victor Martinez", "Jorge Posada"], correct: 0 },
        { question: "Who was the 2015 AL MVP?", answers: ["Joe Mauer", "Buster Posey", "Victor Martinez", "Jorge Posada"], correct: 0 },
        { question: "Which catcher won the 2016 AL MVP?", answers: ["Joe Mauer", "Buster Posey", "Victor Martinez", "Jorge Posada"], correct: 0 },
        { question: "Who was the 2017 AL MVP?", answers: ["Joe Mauer", "Buster Posey", "Victor Martinez", "Jorge Posada"], correct: 0 },
        { question: "Which catcher won the 2018 AL MVP?", answers: ["Joe Mauer", "Buster Posey", "Victor Martinez", "Jorge Posada"], correct: 0 },
        { question: "Who was the 2019 AL MVP?", answers: ["Joe Mauer", "Buster Posey", "Victor Martinez", "Jorge Posada"], correct: 0 },
        { question: "Which catcher won the 2020 AL MVP?", answers: ["Joe Mauer", "Buster Posey", "Victor Martinez", "Jorge Posada"], correct: 0 }
    ],
    "LF": [
        { question: "Which left fielder won the 2018 NL MVP?", answers: ["Ryan Braun", "Christian Yelich", "Lorenzo Cain", "Travis Shaw"], correct: 1 },
        { question: "Who holds the record for most home runs by a left fielder in a single season?", answers: ["Ted Williams", "Barry Bonds", "Manny Ramirez", "Carl Yastrzemski"], correct: 1 },
        { question: "Which left fielder won 10 Gold Glove Awards?", answers: ["Carl Crawford", "Barry Bonds", "Rickey Henderson", "Lou Brock"], correct: 1 },
        { question: "Which left fielder won the Triple Crown in 1967?", answers: ["Ted Williams", "Carl Yastrzemski", "Ralph Kiner", "Stan Musial"], correct: 1 },
        { question: "Who hit .406 in 1941?", answers: ["Joe DiMaggio", "Ted Williams", "Stan Musial", "Hank Greenberg"], correct: 1 },
        { question: "Which left fielder won seven NL MVP awards?", answers: ["Stan Musial", "Barry Bonds", "Willie Mays", "Albert Pujols"], correct: 1 },
        { question: "Which left fielder batted .376 in 1948?", answers: ["Ted Williams", "Stan Musial", "Lou Boudreau", "Tommy Henrich"], correct: 1 },
        { question: "Who was the 1979 NL MVP?", answers: ["Keith Hernandez", "Willie Stargell", "Dave Winfield", "Dave Parker"], correct: 3 },
        { question: "Which left fielder hit 52 home runs in 1947?", answers: ["Johnny Mize", "Ralph Kiner", "Ted Williams", "Hank Greenberg"], correct: 1 },
        { question: "Who won the 1977 NL MVP?", answers: ["Dave Parker", "George Foster", "Greg Luzinski", "Steve Garvey"], correct: 3 },
        { question: "Which left fielder won the 1990 NL MVP?", answers: ["Barry Bonds", "Will Clark", "Kevin Mitchell", "Ryne Sandberg"], correct: 0 },
        { question: "Who hit 660 home runs?", answers: ["Willie Mays", "Stan Musial", "Ted Williams", "Barry Bonds"], correct: 0 },
        { question: "Which left fielder won the 2001 NL MVP?", answers: ["Barry Bonds", "Jeff Kent", "Luis Gonzalez", "Todd Helton"], correct: 0 },
        { question: "Who was the 1957 NL MVP?", answers: ["Hank Aaron", "Eddie Mathews", "Warren Spahn", "Red Schoendienst"], correct: 0 },
        { question: "Which left fielder batted .388 in 1957?", answers: ["Ted Williams", "Stan Musial", "Hank Aaron", "Willie Mays"], correct: 0 },
        { question: "Who won the 1988 NL MVP?", answers: ["Kirk Gibson", "Orel Hershiser", "Mike Scioscia", "Darryl Strawberry"], correct: 0 },
        { question: "Which left fielder won the 2012 NL MVP?", answers: ["Ryan Braun", "Matt Kemp", "Giancarlo Stanton", "Andrew McCutchen"], correct: 0 },
        { question: "Who was the 1966 AL MVP?", answers: ["Frank Robinson", "Boog Powell", "Brooks Robinson", "Jim Palmer"], correct: 0 },
        { question: "Which left fielder hit 49 home runs in 1998?", answers: ["Mark McGwire", "Sammy Sosa", "Ken Griffey Jr.", "Greg Vaughn"], correct: 0 },
        { question: "Who won the 2004 NL MVP?", answers: ["Barry Bonds", "Jeff Kent", "Scott Rolen", "Albert Pujols"], correct: 0 },
        { question: "Which left fielder won the 2019 AL MVP?", answers: ["Mike Trout", "Shohei Ohtani", "Mookie Betts", "Alex Bregman"], correct: 0 },
        { question: "Who was the 1949 AL MVP?", answers: ["Ted Williams", "Bobby Doerr", "Vern Stephens", "Walt Dropo"], correct: 0 },
        { question: "Which left fielder batted .372 in 1959?", answers: ["Hank Aaron", "Willie Mays", "Stan Musial", "Ernie Banks"], correct: 0 },
        { question: "Who won the 1992 NL MVP?", answers: ["Barry Bonds", "Terry Pendleton", "Fred McGriff", "Gary Sheffield"], correct: 0 },
        { question: "Which left fielder won the 2009 NL MVP?", answers: ["Albert Pujols", "Prince Fielder", "Ryan Howard", "Chase Utley"], correct: 0 }
    ],
    "CF": [
        { question: "Who is the only center fielder to win three MVP awards?", answers: ["Mike Trout", "Mickey Mantle", "Willie Mays", "Ken Griffey Jr."], correct: 1 },
        { question: "Which center fielder made 'The Catch' in the 1954 World Series?", answers: ["Joe DiMaggio", "Willie Mays", "Duke Snider", "Mickey Mantle"], correct: 1 },
        { question: "Who holds the record for most consecutive games with a hit (56)?", answers: ["Joe DiMaggio", "Pete Rose", "Ty Cobb", "Willie Keeler"], correct: 0 },
        { question: "Which center fielder won 12 Gold Glove Awards?", answers: ["Willie Mays", "Ken Griffey Jr.", "Andruw Jones", "Mike Trout"], correct: 0 },
        { question: "Which center fielder batted .366 lifetime?", answers: ["Ty Cobb", "Rogers Hornsby", "Shoeless Joe Jackson", "Tris Speaker"], correct: 0 },
        { question: "Who won the Triple Crown in 1956?", answers: ["Mickey Mantle", "Ted Williams", "Willie Mays", "Hank Aaron"], correct: 0 },
        { question: "Which center fielder hit 660 home runs?", answers: ["Willie Mays", "Ken Griffey Jr.", "Mickey Mantle", "Mike Trout"], correct: 0 },
        { question: "Who was the 1989 AL MVP?", answers: ["Robin Yount", "Ruben Sierra", "Kirby Puckett", "Bo Jackson"], correct: 0 },
        { question: "Which center fielder batted .356 in 1920?", answers: ["Tris Speaker", "Ty Cobb", "Babe Ruth", "George Sisler"], correct: 0 },
        { question: "Who won back-to-back MVP awards in 1965-1966?", answers: ["Willie Mays", "Frank Robinson", "Roberto Clemente", "Mickey Mantle"], correct: 0 },
        { question: "Which center fielder won the 1997 NL MVP?", answers: ["Larry Walker", "Andres Galarraga", "Sammy Sosa", "Craig Biggio"], correct: 0 },
        { question: "Who hit 630 home runs?", answers: ["Ken Griffey Jr.", "Willie Mays", "Mickey Mantle", "Mike Trout"], correct: 0 },
        { question: "Which center fielder won the 2014 AL MVP?", answers: ["Mike Trout", "Josh Hamilton", "Jose Abreu", "Michael Brantley"], correct: 0 },
        { question: "Who was the 1951 AL MVP?", answers: ["Yogi Berra", "Phil Rizzuto", "Joe DiMaggio", "Mickey Mantle"], correct: 0 },
        { question: "Which center fielder batted .349 in 1950?", answers: ["Duke Snider", "Willie Mays", "Mickey Mantle", "Dom DiMaggio"], correct: 0 },
        { question: "Who won the 1986 AL MVP?", answers: ["Roger Clemens", "Wade Boggs", "Don Mattingly", "Cal Ripken Jr."], correct: 0 },
        { question: "Which center fielder won the 2005 NL MVP?", answers: ["Albert Pujols", "Andruw Jones", "Miguel Cabrera", "Derrek Lee"], correct: 0 },
        { question: "Who was the 1939 AL MVP?", answers: ["Joe DiMaggio", "Ted Williams", "Jimmie Foxx", "Bill Dickey"], correct: 0 },
        { question: "Which center fielder hit 511 home runs?", answers: ["Ken Griffey Jr.", "Willie Mays", "Mickey Mantle", "Duke Snider"], correct: 0 },
        { question: "Who won the 1990 AL MVP?", answers: ["Rickey Henderson", "Jose Canseco", "Mark McGwire", "Wade Boggs"], correct: 0 },
        { question: "Which center fielder won the 2016 AL MVP?", answers: ["Mike Trout", "Josh Donaldson", "Mookie Betts", "David Ortiz"], correct: 0 },
        { question: "Who was the 1947 NL MVP?", answers: ["Bob Elliott", "Ralph Kiner", "Stan Musial", "Enos Slaughter"], correct: 0 },
        { question: "Which center fielder batted .340 in 1962?", answers: ["Maury Wills", "Ron Hansen", "Tommy Davis", "Willie Davis"], correct: 0 },
        { question: "Who won the 1982 NL MVP?", answers: ["Dale Murphy", "Mike Schmidt", "Tim Raines", "Pedro Guerrero"], correct: 0 },
        { question: "Which center fielder won the 2019 NL MVP?", answers: ["Christian Yelich", "Cody Bellinger", "Nolan Arenado", "Paul Goldschmidt"], correct: 0 }
    ],
    "RF": [
        { question: "Which right fielder hit 73 home runs in 2001?", answers: ["Mark McGwire", "Barry Bonds", "Sammy Sosa", "Aaron Judge"], correct: 1 },
        { question: "Which right fielder won the 2017 AL MVP?", answers: ["Aaron Judge", "Giancarlo Stanton", "Jose Altuve", "Mookie Betts"], correct: 0 },
        { question: "Which right fielder collected exactly 3,000 hits?", answers: ["Roberto Clemente", "Hank Aaron", "Al Kaline", "Tony Gwynn"], correct: 0 },
        { question: "Which right fielder won 13 Gold Glove Awards?", answers: ["Roberto Clemente", "Al Kaline", "Ichiro Suzuki", "Dwight Evans"], correct: 0 },
        { question: "Who hit 755 home runs?", answers: ["Hank Aaron", "Babe Ruth", "Barry Bonds", "Willie Mays"], correct: 0 },
        { question: "Which right fielder batted .394 in 1994?", answers: ["Tony Gwynn", "Jeff Bagwell", "Frank Thomas", "Albert Belle"], correct: 0 },
        { question: "Who won eight batting titles?", answers: ["Tony Gwynn", "Honus Wagner", "Rod Carew", "Ty Cobb"], correct: 0 },
        { question: "Which right fielder hit 60 home runs in 1927?", answers: ["Babe Ruth", "Lou Gehrig", "Jimmie Foxx", "Hack Wilson"], correct: 0 },
        { question: "Who was the 1999 NL MVP?", answers: ["Chipper Jones", "Jeff Bagwell", "Sammy Sosa", "Larry Walker"], correct: 0 },
        { question: "Which right fielder won the 1992 AL MVP?", answers: ["Dennis Eckersley", "Kirby Puckett", "Roberto Alomar", "Frank Thomas"], correct: 0 },
        { question: "Who hit 521 home runs?", answers: ["Hank Aaron", "Babe Ruth", "Willie Mays", "Frank Robinson"], correct: 0 },
        { question: "Which right fielder won the 2006 NL MVP?", answers: ["Ryan Howard", "Chase Utley", "Jimmy Rollins", "Pat Burrell"], correct: 0 },
        { question: "Who was the 1961 AL MVP?", answers: ["Roger Maris", "Mickey Mantle", "Norm Cash", "Rocky Colavito"], correct: 0 },
        { question: "Which right fielder batted .378 in 1959?", answers: ["Hank Aaron", "Willie Mays", "Eddie Mathews", "Orlando Cepeda"], correct: 0 },
        { question: "Who won the 1987 NL MVP?", answers: ["Andre Dawson", "Ryne Sandberg", "Rick Sutcliffe", "Lee Smith"], correct: 0 },
        { question: "Which right fielder won the 2013 NL MVP?", answers: ["Andrew McCutchen", "Yadier Molina", "Carlos Gomez", "Paul Goldschmidt"], correct: 0 },
        { question: "Who was the 1949 NL MVP?", answers: ["Ralph Kiner", "Stan Musial", "Enos Slaughter", "Red Schoendienst"], correct: 0 },
        { question: "Which right fielder hit 49 home runs in 1969?", answers: ["Willie Mays", "Hank Aaron", "Willie McCovey", "Ron Hansen"], correct: 0 },
        { question: "Who won the 1995 NL MVP?", answers: ["Barry Larkin", "Jeff Bagwell", "Craig Biggio", "Dante Bichette"], correct: 0 },
        { question: "Which right fielder won the 2008 NL MVP?", answers: ["Albert Pujols", "Ryan Ludwick", "Chris Carpenter", "Troy Glaus"], correct: 0 },
        { question: "Who was the 1952 AL MVP?", answers: ["Bobby Shantz", "Larry Doby", "Al Rosen", "Phil Rizzuto"], correct: 0 },
        { question: "Which right fielder batted .355 in 1960?", answers: ["Ron Hansen", "Willie Mays", "Hank Aaron", "Frank Robinson"], correct: 0 },
        { question: "Who won the 1980 NL MVP?", answers: ["Mike Schmidt", "Keith Hernandez", "Pete Rose", "Greg Luzinski"], correct: 0 },
        { question: "Which right fielder won the 2015 NL MVP?", answers: ["Bryce Harper", "Nolan Arenado", "Paul Goldschmidt", "Andrew McCutchen"], correct: 0 },
        { question: "Who was the 1946 NL MVP?", answers: ["Stan Musial", "Enos Slaughter", "Red Schoendienst", "Marty Marion"], correct: 0 }
    ],
    "DH": [
        { question: "Who was the first designated hitter in MLB history?", answers: ["Reggie Jackson", "Ron Blomberg", "Harold Baines", "Edgar Martinez"], correct: 1 },
        { question: "Which DH won two AL MVP awards with the Red Sox?", answers: ["David Ortiz", "Edgar Martinez", "Frank Thomas", "Jim Rice"], correct: 0 },
        { question: "Who hit the most home runs as a DH?", answers: ["David Ortiz", "Frank Thomas", "Harold Baines", "Edgar Martinez"], correct: 0 },
        { question: "Which DH is the only two-way player to win MVP unanimously?", answers: ["Shohei Ohtani", "Babe Ruth", "Frank Thomas", "David Ortiz"], correct: 0 },
        { question: "Which DH retired with a .418 on-base percentage?", answers: ["Frank Thomas", "Edgar Martinez", "David Ortiz", "Harold Baines"], correct: 0 },
        { question: "Who won back-to-back AL MVP awards in 1993-1994?", answers: ["Frank Thomas", "Ken Griffey Jr.", "Albert Belle", "Mo Vaughn"], correct: 0 },
        { question: "Which DH won seven Silver Slugger Awards?", answers: ["Edgar Martinez", "David Ortiz", "Frank Thomas", "Jim Thome"], correct: 0 },
        { question: "Who hit .330 over 18 seasons?", answers: ["Edgar Martinez", "Paul Molitor", "Wade Boggs", "Tony Gwynn"], correct: 0 },
        { question: "Who won the 1984 AL MVP?", answers: ["Willie Hernandez", "Dave Winfield", "Cal Ripken Jr.", "Don Mattingly"], correct: 0 },
        { question: "Which DH hit 541 home runs?", answers: ["Frank Thomas", "Jim Thome", "David Ortiz", "Manny Ramirez"], correct: 0 },
        { question: "Who won the 2005 AL MVP?", answers: ["Alex Rodriguez", "Vladimir Guerrero", "Manny Ramirez", "David Ortiz"], correct: 0 },
        { question: "Which DH batted .356 in 1994?", answers: ["Paul Molitor", "Frank Thomas", "Albert Belle", "Ken Griffey Jr."], correct: 0 },
        { question: "Who won the 1991 AL MVP?", answers: ["Cal Ripken Jr.", "Rickey Henderson", "Cecil Fielder", "Frank Thomas"], correct: 0 },
        { question: "Which DH won the 2013 AL MVP?", answers: ["Miguel Cabrera", "Prince Fielder", "Chris Davis", "Josh Donaldson"], correct: 0 },
        { question: "Who was the 1981 AL MVP?", answers: ["Rickey Henderson", "Dwight Evans", "Carl Yastrzemski", "Fred Lynn"], correct: 0 },
        { question: "Which DH batted .363 in 1987?", answers: ["Paul Molitor", "Wade Boggs", "Don Mattingly", "George Brett"], correct: 0 },
        { question: "Who won the 1997 AL MVP?", answers: ["Ken Griffey Jr.", "Alex Rodriguez", "Tino Martinez", "Bernie Williams"], correct: 0 },
        { question: "Which DH won the 2009 AL MVP?", answers: ["Joe Mauer", "Justin Morneau", "Jason Kubel", "Michael Cuddyer"], correct: 0 },
        { question: "Who was the 1979 AL MVP?", answers: ["Don Baylor", "Fred Lynn", "Carl Yastrzemski", "Jim Rice"], correct: 0 },
        { question: "Which DH batted .349 in 1990?", answers: ["Wade Boggs", "Rickey Henderson", "Paul Molitor", "George Brett"], correct: 0 },
        { question: "Who won the 1986 AL MVP?", answers: ["Roger Clemens", "Wade Boggs", "Don Mattingly", "Cal Ripken Jr."], correct: 0 },
        { question: "Which DH won the 2011 AL MVP?", answers: ["Jacoby Ellsbury", "Adrian Gonzalez", "Curtis Granderson", "Mark Teixeira"], correct: 0 },
        { question: "Who was the 1983 AL MVP?", answers: ["Cal Ripken Jr.", "Eddie Murray", "Rick Dempsey", "Scott McGregor"], correct: 0 },
        { question: "Which DH batted .325 in 1985?", answers: ["Don Mattingly", "Wade Boggs", "Rickey Henderson", "George Brett"], correct: 0 },
        { question: "Who won the 1998 AL MVP?", answers: ["Juan Gonzalez", "Ivan Rodriguez", "Rafael Palmeiro", "Alex Rodriguez"], correct: 0 }
    ],
    "P": [
        { question: "Who holds the record for most career strikeouts?", answers: ["Randy Johnson", "Roger Clemens", "Steve Carlton", "Nolan Ryan"], correct: 3 },
        { question: "Which pitcher won the most Cy Young Awards?", answers: ["Roger Clemens", "Greg Maddux", "Randy Johnson", "Sandy Koufax"], correct: 0 },
        { question: "Who threw a perfect game in the 1956 World Series?", answers: ["Sandy Koufax", "Bob Gibson", "Don Larsen", "Whitey Ford"], correct: 2 },
        { question: "Which pitcher won five consecutive Cy Young Awards?", answers: ["Roger Clemens", "Greg Maddux", "Randy Johnson", "Pedro Martinez"], correct: 1 },
        { question: "Who has the most career wins?", answers: ["Cy Young", "Walter Johnson", "Pete Alexander", "Warren Spahn"], correct: 0 },
        { question: "Which pitcher struck out 20 batters in a game?", answers: ["Kerry Wood", "Randy Johnson", "Roger Clemens", "Nolan Ryan"], correct: 1 },
        { question: "Who was the first pitcher to win the Cy Young Award?", answers: ["Don Newcombe", "Warren Spahn", "Bob Lemon", "Early Wynn"], correct: 0 },
        { question: "Which pitcher won the MVP and Cy Young in the same year?", answers: ["Bob Gibson", "Sandy Koufax", "Vida Blue", "Denny McLain"], correct: 0 },
        { question: "Who holds the record for most no-hitters?", answers: ["Nolan Ryan", "Sandy Koufax", "Cy Young", "Bob Feller"], correct: 0 },
        { question: "Which pitcher won the 1965 AL MVP?", answers: ["Zoilo Versalles", "Tony Oliva", "Earl Battey", "Mudcat Grant"], correct: 3 },
        { question: "Who threw the first no-hitter in MLB history?", answers: ["A.J. Smith", "George Bradley", "Lee Richmond", "John Montgomery Ward"], correct: 1 },
        { question: "Which pitcher won the Cy Young Award in 1968?", answers: ["Bob Gibson", "Denny McLain", "Don Drysdale", "Juan Marichal"], correct: 1 },
        { question: "Who has the most wins in a single season?", answers: ["Charles Radbourn", "Old Hoss Radbourn", "Guy Hecker", "Tim Keefe"], correct: 0 },
        { question: "Which pitcher struck out 18 batters in a 9-inning game?", answers: ["Randy Johnson", "Kerry Wood", "Roger Clemens", "Nolan Ryan"], correct: 1 },
        { question: "Who won the 1971 AL Cy Young?", answers: ["Vida Blue", "Jim Palmer", "Gaylord Perry", "Ferguson Jenkins"], correct: 0 },
        { question: "Which pitcher threw a perfect game on his birthday?", answers: ["Don Larsen", "Len Barker", "Tom Browning", "Dennis Martinez"], correct: 3 },
        { question: "Who has the most career shutouts?", answers: ["Walter Johnson", "Pete Alexander", "Grover Cleveland Alexander", "Warren Spahn"], correct: 0 },
        { question: "Which pitcher won the 1995 NL Cy Young?", answers: ["Greg Maddux", "Tom Glavine", "John Smoltz", "Randy Johnson"], correct: 0 },
        { question: "Who threw the only no-hitter in World Series history?", answers: ["Don Larsen", "Bob Gibson", "Sandy Koufax", "Whitey Ford"], correct: 0 },
        { question: "Which pitcher won the 1981 NL Cy Young?", answers: ["Fernando Valenzuela", "Steve Carlton", "Tom Seaver", "Nolan Ryan"], correct: 0 },
        { question: "Who has the most consecutive wins?", answers: ["Carl Hubbell", "Rube Marquard", "Jack Chesbro", "Smokey Joe Wood"], correct: 1 },
        { question: "Which pitcher won the 2000 AL Cy Young?", answers: ["Pedro Martinez", "Roger Clemens", "Randy Johnson", "Greg Maddux"], correct: 0 },
        { question: "Who threw the first perfect game in the American League?", answers: ["Cy Young", "Addie Joss", "Chief Bender", "Eddie Plank"], correct: 1 },
        { question: "Which pitcher won the 1969 AL Cy Young?", answers: ["Denny McLain", "Mike Cuellar", "Dave McNally", "Jim Palmer"], correct: 0 },
        { question: "Who has the most strikeouts in a single game?", answers: ["Kerry Wood", "Randy Johnson", "Roger Clemens", "Nolan Ryan"], correct: 0 }
    ]
};









