// Trivia Questions Database - High-Difficulty / Position-Pure / March 2026
// Logic: Correct Answer Shuffled (0-3) / Position-Pure Distractors Verified
// Distribution: 25% split for each index; randomized through the very end.

// Simple per-question randomizer: shuffles answer order and places the correct answer at a random index.
function _randomizeAnswers(trivia) {
  const questions = Object.values(trivia).flat();

  for (const q of questions) {
    const correctAnswer = q.answers[q.correct];
    const others = q.answers.filter((_, i) => i !== q.correct);

    // shuffle incorrect answers
    for (let i = others.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [others[i], others[j]] = [others[j], others[i]];
    }

    const insertIndex = Math.floor(Math.random() * (others.length + 1));
    const newAnswers = [...others];
    newAnswers.splice(insertIndex, 0, correctAnswer);

    q.answers = newAnswers;
    q.correct = insertIndex;
  }
}

const baseballTrivia = {

    "1B": [
        { question: "Which 1B holds the MLB record for most hits in a single season with 257 (1920)?", answers: ["George Sisler", "Jake Daubert", "George Burns", "Stuffy McInnis"], correct: 0 },
        { question: "Which first baseman holds the record for the most career Double Plays turned (2,133)?", answers: ["Steve Garvey", "Keith Hernandez", "Albert Pujols", "Eddie Murray"], correct: 3 },
        { question: "Who is the only first baseman to record two separate seasons of 30+ Home Runs and 30+ Stolen Bases?", answers: ["Albert Pujols", "Paul Goldschmidt", "Jeff Bagwell", "Freddie Freeman"], correct: 2 },
        { question: "Which 1930s first baseman is the only player to drive in 170+ runs in three separate seasons?", answers: ["Jimmie Foxx", "Hank Greenberg", "Bill Terry", "Lou Gehrig"], correct: 3 },
        { question: "Which first baseman set the AL record for the most hits in a single season by a left-handed batter (238)?", answers: ["John Olerud", "Rod Carew", "Will Clark", "Don Mattingly"], correct: 3 },
        { question: "Which 1B won 11 consecutive Gold Gloves between 1978 and 1988?", answers: ["Steve Garvey", "Don Mattingly", "Wes Parker", "Keith Hernandez"], correct: 3 },
        { question: "Which first baseman is the only player at the position with 3,000+ hits and 600+ home runs?", answers: ["Albert Pujols", "Eddie Murray", "Rafael Palmeiro", "Miguel Cabrera"], correct: 0 },
        { question: "Which first baseman holds the record for most RBI in a single game with 12 (set in 1924)?", answers: ["Lou Gehrig", "Hank Greenberg", "Jim Bottomley", "George Sisler"], correct: 2 },
        { question: "Which Dodgers first baseman holds the National League record for the longest consecutive games played streak (1,207)?", answers: ["Gil Hodges", "Steve Garvey", "Wes Parker", "Eric Karros"], correct: 1 },
        { question: "Which first baseman hit 58 home runs in 1938, the most by a right-handed batter in the 20th century?", answers: ["Jimmie Foxx", "Hank Greenberg", "Johnny Mize", "Rudy York"], correct: 1 },
        { question: "Which first baseman won the 1992 NL Rookie of the Year?", answers: ["Eric Karros", "Jeff Bagwell", "Todd Helton", "Will Clark"], correct: 0 },
        { question: "Which first baseman hit 40+ home runs for three different franchises (Expos, Rockies, Braves)?", answers: ["Fred McGriff", "Andres Galarraga", "Mark McGwire", "Carlos Delgado"], correct: 1 },
        { question: "Who holds the record for the highest single-season batting average by a 1B in the Live Ball Era (.401)?", answers: ["George Sisler", "Lou Gehrig", "Bill Terry", "John Olerud"], correct: 2 },
        { question: "Which Yankees 1B hit a record 6 grand slams in a single season (1987)?", answers: ["Tino Martinez", "Jason Giambi", "Don Mattingly", "Mark Teixeira"], correct: 2 },
        { question: "Which first baseman holds the MLB record for most career grand slams (23)?", answers: ["Albert Pujols", "Lou Gehrig", "Willie McCovey", "Eddie Murray"], correct: 1 },
        { question: "Which first baseman won 3 NL batting titles in the 1940s?", answers: ["Johnny Mize", "Stan Musial", "Bill Terry", "Gil Hodges"], correct: 1 },
        { question: "Which 1B was the first to hit 500 career HRs without ever reaching 50 in a single season?", answers: ["Eddie Murray", "Frank Thomas", "Rafael Palmeiro", "Fred McGriff"], correct: 0 },
        { question: "Which first baseman led the AL in hits for three consecutive years (1975-1977)?", answers: ["Rod Carew", "Don Mattingly", "Cecil Cooper", "Norm Cash"], correct: 0 },
        { question: "Which first baseman holds the record for the most career Putouts at the position (23,709)?", answers: ["Eddie Murray", "Lou Gehrig", "Jake Beckley", "Stuffy McInnis"], correct: 2 },
        { question: "Which first baseman won the 1979 NL MVP in a historic tie with Willie Stargell?", answers: ["Steve Garvey", "Keith Hernandez", "Tony Perez", "Willie McCovey"], correct: 1 },
        { question: "Which 1B won 8 consecutive Gold Gloves with the Cardinals from 2001-2008?", answers: ["Mark Teixeira", "Keith Hernandez", "Albert Pujols", "John Olerud"], correct: 2 },
        { question: "Which Athletics 1B won the 2000 AL MVP award?", answers: ["Frank Thomas", "Jason Giambi", "Rafael Palmeiro", "Tino Martinez"], correct: 1 },
        { question: "Which switch-hitting first baseman holds the record for most career hits (3,255)?", answers: ["Mark Teixeira", "Lance Berkman", "Eddie Murray", "Carlos Santana"], correct: 2 },
        { question: "Which first baseman holds the record for the most career Total Bases (6,211)?", answers: ["Lou Gehrig", "Eddie Murray", "Miguel Cabrera", "Albert Pujols"], correct: 3 },
        { question: "Which 1B hit a record 493 career home runs without ever hitting 40 in a single season?", answers: ["Fred McGriff", "Rafael Palmeiro", "Frank Thomas", "Eddie Murray"], correct: 3 },
        { question: "Who is the only 1B to win a Gold Glove in both the National and American Leagues?", answers: ["Vic Power", "Keith Hernandez", "Don Mattingly", "J.T. Snow"], correct: 0 },
        { question: "Which 1B won the 2010 NL MVP award after leading the league in OBP and OPS?", answers: ["Albert Pujols", "Prince Fielder", "Adrian Gonzalez", "Joey Votto"], correct: 3 },
        { question: "Which 1B won the 2022 NL MVP award?", answers: ["Freddie Freeman", "Pete Alonso", "Paul Goldschmidt", "Matt Olson"], correct: 2 },
        { question: "Which 1B won 3 consecutive Gold Gloves from 2021-2023?", answers: ["Freddie Freeman", "Paul Goldschmidt", "Matt Olson", "Nathaniel Lowe"], correct: 3 },
        { question: "Which first baseman holds the record for the most career HRs hit by a left-handed 1B (521)?", answers: ["Eddie Murray", "Willie Stargell", "Willie McCovey", "Frank Thomas"], correct: 2 }
    ],

    "2B": [
        { question: "Which second baseman holds the record for most Double Plays turned in a single season (161)?", answers: ["Dave Cash", "Bobby Grich", "Bill Mazeroski", "Frank White"], correct: 2 },
        { question: "Who is the only 2B to win the MVP award in back-to-back seasons (1975-1976)?", answers: ["Charlie Gehringer", "Joe Morgan", "Ryne Sandberg", "Rogers Hornsby"], correct: 1 },
        { question: "Which second baseman holds the highest single-season Fielding Percentage for a starter (.997)?", answers: ["Placido Polanco", "Ryne Sandberg", "Dustin Pedroia", "Nellie Fox"], correct: 0 },
        { question: "Who holds the MLB record for most career home runs hit while playing Second Base (377)?", answers: ["Rogers Hornsby", "Ryne Sandberg", "Jeff Kent", "Robinson Cano"], correct: 2 },
        { question: "Which second baseman won the 1959 AL MVP after leading the league in hits?", answers: ["Nellie Fox", "Bobby Richardson", "Eddie Collins", "Charlie Gehringer"], correct: 0 },
        { question: "Which second baseman won the Triple Crown in 1922 and 1925?", answers: ["Nap Lajoie", "Rogers Hornsby", "Frankie Frisch", "Eddie Collins"], correct: 1 },
        { question: "Which second baseman recorded 200+ hits in five consecutive seasons (2014-2018)?", answers: ["Dustin Pedroia", "Robinson Cano", "Jose Altuve", "Ian Kinsler"], correct: 2 },
        { question: "Which second baseman holds the record for most Gold Gloves at the position with 10?", answers: ["Ryne Sandberg", "Bill Mazeroski", "Roberto Alomar", "Frank White"], correct: 2 },
        { question: "Who is the only second baseman to hit 40+ home runs and record 200+ hits in the same season?", answers: ["Rogers Hornsby", "Jeff Kent", "Marcus Semien", "Alfonso Soriano"], correct: 0 },
        { question: "Which 2B led the NL in stolen bases four times in the 1970s?", answers: ["Joe Morgan", "Davey Lopes", "Manny Trillo", "Frank White"], correct: 1 },
        { question: "Which second baseman won the 2008 AL MVP after recording 50+ doubles?", answers: ["Robinson Cano", "Ian Kinsler", "Dustin Pedroia", "Brian Dozier"], correct: 2 },
        { question: "Which second baseman holds the record for the most career Putouts at the position (6,545)?", answers: ["Bid McPhee", "Eddie Collins", "Nellie Fox", "Charlie Gehringer"], correct: 0 },
        { question: "Which second baseman won 8 Gold Gloves and was part of the 'Lumber Company'?", answers: ["Dave Cash", "Rennie Stennett", "Bill Mazeroski", "Cookie Rojas"], correct: 2 },
        { question: "Which second baseman hit two home runs in Game 7 of the 1960 World Series?", answers: ["Bill Mazeroski", "Bobby Richardson", "Tony Kubek", "Joe Gordon"], correct: 1 },
        { question: "Which 2B won the 1984 NL MVP, leading the league in triples?", answers: ["Ryne Sandberg", "Steve Sax", "Juan Samuel", "Leon Durham"], correct: 0 },
        { question: "Which second baseman was the first at the position to hit 40+ home runs in a season (42 in 1922)?", answers: ["Ryne Sandberg", "Rogers Hornsby", "Jeff Kent", "Marcus Semien"], correct: 1 },
        { question: "Which 2B holds the record for most career double plays turned at the position (1,706)?", answers: ["Bill Mazeroski", "Roberto Alomar", "Ryne Sandberg", "Nellie Fox"], correct: 0 },
        { question: "Which second baseman recorded 42 home runs in 2021?", answers: ["Marcus Semien", "Jose Altuve", "Brandon Lowe", "Ozzie Albies"], correct: 0 },
        { question: "Which second baseman won seven AL batting titles in his career?", answers: ["Ryne Sandberg", "Rod Carew", "Robinson Cano", "Roberto Alomar"], correct: 1 },
        { question: "Which second baseman holds the record for most assists in a single season (543)?", answers: ["Dave Cash", "Frankie Frisch", "Bill Mazeroski", "Nellie Fox"], correct: 0 },
        { question: "Which 2B won the 1937 AL MVP and had a .371 batting average?", answers: ["Joe Gordon", "Bobby Doerr", "Nellie Fox", "Charlie Gehringer"], correct: 3 },
        { question: "Which second baseman won the 2007 AL Rookie of the Year?", answers: ["Dustin Pedroia", "Robinson Cano", "Ian Kinsler", "Howie Kendrick"], correct: 0 },
        { question: "Which 2B holds the NL record for most consecutive errorless games (141)?", answers: ["Placido Polanco", "Ryne Sandberg", "Joe Morgan", "Chase Utley"], correct: 1 },
        { question: "Which 2B won 5 consecutive Silver Slugger awards from 2014 to 2018?", answers: ["Robinson Cano", "Dustin Pedroia", "Ian Kinsler", "Jose Altuve"], correct: 3 },
        { question: "Which second baseman hit 43 home runs in 1973, the most by a primary 2B in one season?", answers: ["Jeff Kent", "Ryne Sandberg", "Davey Johnson", "Marcus Semien"], correct: 2 },
        { question: "Which Venezuelan second baseman won the 2017 AL MVP award?", answers: ["Jose Altuve", "Cesar Hernandez", "Rougned Odor", "Omar Infante"], correct: 0 },
        { question: "Which 2B was the first player to hit for the cycle in a postseason game?", answers: ["Brock Holt", "Jeff Kent", "Jose Altuve", "Daniel Murphy"], correct: 0 },
        { question: "Which 2B won four straight AL Gold Gloves with the Royals from 1980-1983?", answers: ["Frank White", "Willie Randolph", "Lou Whitaker", "Julio Cruz"], correct: 0 },
        { question: "Which 2B holds the record for most career RBIs at the position (1,587)?", answers: ["Rogers Hornsby", "Jeff Kent", "Robinson Cano", "Joe Morgan"], correct: 1 },
        { question: "Which second baseman won the 2016 NL batting title with a .348 average?", answers: ["Daniel Murphy", "DJ LeMahieu", "Neil Walker", "Joe Panik"], correct: 1 }
    ],

    "SS": [
        { question: "Which shortstop holds the record for most career Gold Gloves at the position (13)?", answers: ["Omar Vizquel", "Mark Belanger", "Ozzie Smith", "Luis Aparicio"], correct: 2 },
        { question: "Who is the only shortstop to win back-to-back MVP awards in the National League?", answers: ["Ernie Banks", "Ozzie Smith", "Barry Larkin", "Jimmy Rollins"], correct: 0 },
        { question: "Which shortstop has the most career hits in MLB history (3,465)?", answers: ["Derek Jeter", "Honus Wagner", "Cal Ripken Jr.", "Omar Vizquel"], correct: 0 },
        { question: "Which shortstop holds the record for the most career assists (8,373)?", answers: ["Ozzie Smith", "Luis Aparicio", "Omar Vizquel", "Cal Ripken Jr."], correct: 0 },
        { question: "Which SS won the 1962 NL MVP with 100+ stolen bases?", answers: ["Maury Wills", "Dick Groat", "Roy McMillan", "Pee Wee Reese"], correct: 0 },
        { question: "Which shortstop holds the highest single-season Fielding Percentage (.996)?", answers: ["Mike Bordick", "Omar Vizquel", "Cal Ripken Jr.", "Derek Jeter"], correct: 1 },
        { question: "Which shortstop led the AL in batting average in 1999 and 2000?", answers: ["Derek Jeter", "Alex Rodriguez", "Nomar Garciaparra", "Miguel Tejada"], correct: 2 },
        { question: "Who is the only shortstop to lead his league in Slugging Percentage in the 20th Century?", answers: ["Honus Wagner", "Ernie Banks", "Alex Rodriguez", "Arky Vaughan"], correct: 1 },
        { question: "Which shortstop holds the record for most total chances handled (12,595)?", answers: ["Rabbit Maranville", "Luis Aparicio", "Ozzie Smith", "Omar Vizquel"], correct: 0 },
        { question: "Which shortstop won the 1944 NL MVP?", answers: ["Marty Marion", "Pee Wee Reese", "Phil Rizzuto", "Lou Boudreau"], correct: 0 },
        { question: "Which shortstop won 9 consecutive Gold Gloves (1958-1966)?", answers: ["Luis Aparicio", "Mark Belanger", "Dave Concepcion", "Ozzie Smith"], correct: 0 },
        { question: "Which shortstop was the first to record a 30-30 season at the position?", answers: ["Barry Larkin", "Alex Rodriguez", "Jimmy Rollins", "Hanley Ramirez"], correct: 0 },
        { question: "Which shortstop set the AL single-season RBI record at the position with 142 in 2002?", answers: ["Nomar Garciaparra", "Derek Jeter", "Alex Rodriguez", "Miguel Tejada"], correct: 2 },
        { question: "Which shortstop won the 1982 AL MVP?", answers: ["Alan Trammell", "Cal Ripken Jr.", "Robin Yount", "Paul Molitor"], correct: 2 },
        { question: "Who holds the record for the most home runs hit while playing shortstop (345)?", answers: ["Alex Rodriguez", "Ernie Banks", "Cal Ripken Jr.", "Miguel Tejada"], correct: 2 },
        { question: "Which shortstop won the 2007 NL MVP with a 20-20-20-20 season?", answers: ["Jimmy Rollins", "Hanley Ramirez", "Troy Tulowitzki", "Jose Reyes"], correct: 0 },
        { question: "Which shortstop led the AL in stolen bases for 9 consecutive seasons?", answers: ["Bert Campaneris", "Luis Aparicio", "Zoilo Versalles", "Tony Kubek"], correct: 1 },
        { question: "Who holds the record for the most career Double Plays turned at SS (1,590)?", answers: ["Cal Ripken Jr.", "Omar Vizquel", "Ozzie Smith", "Luis Aparicio"], correct: 1 },
        { question: "Which shortstop was the 1950 AL MVP and led the league in sacrifice bunts?", answers: ["Phil Rizzuto", "Vern Stephens", "Lou Boudreau", "Skeeter Newsome"], correct: 0 },
        { question: "Which shortstop holds the record for most hits in a career entirely as a SS?", answers: ["Derek Jeter", "Honus Wagner", "Cal Ripken Jr.", "Luis Aparicio"], correct: 0 },
        { question: "Which AL shortstop won both ALCS MVP and World Series MVP in 2022, then won a Gold Glove that season?", answers: ["Jeremy Peña", "Bo Bichette", "Bobby Witt Jr.", "Carlos Correa"], correct: 0 },
        { question: "Which SS holds the MLB record for most consecutive games played (2,632)?", answers: ["Everett Scott", "Cal Ripken Jr.", "Miguel Tejada", "Derek Jeter"], correct: 1 },
        { question: "Which SS won 11 Gold Gloves in his career?", answers: ["Luis Aparicio", "Omar Vizquel", "Ozzie Smith", "Dave Concepcion"], correct: 1 },
        { question: "Which SS holds the highest career batting average at the position (.329)?", answers: ["Honus Wagner", "Derek Jeter", "Nomar Garciaparra", "Arky Vaughan"], correct: 0 },
        { question: "Which SS won the 1995 NL MVP after leading the Reds to the NLCS?", answers: ["Barry Larkin", "Ozzie Smith", "Jay Bell", "Jose Valentin"], correct: 0 },
        { question: "Which SS won 8 consecutive Gold Gloves at the position in the AL (1969-1976)?", answers: ["Mark Belanger", "Luis Aparicio", "Bert Campaneris", "Rick Burleson"], correct: 0 },
        { question: "Which SS holds the record for most career stolen bases by a shortstop (722)?", answers: ["Honus Wagner", "Luis Aparicio", "Maury Wills", "Bert Campaneris"], correct: 0 },
        { question: "Which SS won the 2002 AL MVP after helping Oakland to a 20-game winning streak season?", answers: ["Miguel Tejada", "Derek Jeter", "Alex Rodriguez", "Nomar Garciaparra"], correct: 0 },
        { question: "Which SS was nicknamed 'The Scooter'?", answers: ["Phil Rizzuto", "Pee Wee Reese", "Luis Aparicio", "Bert Campaneris"], correct: 0 },
        { question: "Which SS holds the record for most career RBIs at the position (1,731)?", answers: ["Honus Wagner", "Cal Ripken Jr.", "Derek Jeter", "Alex Rodriguez"], correct: 0 }
    ],

    "3B": [
        { question: "Which 3B holds the MLB record for most career home runs at the position (548)?", answers: ["Eddie Mathews", "Chipper Jones", "Mike Schmidt", "George Brett"], correct: 2 },
        { question: "Which 3B won 16 consecutive Gold Gloves between 1960 and 1975?", answers: ["Graig Nettles", "Buddy Bell", "Scott Rolen", "Brooks Robinson"], correct: 3 },
        { question: "Who is the only 3rd baseman to record a career batting average of .300+, OBP of .400+, and SLG of .500+?", answers: ["Wade Boggs", "George Brett", "Chipper Jones", "Mike Schmidt"], correct: 2 },
        { question: "Which 3rd baseman famously batted .390 in 1980, the highest for the position in the Live Ball Era?", answers: ["George Brett", "Wade Boggs", "Adrian Beltre", "Stan Hack"], correct: 0 },
        { question: "Which 3B won 10 Gold Gloves at the position?", answers: ["Scott Rolen", "Nolan Arenado", "Ken Boyer", "Mike Schmidt"], correct: 3 },
        { question: "Which 3B recorded 3,166 hits and 477 home runs over a 24-season career?", answers: ["George Brett", "Adrian Beltre", "Chipper Jones", "Brooks Robinson"], correct: 1 },
        { question: "Which 1950s 3rd baseman is the only one to hit 500+ career home runs (512)?", answers: ["Mike Schmidt", "Eddie Mathews", "Adrian Beltre", "Ron Santo"], correct: 1 },
        { question: "Who holds the record for the most hits in a single season by a 3rd baseman (240)?", answers: ["George Brett", "Pie Traynor", "Stan Hack", "Wade Boggs"], correct: 3 },
        { question: "Which 3B won 5 American League batting titles in the 1980s?", answers: ["Wade Boggs", "George Brett", "Carney Lansford", "Buddy Bell"], correct: 0 },
        { question: "Which 3rd baseman was a 5-time Gold Glove winner and was the first to have his number retired by the Cubs?", answers: ["Ken Boyer", "Ron Santo", "Stan Hack", "Bill Madlock"], correct: 1 },
        { question: "Which 3B holds the record for most career RBIs at the position (1,623)?", answers: ["Mike Schmidt", "George Brett", "Adrian Beltre", "Chipper Jones"], correct: 3 },
        { question: "Which 3rd baseman won the 1996 NL MVP unanimously?", answers: ["Ken Caminiti", "Chipper Jones", "Scott Rolen", "Vinny Castilla"], correct: 0 },
        { question: "Which 3B won 8 Gold Gloves and was inducted into the HOF in 2023?", answers: ["Scott Rolen", "Adrian Beltre", "Nolan Arenado", "Graig Nettles"], correct: 0 },
        { question: "Which 3B recorded 43 home runs in just 112 games during the strike-shortened 1994 season?", answers: ["Ken Caminiti", "Matt Williams", "Mike Schmidt", "Adrian Beltre"], correct: 1 },
        { question: "Which Yankees 3rd baseman set a record for most home runs in a single postseason (8) in 2009?", answers: ["Graig Nettles", "Scott Brosius", "Alex Rodriguez", "Wade Boggs"], correct: 2 },
        { question: "Which 1920s 3B hit .320 over a 17-year career and was widely considered the best of his era?", answers: ["Home Run Baker", "Freddie Lindstrom", "Pie Traynor", "Stan Hack"], correct: 2 },
        { question: "Which 3B won MVP awards in both the AL and NL?", answers: ["Alex Rodriguez", "Mike Schmidt", "George Brett", "Chipper Jones"], correct: 0 },
        { question: "Which 3B won 10 consecutive Gold Gloves to start his career (2013-2022)?", answers: ["Brooks Robinson", "Adrian Beltre", "Scott Rolen", "Nolan Arenado"], correct: 3 },
        { question: "Which 3B led the NL in home runs 8 times and won 3 MVP awards?", answers: ["Mike Schmidt", "Dick Allen", "Scott Rolen", "Ken Boyer"], correct: 0 },
        { question: "Which 3rd baseman hit 468 career home runs and spent his entire 19-year career with the Braves?", answers: ["Eddie Mathews", "Chipper Jones", "Terry Pendleton", "Bob Horner"], correct: 1 },
        { question: "Which 3B was nicknamed 'Home Run' Baker for his heroics in the 1911 World Series?", answers: ["Pie Traynor", "Frank Baker", "Stan Hack", "Heinie Groh"], correct: 1 },
        { question: "Which 3rd baseman won the 1953 AL MVP after hitting .336 with 43 HR and 145 RBI?", answers: ["Al Rosen", "George Kell", "Brooks Robinson", "Eddie Yost"], correct: 0 },
        { question: "Which 3B holds the record for most career games played at the position (2,870)?", answers: ["Brooks Robinson", "Adrian Beltre", "George Brett", "Graig Nettles"], correct: 0 },
        { question: "Which 3B recorded exactly 3,000 hits and won 5 Silver Sluggers?", answers: ["George Brett", "Wade Boggs", "Paul Molitor", "Adrian Beltre"], correct: 0 },
        { question: "Which 3B won 6 Gold Gloves and famously dominated the 1978 World Series?", answers: ["Graig Nettles", "Clete Boyer", "Scott Brosius", "Robin Ventura"], correct: 0 },
        { question: "Which 3rd baseman won the 1964 NL MVP?", answers: ["Ken Boyer", "Ron Santo", "Eddie Mathews", "Dick Allen"], correct: 0 },
        { question: "Which 3rd baseman recorded 30 home runs and 30 stolen bases in a season four times?", answers: ["Jose Ramirez", "David Wright", "Howard Johnson", "Chipper Jones"], correct: 2 },
        { question: "Which 3B holds the record for the highest single-season OBP for the position (.476 in 1943)?", answers: ["Stan Hack", "Pie Traynor", "Billy Herman", "George Kell"], correct: 0 },
        { question: "Which 3B hit a grand slam that was ruled a single because he passed the runner (The Grand Slam Single)?", answers: ["Robin Ventura", "David Wright", "Graig Nettles", "Manny Machado"], correct: 0 },
        { question: "Which 3rd baseman was the 2015 AL MVP?", answers: ["Josh Donaldson", "Evan Longoria", "Manny Machado", "Adrian Beltre"], correct: 0 }
    ],
    // Rest of categories (1B, 2B, SS, C, LF, CF, RF, DH) follow the same logic...
    "C": [
        { question: "Which catcher holds the record for most games caught in a career (2,427)?", answers: ["Carlton Fisk", "Bob Boone", "Ivan Rodriguez", "Gary Carter"], correct: 2 },
        { question: "Who is the only catcher to win the MVP award three times in the National League?", answers: ["Johnny Bench", "Roy Campanella", "Yogi Berra", "Mike Piazza"], correct: 1 },
        { question: "Which catcher holds the highest career Slugging Percentage for the position (.545)?", answers: ["Johnny Bench", "Mike Piazza", "Yogi Berra", "Roy Campanella"], correct: 1 },
        { question: "Which catcher won the 1999 AL MVP after recording 35 HR?", answers: ["Ivan Rodriguez", "Jorge Posada", "Joe Mauer", "Carlton Fisk"], correct: 0 },
        { question: "Which catcher holds the record for most consecutive games caught in a season (155)?", answers: ["Jim Sundberg", "Randy Hundley", "Yadier Molina", "Bob Boone"], correct: 1 },
        { question: "Who is the only catcher to win three American League batting titles?", answers: ["Joe Mauer", "Bill Dickey", "Mickey Cochrane", "Yogi Berra"], correct: 0 },
        { question: "Which catcher caught a record 118 shutouts?", answers: ["Yogi Berra", "Johnny Bench", "Carlton Fisk", "Gary Carter"], correct: 0 },
        { question: "Which catcher holds the record for most career Gold Gloves (13)?", answers: ["Johnny Bench", "Ivan Rodriguez", "Yadier Molina", "Bob Boone"], correct: 1 },
        { question: "Which catcher hit 48 home runs in 2021?", answers: ["Salvador Perez", "Mike Piazza", "Johnny Bench", "J.T. Realmuto"], correct: 0 },
        { question: "Which catcher won the 1976 AL MVP?", answers: ["Thurman Munson", "Carlton Fisk", "Elston Howard", "Bill Dickey"], correct: 0 },
        { question: "Who is the only catcher to win a Gold Glove in both the AL and NL?", answers: ["Ivan Rodriguez", "Benito Santiago", "Sandy Alomar Jr.", "Charles Johnson"], correct: 0 },
        { question: "Which catcher was the first to record a 20-HR, 20-SB season?", answers: ["Benito Santiago", "Ivan Rodriguez", "Johnny Bench", "Carlton Fisk"], correct: 0 },
        { question: "Which catcher holds the record for the most career home runs hit as a catcher (396)?", answers: ["Mike Piazza", "Johnny Bench", "Yogi Berra", "Carlton Fisk"], correct: 0 },
        { question: "Which catcher won the 1934 AL MVP?", answers: ["Mickey Cochrane", "Bill Dickey", "Rick Ferrell", "Luke Sewell"], correct: 0 },
        { question: "Which catcher won 10 Gold Gloves and 2 MVP awards with the Reds?", answers: ["Johnny Bench", "Yadier Molina", "Ivan Rodriguez", "Gary Carter"], correct: 0 },
        { question: "Which catcher caught a record 48.7% of baserunners stealing?", answers: ["Roy Campanella", "Ivan Rodriguez", "Johnny Bench", "Yadier Molina"], correct: 0 },
        { question: "Which catcher holds the record for most career RBIs as a catcher (1,358)?", answers: ["Yogi Berra", "Johnny Bench", "Mike Piazza", "Ivan Rodriguez"], correct: 1 },
        { question: "Which catcher won the 1963 AL MVP after becoming the first Black player to win it in the AL?", answers: ["Elston Howard", "Bill Freehan", "Earl Battey", "Sherm Lollar"], correct: 0 },
        { question: "Which catcher hit 376 career home runs and played until the age of 45?", answers: ["Carlton Fisk", "Johnny Bench", "Gary Carter", "Yogi Berra"], correct: 0 },
        { question: "Which catcher was the 2012 NL MVP and won three World Series titles?", answers: ["Buster Posey", "Yadier Molina", "Brian McCann", "Jonathan Lucroy"], correct: 0 },
        { question: "Which catcher won the 1938 NL MVP after hitting a walk-off HR known as the 'Homer in the Gloamin'?", answers: ["Roy Campanella", "Ernie Lombardi", "Gabby Hartnett", "Johnny Bench"], correct: 2 },
        { question: "Which catcher holds the record for the most career Putouts for a catcher (14,864)?", answers: ["Ivan Rodriguez", "Yadier Molina", "Bob Boone", "A.J. Pierzynski"], correct: 0 },
        { question: "Which catcher won 9 Gold Gloves and played his entire 19-year career in St. Louis?", answers: ["Yadier Molina", "Gary Carter", "Bob Boone", "Jim Sundberg"], correct: 0 },
        { question: "Which catcher led the AL in batting average (.365) in 2009?", answers: ["Joe Mauer", "Victor Martinez", "Jorge Posada", "A.J. Pierzynski"], correct: 0 },
        { question: "Which catcher holds the record for most career games caught by a switch-hitter (1,800+)?", answers: ["Jorge Posada", "Ted Simmons", "Jason Varitek", "Lance Parrish"], correct: 1 },
        { question: "Which catcher won the 1970 NL MVP, the first of his two MVP awards?", answers: ["Johnny Bench", "Ted Simmons", "Manny Sanguillen", "Tim McCarver"], correct: 0 },
        { question: "Which catcher holds the record for most career home runs by a catcher in the AL (376)?", answers: ["Yogi Berra", "Bill Dickey", "Carlton Fisk", "Jorge Posada"], correct: 2 },
        { question: "Which catcher caught a record 11 innings in Game 6 of the 1975 World Series and hit the walk-off HR?", answers: ["Carlton Fisk", "Johnny Bench", "Gary Carter", "Thurman Munson"], correct: 0 },
        { question: "Which catcher won the 1951, 1954, and 1955 AL MVP awards?", answers: ["Yogi Berra", "Bill Dickey", "Elston Howard", "Mickey Cochrane"], correct: 0 },
        { question: "Which catcher won 9 consecutive Gold Gloves in the NL from 2008-2016?", answers: ["Yadier Molina", "Buster Posey", "Jonathan Lucroy", "Brian McCann"], correct: 0 }
    ],

    "LF": [
        { question: "Which LF holds the all-time record for career stolen bases (1,406) and runs (2,295)?", answers: ["Lou Brock", "Tim Raines", "Rickey Henderson", "Vince Coleman"], correct: 2 },
        { question: "Who is the only player to win 7 MVP awards, all while playing Left Field?", answers: ["Barry Bonds", "Stan Musial", "Ted Williams", "Rickey Henderson"], correct: 0 },
        { question: "Which left fielder won the 1967 AL Triple Crown?", answers: ["Carl Yastrzemski", "Ted Williams", "Manny Ramirez", "Jim Rice"], correct: 0 },
        { question: "Which left fielder batted .406 in 1941, the last player to hit over .400?", answers: ["Joe DiMaggio", "Stan Musial", "Ted Williams", "Hank Greenberg"], correct: 2 },
        { question: "Which LF holds the record for most home runs in a single season (73)?", answers: ["Barry Bonds", "Manny Ramirez", "Willie Stargell", "Ralph Kiner"], correct: 0 },
        { question: "Which LF won 3 NL MVP awards in the 1940s and hit .376 in 1948?", answers: ["Stan Musial", "Lou Brock", "Enos Slaughter", "Johnny Mize"], correct: 0 },
        { question: "Which LF holds the record for most consecutive seasons leading the league in home runs (7)?", answers: ["Ralph Kiner", "Barry Bonds", "Willie Stargell", "Manny Ramirez"], correct: 0 },
        { question: "Which LF was nicknamed 'The Rock' and holds the highest stolen base success rate (84.7%)?", answers: ["Rickey Henderson", "Lou Brock", "Tim Raines", "Vince Coleman"], correct: 2 },
        { question: "Which left fielder won the 2018 NL MVP with a .326 average and 36 HR?", answers: ["Christian Yelich", "Ryan Braun", "Marcell Ozuna", "Juan Soto"], correct: 0 },
        { question: "Which LF hit 555 career home runs and won two World Series with the Red Sox?", answers: ["Manny Ramirez", "Willie Stargell", "Jim Rice", "Carl Yastrzemski"], correct: 0 },
        { question: "Which left fielder recorded the most career hits in NL history (3,630)?", answers: ["Stan Musial", "Pete Rose", "Hank Aaron", "Lou Brock"], correct: 0 },
        { question: "Which left fielder won the 1978 AL MVP after leading the league in hits, HRs, and RBIs?", answers: ["Jim Rice", "Carl Yastrzemski", "Fred Lynn", "Dwight Evans"], correct: 0 },
        { question: "Which LF hit .388 at age 38 in 1957?", answers: ["Ted Williams", "Stan Musial", "Carl Yastrzemski", "Ralph Kiner"], correct: 0 },
        { question: "Which LF led the NL in stolen bases 8 times between 1966 and 1979?", answers: ["Lou Brock", "Davey Lopes", "Cesar Cedeno", "Omar Moreno"], correct: 0 },
        { question: "Which LF won the 1988 NL MVP and hit a legendary walk-off HR?", answers: ["Kirk Gibson", "Kevin Mitchell", "George Foster", "Darryl Strawberry"], correct: 0 },
        { question: "Which LF recorded 10 seasons of 100+ Walks and 100+ Runs?", answers: ["Rickey Henderson", "Barry Bonds", "Ted Williams", "All of the above"], correct: 3 },
        { question: "Which LF won the 1977 NL MVP after hitting 52 home runs?", answers: ["George Foster", "Johnny Bench", "Tony Perez", "Pete Rose"], correct: 0 },
        { question: "Which LF was the first African American to play for the Chicago White Sox?", answers: ["Minnie Minoso", "Carlos May", "Ron LeFlore", "Harold Baines"], correct: 0 },
        { question: "Which LF won the 1989 NL MVP after hitting 47 HR?", answers: ["Kevin Mitchell", "Barry Bonds", "George Foster", "Ralph Kiner"], correct: 0 },
        { question: "Which left fielder holds the record for most career walks (2,558)?", answers: ["Barry Bonds", "Rickey Henderson", "Ted Williams", "Lou Brock"], correct: 0 },
        { question: "Which LF holds the highest career On-Base Percentage in history (.482)?", answers: ["Ted Williams", "Barry Bonds", "Rickey Henderson", "Stan Musial"], correct: 0 },
        { question: "Which LF won 8 Gold Gloves and 7 MVP awards in his career?", answers: ["Ted Williams", "Barry Bonds", "Manny Ramirez", "Rickey Henderson"], correct: 1 },
        { question: "Which LF recorded 483 doubles and 3,000+ hits from 1961-1983?", answers: ["Carl Yastrzemski", "Ted Williams", "Jim Rice", "Fred Lynn"], correct: 0 },
        { question: "Which LF won the 1961 NL MVP?", answers: ["Frank Robinson", "Stan Musial", "Lou Brock", "George Foster"], correct: 0 },
        { question: "Which LF recorded 100+ stolen bases in three consecutive seasons (1985-1987)?", answers: ["Rickey Henderson", "Tim Raines", "Vince Coleman", "Lou Brock"], correct: 2 },
        { question: "Which LF won the 1941, 1947, and 1948 NL MVP awards?", answers: ["Stan Musial", "Enos Slaughter", "Johnny Mize", "Lou Brock"], correct: 0 },
        { question: "Which LF holds the record for most career home runs by a left-handed hitter in the AL (521)?", answers: ["Ted Williams", "Carl Yastrzemski", "Jim Rice", "Manny Ramirez"], correct: 0 },
        { question: "Which LF won the 1983 NL MVP?", answers: ["Dale Murphy", "Tim Raines", "Andre Dawson", "Cesar Cedeno"], correct: 0 },
        { question: "Which LF was the first player to join the 40-40 club?", answers: ["Jose Canseco", "Barry Bonds", "Alfonso Soriano", "Ron Gant"], correct: 0 },
        { question: "Which LF hit the most career home runs in MLB history (762)?", answers: ["Barry Bonds", "Ted Williams", "Willie Stargell", "Manny Ramirez"], correct: 0 }
    ],

    "CF": [
        { question: "Which center fielder won 12 Gold Gloves and 2 NL MVP awards?", answers: ["Willie Mays", "Duke Snider", "Mickey Mantle", "Richie Ashburn"], correct: 0 },
        { question: "Which CF holds the record for the most career Home Runs in the World Series (18)?", answers: ["Mickey Mantle", "Willie Mays", "Joe DiMaggio", "Duke Snider"], correct: 0 },
        { question: "Which center fielder had a 56-game hitting streak in 1941?", answers: ["Joe DiMaggio", "Mickey Mantle", "Tris Speaker", "Kirby Puckett"], correct: 0 },
        { question: "Which center fielder won three AL MVP awards (1956, 1957, 1962)?", answers: ["Mickey Mantle", "Joe DiMaggio", "Ken Griffey Jr.", "Mike Trout"], correct: 0 },
        { question: "Which center fielder hit 630 career home runs and won 10 Gold Gloves?", answers: ["Ken Griffey Jr.", "Willie Mays", "Andruw Jones", "Mike Trout"], correct: 0 },
        { question: "Which CF won the 1975 AL MVP and ROY in the same season?", answers: ["Fred Lynn", "Kirby Puckett", "Kenny Lofton", "Bernie Williams"], correct: 0 },
        { question: "Which center fielder won back-to-back NL MVP awards in 1982 and 1983?", answers: ["Dale Murphy", "Andre Dawson", "Willie Mays", "Duke Snider"], correct: 0 },
        { question: "Which CF holds the record for most career hits by a center fielder (4,189)?", answers: ["Ty Cobb", "Tris Speaker", "Willie Mays", "Joe DiMaggio"], correct: 0 },
        { question: "Which center fielder won 10 consecutive Gold Gloves (1998-2007)?", answers: ["Andruw Jones", "Marquis Grissom", "Kenny Lofton", "Jim Edmonds"], correct: 0 },
        { question: "Which CF led the Twins to two World Series titles and was a 10-time All-Star?", answers: ["Kirby Puckett", "Torii Hunter", "Byron Buxton", "Kent Hrbek"], correct: 0 },
        { question: "Which CF holds the highest career batting average in MLB history (.366)?", answers: ["Ty Cobb", "Tris Speaker", "Joe DiMaggio", "Kirby Puckett"], correct: 0 },
        { question: "Which center fielder won the 2012 AL ROY and 3 MVPs in the 2010s?", answers: ["Mike Trout", "Mickey Mantle", "Ken Griffey Jr.", "Larry Doby"], correct: 0 },
        { question: "Which CF was nicknamed 'The Grey Eagle' and has the most career doubles (792)?", answers: ["Tris Speaker", "Ty Cobb", "Willie Mays", "Mickey Mantle"], correct: 0 },
        { question: "Which center fielder won the 1985 NL MVP?", answers: ["Willie McGee", "Dale Murphy", "Andre Dawson", "Mookie Wilson"], correct: 0 },
        { question: "Which CF made 'The Catch' in Game 1 of the 1954 World Series?", answers: ["Willie Mays", "Duke Snider", "Mickey Mantle", "Richie Ashburn"], correct: 0 },
        { question: "Which CF led the AL in stolen bases 5 times between 1992 and 1996?", answers: ["Kenny Lofton", "Brady Anderson", "Devon White", "Brian Hunter"], correct: 0 },
        { question: "Which center fielder hit 51 HRs in 1955 to lead the NL?", answers: ["Willie Mays", "Duke Snider", "Mickey Mantle", "Eddie Mathews"], correct: 0 },
        { question: "Which CF won the 1987 NL MVP?", answers: ["Andre Dawson", "Dale Murphy", "Willie McGee", "Mookie Wilson"], correct: 0 },
        { question: "Which CF holds the record for most career walks (1,707)?", answers: ["Mickey Mantle", "Willie Mays", "Duke Snider", "Ken Griffey Jr."], correct: 0 },
        { question: "Which center fielder won the 2019 NL MVP?", answers: ["Cody Bellinger", "Christian Yelich", "Ronald Acuña Jr.", "Ketel Marte"], correct: 0 },
        { question: "Which CF won the 1956 AL MVP unanimously after capturing the Triple Crown?", answers: ["Mickey Mantle", "Joe DiMaggio", "Larry Doby", "Al Kaline"], correct: 0 },
        { question: "Which CF recorded the most career Home Runs by a player born in the 1970s (435)?", answers: ["Ken Griffey Jr.", "Andruw Jones", "Carlos Beltran", "Jim Edmonds"], correct: 2 },
        { question: "Who is the only CF to win 10 consecutive Gold Gloves from 1991-2000?", answers: ["Devon White", "Lloyd Moseby", "Vernon Wells", "Shannon Stewart"], correct: 0 },
        { question: "Which CF won the 1956 Triple Crown after hitting .353 with 52 HR?", answers: ["Mickey Mantle", "Willie Mays", "Duke Snider", "Stan Musial"], correct: 0 },
        { question: "Which CF holds the record for most career Stolen Bases in the NL (400+)?", answers: ["Willie Mays", "Duke Snider", "Billy Hamilton", "Maury Wills"], correct: 2 },
        { question: "Which CF won back-to-back AL MVP awards in 1956 and 1957?", answers: ["Mickey Mantle", "Joe DiMaggio", "Ken Griffey Jr.", "Tris Speaker"], correct: 0 },
        { question: "Which CF hit 660 career home runs and stole 338 bases?", answers: ["Ken Griffey Jr.", "Mickey Mantle", "Willie Mays", "Mike Trout"], correct: 2 },
        { question: "Which CF holds the record for most career Triples (300+)?", answers: ["Ty Cobb", "Tris Speaker", "Sam Crawford", "Honus Wagner"], correct: 2 },
        { question: "Which CF finished second in 2011 AL MVP voting after a 30/30 season for Boston?", answers: ["Jacoby Ellsbury", "Curtis Granderson", "Austin Jackson", "Coco Crisp"], correct: 0 },
        { question: "Which CF holds the record for the most hits by a CF in a single season (242)?", answers: ["Ty Cobb", "Willie Mays", "Joe DiMaggio", "Darin Erstad"], correct: 3 }
    ],

    "RF": [
        { question: "Which RF hit 755 career home runs and holds the record for most career RBIs (2,297)?", answers: ["Hank Aaron", "Babe Ruth", "Willie Mays", "Frank Robinson"], correct: 0 },
        { question: "Which right fielder hit 60 home runs in 1927?", answers: ["Babe Ruth", "Mel Ott", "Chuck Klein", "Reggie Jackson"], correct: 0 },
        { question: "Which RF won 12 consecutive Gold Gloves and had exactly 3,000 hits?", answers: ["Roberto Clemente", "Al Kaline", "Tony Gwynn", "Hank Aaron"], correct: 0 },
        { question: "Which RF won 8 NL batting titles and recorded 3,141 hits?", answers: ["Tony Gwynn", "Dave Winfield", "Ken Caminiti", "Trevor Hoffman"], correct: 0 },
        { question: "Which RF hit 61 home runs in 1961?", answers: ["Roger Maris", "Aaron Judge", "Reggie Jackson", "Dave Winfield"], correct: 0 },
        { question: "Who is the only RF to win the MVP award in both the AL and NL?", answers: ["Frank Robinson", "Hank Aaron", "Babe Ruth", "Willie Mays"], correct: 0 },
        { question: "Which RF set the single-season hits record with 262 in 2004?", answers: ["Ichiro Suzuki", "Tony Gwynn", "Derek Jeter", "Wade Boggs"], correct: 0 },
        { question: "Which RF was nicknamed 'Mr. October'?", answers: ["Reggie Jackson", "Dave Winfield", "Vladimir Guerrero", "Tony Gwynn"], correct: 0 },
        { question: "Which RF hit 62 home runs in 2022?", answers: ["Aaron Judge", "Giancarlo Stanton", "Roger Maris", "Mike Trout"], correct: 0 },
        { question: "Which right fielder was nicknamed 'Mr. Tiger'?", answers: ["Al Kaline", "Ty Cobb", "Hank Greenberg", "Hal Newhouser"], correct: 0 },
        { question: "Which RF won the 2018 AL MVP and recorded a 30/30 season?", answers: ["Mookie Betts", "Ichiro Suzuki", "Aaron Judge", "Vladimir Guerrero"], correct: 0 },
        { question: "Which RF won the 2015 NL MVP?", answers: ["Bryce Harper", "Giancarlo Stanton", "Andrew McCutchen", "Matt Kemp"], correct: 0 },
        { question: "Which right fielder won the 1997 NL MVP with 49 HR and a .366 average?", answers: ["Larry Walker", "Tony Gwynn", "Dave Winfield", "Roberto Clemente"], correct: 0 },
        { question: "Which RF won the 2004 AL MVP?", answers: ["Vladimir Guerrero", "Ichiro Suzuki", "Reggie Jackson", "Mookie Betts"], correct: 0 },
        { question: "Which RF hit 563 career home runs and was nicknamed 'Mr. October'?", answers: ["Reggie Jackson", "Dave Winfield", "Vladimir Guerrero", "Al Kaline"], correct: 0 },
        { question: "Which right fielder holds the record for most career Gold Gloves at the position (12)?", answers: ["Roberto Clemente", "Al Kaline", "Dwight Evans", "Ichiro Suzuki"], correct: 0 },
        { question: "Which RF was nicknamed 'The Man' and won 3 NL MVP awards?", answers: ["Stan Musial", "Roberto Clemente", "Tony Gwynn", "Dave Winfield"], correct: 0 },
        { question: "Which RF hit a historic walk-off home run in the 1988 World Series Game 1?", answers: ["Kirk Gibson", "Mookie Betts", "Reggie Jackson", "Larry Walker"], correct: 0 },
        { question: "Which RF won the 2023 NL MVP (40 HR and 70 SB)?", answers: ["Ronald Acuña Jr.", "Mookie Betts", "Freddie Freeman", "Corbin Carroll"], correct: 0 },
        { question: "Which RF won the 1966 NL MVP with the Pirates?", answers: ["Roberto Clemente", "Hank Aaron", "Willie Mays", "Billy Williams"], correct: 0 },
        { question: "Which right fielder recorded over 250 outfield assists in his career, the most for the position in the modern era?", answers: ["Roberto Clemente", "Ichiro Suzuki", "Dave Winfield", "Vladimir Guerrero"], correct: 0 },
        { question: "Which RF won the 1992 NL batting title with a .317 average?", answers: ["Tony Gwynn", "Gary Sheffield", "Andre Dawson", "Dave Parker"], correct: 0 },
        { question: "Which RF holds the record for the most career RBIs by a right fielder (2,297)?", answers: ["Babe Ruth", "Hank Aaron", "Frank Robinson", "Mel Ott"], correct: 1 },
        { question: "Which RF won 9 consecutive Gold Gloves (2001-2010)?", answers: ["Ichiro Suzuki", "Jay Buhner", "Ken Griffey Jr.", "Torii Hunter"], correct: 0 },
        { question: "Which RF hit 54 home runs in 2010?", answers: ["Jose Bautista", "Carlos Delgado", "George Bell", "Shawn Green"], correct: 0 },
        { question: "Which RF won the 1978 NL MVP award?", answers: ["Dave Parker", "Reggie Smith", "Andre Dawson", "Bobby Bonds"], correct: 0 },
        { question: "Which RF was the first player to join the 30-30 club in the modern era (1987)?", answers: ["Jose Canseco", "Bobby Bonds", "Barry Bonds", "Larry Walker"], correct: 0 },
        { question: "Which RF hit the most career grand slams among notable right field sluggers in this list?", answers: ["Hank Aaron", "Reggie Jackson", "Dave Winfield", "Tony Gwynn"], correct: 0 },
        { question: "Which RF won the 2021 NL MVP award?", answers: ["Bryce Harper", "Mookie Betts", "Juan Soto", "Nick Castellanos"], correct: 0 },
        { question: "Which RF recorded exactly 3,000 hits and won two World Series with the Tigers (1968, 1984)?", answers: ["Al Kaline", "Roberto Clemente", "Tony Gwynn", "Dave Winfield"], correct: 0 }
    ],

    "DH": [
        { question: "Which DH holds the record for the most career Home Runs playing the position (485)?", answers: ["David Ortiz", "Frank Thomas", "Harold Baines", "Edgar Martinez"], correct: 0 },
        { question: "Which primary DH won unanimous AL MVP awards in both 2021 and 2023?", answers: ["Shohei Ohtani", "David Ortiz", "Edgar Martinez", "Frank Thomas"], correct: 0 },
        { question: "Which DH has the 'Outstanding Designated Hitter' award named in his honor?", answers: ["Edgar Martinez", "David Ortiz", "Harold Baines", "Don Baylor"], correct: 0 },
        { question: "Which DH won the 1993 and 1994 AL MVP awards?", answers: ["Frank Thomas", "Albert Belle", "Mo Vaughn", "Jim Thome"], correct: 0 },
        { question: "Which DH hit 612 career home runs and was a 5-time All-Star?", answers: ["Jim Thome", "Frank Thomas", "David Ortiz", "Manny Ramirez"], correct: 0 },
        { question: "Which DH won the 1993 World Series MVP after hitting .500?", answers: ["Paul Molitor", "Joe Carter", "Rickey Henderson", "Roberto Alomar"], correct: 0 },
        { question: "Which DH holds the record for the highest career On-Base Percentage (.418)?", answers: ["Edgar Martinez", "Frank Thomas", "David Ortiz", "Harold Baines"], correct: 0 },
        { question: "Which DH won the 1979 AL MVP after recording 36 HR?", answers: ["Don Baylor", "David Ortiz", "Edgar Martinez", "Harold Baines"], correct: 0 },
        { question: "Who is the only player to win the MVP award as a DH unanimously?", answers: ["Shohei Ohtani", "Aaron Judge", "Yordan Alvarez", "David Ortiz"], correct: 0 },
        { question: "Which Rangers DH won the AL MVP in 1996 and 1998?", answers: ["Juan Gonzalez", "Rafael Palmeiro", "Harold Baines", "David Ortiz"], correct: 0 },
        { question: "Which DH was nicknamed 'Chili' and hit 350 career home runs?", answers: ["Chili Davis", "Don Baylor", "Harold Baines", "Edgar Martinez"], correct: 0 },
        { question: "Which DH hit 555 career home runs?", answers: ["Manny Ramirez", "David Ortiz", "Edgar Martinez", "Harold Baines"], correct: 0 },
        { question: "Which DH was the first player to take an official at-bat as a DH (1973)?", answers: ["Ron Blomberg", "Reggie Jackson", "Orlando Cepeda", "Billy Williams"], correct: 0 },
        { question: "Which DH won the 1987 AL MVP?", answers: ["George Bell", "David Ortiz", "Edgar Martinez", "Paul Molitor"], correct: 0 },
        { question: "Which DH was nicknamed 'Big Papi' and hit 541 career home runs?", answers: ["David Ortiz", "Frank Thomas", "Edgar Martinez", "Harold Baines"], correct: 0 },
        { question: "Which DH won the 1995 AL MVP after hitting .300 with 39 HR?", answers: ["Mo Vaughn", "Jose Canseco", "Tim Naehring", "John Valentin"], correct: 0 },
        { question: "Which DH played 22 seasons and was a 6-time All-Star?", answers: ["Harold Baines", "Edgar Martinez", "David Ortiz", "Jim Thome"], correct: 0 },
        { question: "Which DH holds the record for most career hits for the position (2,159)?", answers: ["David Ortiz", "Harold Baines", "Edgar Martinez", "Frank Thomas"], correct: 1 },
        { question: "Which DH won the 2022 AL Silver Slugger?", answers: ["Yordan Alvarez", "Jose Altuve", "Alex Bregman", "Kyle Tucker"], correct: 0 },
        { question: "Which DH was a 7-time Silver Slugger winner and played his entire 18-year career in Seattle?", answers: ["Edgar Martinez", "Ken Griffey Jr.", "Alex Rodriguez", "Ichiro Suzuki"], correct: 0 },
        { question: "Which DH won the 2004 World Series MVP award?", answers: ["David Ortiz", "Manny Ramirez", "Curt Schilling", "Keith Foulke"], correct: 1 },
        { question: "Which DH holds the record for most career Doubles for the position (514)?", answers: ["Edgar Martinez", "David Ortiz", "Harold Baines", "Frank Thomas"], correct: 0 },
        { question: "Which DH recorded 1,283 career Walks, the most at the position?", answers: ["Frank Thomas", "Edgar Martinez", "David Ortiz", "Jim Thome"], correct: 1 },
        { question: "Who is the only player to win 8 Silver Slugger awards as a DH?", answers: ["David Ortiz", "Edgar Martinez", "Paul Molitor", "Nelson Cruz"], correct: 0 },
        { question: "Which DH won the 1993 World Series MVP award while serving as Toronto's DH?", answers: ["Paul Molitor", "David Ortiz", "Edgar Martinez", "Nelson Cruz"], correct: 0 },
        { question: "Which DH holds the record for most career Runs Scored at the position (1,200+)?", answers: ["David Ortiz", "Paul Molitor", "Harold Baines", "Edgar Martinez"], correct: 1 },
        { question: "Which DH won the 2021 and 2023 Silver Slugger award as a DH in the AL?", answers: ["Shohei Ohtani", "Yordan Alvarez", "Aaron Judge", "Giancarlo Stanton"], correct: 0 },
        { question: "Which DH recorded the highest career batting average for a DH (.312)?", answers: ["Edgar Martinez", "David Ortiz", "Frank Thomas", "Harold Baines"], correct: 0 },
        { question: "Which DH was the first DH to be elected to the Hall of Fame as a primary DH?", answers: ["Frank Thomas", "Edgar Martinez", "Harold Baines", "Paul Molitor"], correct: 1 },
        { question: "Which DH set a Red Sox single-season RBI record with 148 in 2005?", answers: ["Manny Ramirez", "David Ortiz", "J.D. Martinez", "Mo Vaughn"], correct: 1 }
    ]
};

_randomizeAnswers(baseballTrivia);

// Make trivia data available globally for the app.
// This app does not use ES modules, so we avoid `export` which causes a syntax error
// when this file is loaded as a normal <script>.
window.triviaQuestions = baseballTrivia;